rectorphp/rector-src

- .github/workflows/build_scoped_rector_php70.yaml
@samsonasik Currently this workflow makes CI fail everytime. I've got some confusing feedback that Rector is broken and it was caused by another PR contributors.
This should make sure the `main` branch is clean and you can invoke the build with a propper branch name.
Maybe the syntax is sligthly differnt, but the idea should be clear.
> [ci] build PHP70 only on prefixed branches

- packages/FileFormatter/Formatter/YamlFileFormatter.php
- During the Yaml::dump a final new line is already added. No need to add it twice
> [BUGFIX] Remove redundant new line

- src/Application/FileProcessor/PhpFileProcessor.php
- src/PhpParser/Printer/NodesWithFileDestinationPrinter.php
- Closes https://github.com/rectorphp/rector-src/pull/10
- Closes https://github.com/rectorphp/rector/issues/6403
> remove last empty token on new printed content; go for newline by default as best practise conventions

- utils/compiler/src/PhpScoper/StaticEasyPrefixer.php
Resolves: rectorphp/rector#6405
> [TASK] Do not prefix class ComposerJson

- src/Autoloading/BootstrapFilesIncluder.php
When the option bootstrap_files contains a file that does not exist, `vendor/bin/rector process` will crashing with fatal error.
```
PHP Fatal error:  Uncaught TypeError: Exception::__construct(): Argument #2 ($code) must be of type int, string given in /home/runner/work/coding-standard/coding-standard/vendor/rector/rector/src/Exception/ShouldNotHappenException.php:22
```
It is missing `sprintf()` here
https://github.com/rectorphp/rector-src/blob/298c97a3bc72aed972935eea80eae14de2fca35e/src/Autoloading/BootstrapFilesIncluder.php#L29
> Fix fatal error when bootstrap file does not exist

- rules-tests/CodeQuality/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector/Fixture/skip_keys_used.php.inc
- rules/CodeQuality/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector.php
Fixes https://github.com/rectorphp/rector/issues/6424
> [CodeQuality] Skip ArrayKeysAndInArrayToArrayKeyExistsRector on keys variable used

- build/target-repository/composer.json
All these rules are now bundled. Having them installed as separate packages will result in unpredicted behavior.
Follow up from https://github.com/rectorphp/rector-symfony/issues/12
> FX do not allow rector rules packages installed with latest 0.11 rector

- rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/skip_callable_type.php.inc
- rules/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector.php
Fixes https://github.com/rectorphp/rector/issues/6421
> [Php80] Skip callable type on ClassPropertyAssignToConstructorPromotionRector

- build/target-repository/.gitattributes
To remove `e2e` on required via composer: 
```bash
$ composer require rector/rector
$ tree -L 1 -a vendor/rector/rector/
vendor/rector/rector/
├── LICENSE
├── README.md
├── UPGRADE.md
├── bin
├── bootstrap.php
├── composer.json
├── config
├── docs
├── e2e       <-- to remove this
├── packages
├── preload.php
├── rules
├── src
├── templates
├── upgrade
└── vendor
10 directories, 6 files
```
> [GitAttributes] Add e2e directory to .gitattributes

- rules-tests/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector/Fixture/return_is.php.inc
- rules-tests/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector/Fixture/return_or.php.inc
- rules-tests/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector/Fixture/some_class.php.inc
- rules/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector.php
- rules/DowngradePhp72/snippet/isatty_closure.php.inc
Closes https://github.com/rectorphp/rector/issues/6416
I had originally believed that `symfony/console` might have a solution that'd work better as it inverts the order of operations. Further investigation showed that Rector already sourced the implementation from Symfony's Polyfills. Running under the assumption that the [implementation in `symfony/polyfill-php72`](https://github.com/symfony/polyfill-php72/blob/main/Php72.php#L134-L149) is highly used & tested, `rules/DowngradePhp72/snippet/isatty_closure.php.inc` has been updated to use the latest implementation. 
In practice, this adds a `function_exists` call verifying that `posix_isatty` is available which is not always the case.
Additionally, given it appears the intent is to downgrade to support lower minimum requirements, this …
> Improve DowngradeStreamIsattyRector when stream_isatty is available

- .github/workflows/build_scoped_rector.yaml
- .github/workflows/build_scoped_rector_php70.yaml
- CONTRIBUTING.md
- README.md
Based on https://github.com/rectorphp/rector/issues/6431#issuecomment-843267700 . The current `CONTRIBUTING.md` seems was left over https://github.com/rectorphp/rector/blob/main/CONTRIBUTING.md
> [Doc] Add CONTRIBUTING.md to point target development repo rector-src

- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- phpstan.neon
- rules-tests/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector/DoctrineAnnotationClassToAttributeRectorTest.php
- rules-tests/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector/Fixture/none_target.php.inc
- rules-tests/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector/Fixture/required_value.php.inc
- rules-tests/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector/Fixture/some_class.php.inc
- rules-tests/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector/Fixture/target_method_property_class.php.inc
- rules-tests/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector/config/configured_rule.php
- rules/Arguments/Rector/MethodCall/ValueObjectWrapArgRector.php
- rules/Composer/Rector/AddPackageToRequireComposerRector.php
- rules/Composer/Rector/AddPackageToRequireDevComposerRector.php
- rules/Composer/Rector/ChangePackageVersionComposerRector.php
- rules/Composer/Rector/RenamePackageComposerRector.php
- rules/Composer/Rector/ReplacePackageAndVersionComposerRector.php
- rules/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector.php
- rules/Removing/NodeManipulator/ComplexNodeRemover.php
- rules/Restoration/Rector/Namespace_/CompleteImportForPartialAnnotationRector.php
- rules/Transform/Rector/MethodCall/ReplaceParentCallByPropertyCallRector.php
```diff
+use Attribute;
-use Doctrine\Common\Annotations\Annotation\Required;
-use Doctrine\Common\Annotations\Annotation\Target;
-/**
- * @Annotation
- * @Target({"METHOD"})
- */
+#[Attribute(Attribute::TARGET_METHOD)]
class SomeAnnotation
```
- all or configurable
Closes https://github.com/rectorphp/rector/issues/6429
> [PHP 8.0] Add DoctrineAnnotationClassToAttributeRector

- config/set/downgrade-php80.php
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/DowngradeStrContainsRectorTest.php
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/Fixture/not_str_contains.php.inc
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/Fixture/not_str_contains_with_mixed.php.inc
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/Fixture/not_str_contains_with_variables.php.inc
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/Fixture/str_contains.php.inc
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/Fixture/str_contains.php_with_mixed.php.inc
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/Fixture/str_contains.php_with_variables.php.inc
- rules-tests/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector.php
Adds a rector for downgrading calls to PHP 8.0's `str_contains()` to `strpos() !== false` (ditto for `! str_contains()`).
`strpos()` used over `strstr()` because, as the returned substring is of no interest, `strpos()` is a less memory-intensive way of getting the same result as `strstr()`.
Partially closes https://github.com/rectorphp/rector/issues/6315
> [PHP 8.0] Downgrade `str_contains()`

- build/target-repository/docs/rector_rules_overview.md
- composer.json
Currently, the `rector_rules_overview.md` pointed by `../../../` as directly passed to `build/target-repository/docs/` which 3 directory dept. While in `rector/rector` repository, it just has parent `docs` ( 1 dept directory). This make the link in generated in https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md not linked on each class rule. 
To fix it, I applied composer script ( composer docs ) command to apply docs content to temporary to `build` directory, which is 1 dept directory, and then next moved the generated to `build/target-repository/docs/` as the correct content.
Closes https://github.com/rectorphp/rector-src/pull/91
> [Docs] Fixes rector_rules_overview.md docs link in each rules

- config/set/downgrade-php80.php
- packages/PhpAttribute/Printer/DoctrineAnnotationFactory.php
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/DowngradeAttributeToAnnotationRectorTest.php
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/symfony_required.php.inc
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
- rules/DowngradePhp80/ValueObject/DowngradeAttributeToAnnotation.php
Ref https://github.com/rectorphp/rector/issues/4156
Needed for Rector downgrade of `#[Required]` attribute from Symfony
> [Downgrade PHP 8.0] Add DowngradeAttributeToAnnotationRector

- rules-tests/DowngradePhp70/Rector/FunctionLike/DowngradeScalarTypeDeclarationRector/Fixture/closure.php.inc
- rules/DowngradePhp70/Rector/FunctionLike/DowngradeScalarTypeDeclarationRector.php
Fixes https://github.com/rectorphp/rector/issues/6451
> [DowngradePhp70] Handle DowngradeScalarTypeDeclarationRector on Closure

- tests/PhpParser/Printer/FormatPerservingPrinterTest.php
file-mod is not a concept on windows, therefore is this test not usefull / will always fail
> Skip FormatPerservingPrinterTest on windows

- packages-tests/BetterPhpDocParser/PhpDocInlineHtml/config/configured_rule.php
- rules-tests/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Fixture/skip_next_inline_html.php.inc
- rules/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php
Fixes https://github.com/rectorphp/rector/issues/6455
> [CodeQualityStrict] Skip MoveVariableDeclarationNearReferenceRector when next is inline HTML

- .gitattributes
this change fixes the following test-errors on windows:
```
4) Rector\Tests\FileFormatter\Formatter\JsonFileFormatter\JsonFileFormatterTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
#Warning: Strings contain different line endings!
-'{
-	"name": "foo/bar",
-	"description": "A foo bar baz extension",
-	"license": "GPL-2.0-or-later"
-}
+'{
+	"name": "foo/bar",
+	"description": "A foo bar baz extension",
+	"license": "GPL-2.0-or-later"
+}
'
5) Rector\Tests\FileFormatter\Formatter\XmlFileFormatter\XmlFileFormatterTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
#Warning: …
```
> make sure windows uses LF, for files, which we expect to always use LF, no matter the platform

- rules/PSR4/FileRelocationResolver.php
```
1) Rector\Tests\PSR4\FileRelocationResolverTest::test with data set #0 ('C:\xampp7.3\htdocs\rector-src...le.php', 'Rector\Tests\PSR4\Source\SomeFile', 'Rector\Tests\PSR10\Source\SomeFile', 'rules-tests/PSR10/Source/SomeFile.php')
Nette\Utils\RegexpException: No ending delimiter '#' found in pattern: #\#
C:\xampp7.3\htdocs\rector-src\vendor\nette\utils\src\Utils\Strings.php:539
C:\xampp7.3\htdocs\rector-src\vendor\nette\utils\src\Utils\Callback.php:76
C:\xampp7.3\htdocs\rector-src\vendor\nette\utils\src\Utils\Callback.php:84
C:\xampp7.3\htdocs\rector-src\vendor\nette\utils\src\Utils\Strings.php:540
C:\xampp7.3\htdocs\rector-src\vendor\nette\utils\src\Utils\Strings.php:475
C:\xampp7.3\htdocs\rector-src\rules\PSR4\FileRelocationResolver.php:165 …
```
> FileRelocationResolverTest: fix RegexpException on windows

- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/donot_reorder_annotation.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/multiple_same_attribute.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/FixtureAutoImported/donot_reorder_annotation.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/FixtureAutoImported/donot_sort_annotation.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
- rules/Php80/Rector/Class_/AnnotationToAttributeRector.php
Annotation attribute should keep order original annotation comment. This is failing fixture that: 
```
* @ORM\Column(name="id", type="bigint", nullable=false)     
* @ORM\Id  
*  @ORM\GeneratedValue(strategy="IDENTITY")
```
should have the same order:
```
#[Column(name: 'id', type: 'bigint', nullable: false)]    
#[Id]   
#[GeneratedValue(strategy: 'IDENTITY')]
```
> [Php80] Annotation attribute should keep order original annotation comment

- packages/ChangesReporting/Annotation/AnnotationExtractor.php
- packages/ChangesReporting/Annotation/RectorsChangelogResolver.php
fixes failing windows test
```
1) Rector\Tests\ChangesReporting\Annotation\AnnotationExtractorTest::testExtractAnnotationFromClass with data set "Class with changelog annotation" ('Rector\Tests\ChangesReporting...ngelog', '@changelog', 'rectorphp/...iew.md')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'rectorphp/rector@master/docs/rector_rules_overview.md'
+'rectorphp/rector@master/docs/rector_rules_overview.md
'
2) Rector\Tests\ChangesReporting\Annotation\AppliedRectorsChangelogResolver\RectorsChangelogResolverTest::test
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
Array &0 (
-    'Rector\Tests\ChangesReporting\Annotation\AppliedRectorsChangelogResolver\Source\RectorWithChangelog' => …
```
> AnnotationExtractor: fix tests on windows

- config/set/downgrade-php73.php
- packages/PHPStanStaticTypeMapper/PHPStanStaticTypeMapper.php
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeIsCountableRector/DowngradeIsCountableRectorTest.php
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeIsCountableRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeIsCountableRector/config/configured_rule.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeIsCountableRector.php
We're missing this rule for Rector code.
Discovered in https://github.com/rectorphp/rector-src/pull/113/files
> [Downgrade PHP 7.3] Add DowngradeIsCountableRector

- rules-tests/Php74/Rector/LNumber/AddLiteralSeparatorToNumberRector/Fixture/skip_already_formatted.php.inc
- rules/Php74/Rector/LNumber/AddLiteralSeparatorToNumberRector.php
- src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php
Fixes https://github.com/rectorphp/rector/issues/6188
> [Php74] Skip AddLiteralSeparatorToNumberRector on already formatted literals

- rules/CodingStyle/Rector/Assign/ManualJsonStringToJsonEncodeArrayRector.php
- rules/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector.php
- rules/EarlyReturn/Rector/If_/ChangeOrIfContinueToMultiContinueRector.php
- rules/Naming/Rector/ClassMethod/RenameParamToMatchTypeRector.php
- rules/Php52/Rector/Property/VarToPublicPropertyRector.php
- rules/Php70/Rector/FunctionLike/ExceptionHandlerTypehintRector.php
- rules/Php80/Rector/FuncCall/TokenGetAllToObjectRector.php
- rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromReturnNewRector.php
Some rule docs were mindlessly copied from other rules, and don't make any sense.
- `ReturnTypeFromReturnNewRector` copied from `AddVoidReturnTypeWhereNoReturnRector`
- `SensitiveDefineRector` copied from `SensitiveConstantNameRector`
- `DowngradeFlexibleHeredocSyntaxRector` copied from `SensitiveHereNowDocRector`
- `ChangeOrIfContinueToMultiContinueRector` copied from `ChangeAndIfToEarlyReturnRector`
- `ExceptionHandlerTypehintRector` copied from `TypedPropertyRector`
- `TokenGetAllToObjectRector` copied from `CompleteMissingDependencyInNewRector`
- `VarToPublicPropertyRector` copied from `RemoveUnusedPrivateMethodRector`
- `RenameParamToMatchTypeRector` copied from `RenameVariableToMatchNewTypeRector`
> Fix copy-paste errors in rule docs

- rules/DowngradePhp72/NodeAnalyzer/ClassLikeWithTraitsClassMethodResolver.php
- rules/DowngradePhp72/NodeAnalyzer/ParamContravariantDetector.php
- rules/DowngradePhp72/NodeAnalyzer/ParentChildClassMethodTypeResolver.php
- rules/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector.php
- Early skip when `$scope->getClassReflection()` is not ClassReflection instead of check in each loop.
- Remove unneded pass Scope on already ClassReflection used in ParentChildClassMethodTypeResolver
- change `count($uniqueTypes) <= 1` to `! isset($uniqueTypes[1])` as array_values always start from 0
- use ClassReflection type hint for ParamContravariantDetector methods
- get ancestors and class method name early before loop
- early get classes and interfaces by type before loop
- remove unused dependencies
- get all interfaces early before loop
Fixes https://github.com/rectorphp/rector/issues/6435
> [DowngradePhp72] Improve DowngradeParameterTypeWideningRector performance

- packages/FileFormatter/Formatter/XmlFileFormatter.php
Should fix a failling test on windows (not yet verified)
```
4) Rector\Tests\FileFormatter\Formatter\XmlFileFormatter\XmlFileFormatterTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
52
Failed asserting that two strings are identical.
53
--- Expected
54
+++ Actual
55
@@ @@
56
#Warning: Strings contain different line endings!
57
-'<?xml version="1.0"?>
58
-<catalog>
59
-	<book id="bk101">
60
-		<author>Gambardella, Matthew</author>
61
-		<title>XML Developer's Guide</title>
62
-		<genre>Computer</genre>
63
-		<price>44.95</price>
64
-		<publish_date>2000-10-01</publish_date>
65
-		<description>An in-depth look at creating applications
66
-		with XML.</description>
67
-	</book>
68
+'<?xml version="1.0"?>
69
+<catalog>
70
+	<book id="bk101">
71
+ …
```
> XmlFileFormatter: utilize EditorConfigConfiguration for newline generation

- packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80/do_not_duplicate_array_return.php.inc
`array` piped should be only defined once, it currently got twice:
```bash
-    public function go($number): bool|array|float
+    public function go($number): bool|array|float|array
```
> [TypeDeclaration] Do not duplicate piped array return on ReturnTypeDeclarationRector

- rector.php
- rules-tests/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector/Fixture/skip_nullable_string_from_external_trait.php.inc
- rules-tests/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector/Source/NullableStringTrait.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_from_external_void.php.inc
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_from_external_void_interface.php.inc
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_from_external_void_trait.php.inc
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Source/ExternalForVoid.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Source/ExternalForVoidInterface.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Source/ExternalForVoidTrait.php
- rules/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector.php
- rules/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- rules/TypeDeclaration/TypeInferer/SilentVoidResolver.php
- src/NodeAnalyzer/ExternalFullyQualifiedAnalyzer.php
Re-open of https://github.com/rectorphp/rector-src/pull/152 . 
The `src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php` need to be skipped for `AddVoidReturnTypeWhereNoReturnRector` as always loaded early.
> [Core] Add ExternalFullyQualifiedAnalyzer to check external FullyQualified extends/interface/traits

- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php
- rules-tests/Naming/Rector/Class_/RenamePropertyToMatchTypeRector/FixturePhp80/rename_param_doc.php.inc
- rules/Naming/Rector/Class_/RenamePropertyToMatchTypeRector.php
The variable in `@param` should follow the changed to new variable name.
> [Naming] @param doc should follow variable renamed on RenamePropertyToMatchTypeRector

- packages-tests/PhpAttribute/Printer/PhpAttributeGroupFactoryTest.php
- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
I need this new method to be able to explode one annotation into multiple attributes.
> Add new method createFromClassWithItems in PhpAttributeGroupFactory

- rules-tests/DowngradePhp80/Rector/ClassConstFetch/DowngradeClassOnObjectToGetClassRector/Fixture/func_call.php.inc
- rules/DowngradePhp80/Rector/ClassConstFetch/DowngradeClassOnObjectToGetClassRector.php
Apply changes when `$node->name` named 'class' for `ClassConstFetch` for `Expr`
> [DowngradePhp80] Allow Expr type for DowngradeClassOnObjectToGetClassRector

- phpstan.neon
- tests/Issues/Issue6481/EncapsedStringsInsideDeadInstanceTest.php
- tests/Issues/Issue6481/Fixture/fixture.php.inc
- tests/Issues/Issue6481/config/configured_rule.php
Closes rectorphp/rector#6481
Fixed by #201 @samsonasik 
See nikic/PHP-Parser#780
> Test: `EncapsedStringsToSprintfRector` + `RemoveDeadInstanceOfRector`

- rules-tests/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture/multiple.php.inc
- rules-tests/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture/skip_interface_method.php.inc
- rules/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector.php
fixes https://github.com/rectorphp/rector/issues/6501
I just changed the way to add newlines, because adding newlines directly to `$node->stmts` inside foreach loop was breaking the loop (and logic).
> [CodingStyle] Fix newline before new assign set

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/imported_attributes.php.inc
Based on https://getrector.org/demo/4c7348a5-8a07-4f85-aa4d-e462f672dae8
> Add failing test fixture for AnnotationToAttributeRector

- phpstan.neon
- src/DependencyInjection/CompilerPass/VerifyRectorServiceExistsCompilerPass.php
before this change, rector always reports `Rector rule "%s" not found, please verify that the rule exists.` no matter whether the rector rule was not found at all, or it a class was found but did not implement the proper interface
> DX: Report more precise errors in `VerifyRectorServiceExistsCompilerPass`

- packages/NodeCollector/NodeCollector/NodeRepository.php
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_this_case_insensitive_method_name.php.inc
Fixes https://github.com/rectorphp/rector/issues/6507
> Incorrect behavior of RemoveUnusedPrivateMethodRector

- src/Util/StaticRectorStrings.php
instead of run strtolower inside foreach, make variable and early assign for strtolower.
> [Util] Early strtolower() on StaticRectorStrings::isInArrayInsensitive()

- packages/NodeCollector/NodeCollector/NodeRepository.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/annotation_converted_an_keep_docblock.php.inc
- rules/Php80/NodeResolver/SwitchExprsResolver.php
- src/DependencyInjection/CompilerPass/VerifyRectorServiceExistsCompilerPass.php
- add test for annotation and attribue
- fixup! add test for annotation and attribue
> [PHP 8.0 ] No space annotatation and attributes

- rules-tests/Naming/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/keep_underscore.php.inc
- rules/Naming/ExpectedNameResolver/InflectorSingularResolver.php
Fixes https://github.com/rectorphp/rector/issues/6479
> [Naming] Keep underscore in RenameForeachValueVariableToMatchExprVariableRector

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_in_compact.php.inc
- rules/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector.php
Thanks for the great tool!
I've run into an issue where `RemoveUnusedAssignVariableRector` removes variables used in `compact()`.
E.g.
```diff
{
-   $value = 'foobar';
return compact('value');
}
```
I noticed this has been recently fixed in `RemoveUnusedVariableAssignRector` (https://github.com/rectorphp/rector/pull/6103) so I've tried to apply a similar approach here.
I'm not confident that I know what I'm doing in this code base so I would appreciate a thorough review and welcome any feedback.
Thanks again!
> [DeadCode] Prevent RemoveUnusedAssignVariableRector removing variables used in compact()

- rules-tests/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector/Fixture/treat_variadic_parameter_as_optional.php.inc
- rules/Php80/NodeResolver/RequireOptionalParamResolver.php
see https://github.com/rectorphp/rector-src/pull/233
fixes https://github.com/rectorphp/rector/issues/6506
> [Php80] Fix OptionalParametersAfterRequiredRector to treat variadic as optional

- build/target-repository/composer.json
It currently still uses `>=0.12.86 <=0.12.88` which should be updated as well.
> Apply missing update phpstan req at target-repository

- build/target-repository/.github/workflows/publish_docker_images.yaml
fixes https://github.com/rectorphp/rector/issues/6457
Requires DockerHub password to run, and I believe this is the only way to update overview constantly with a path other than README.md.
> add DockerHub overview update workflow

- src/Application/FileSystem/RemovedAndAddedFilesCollector.php
instead of re-call `$smartFileInfo->getPathname()` in a loop.
> [Core] Early assign $smartFileInfo->getPathname() to variable for RemovedAndAddedFilesCollector::isFileRemoved()

- src/NonPhpFile/NonPhpFileProcessor.php
> [Core] Early $smartFileInfo->getPathname() on NonPhpFileProcessor::supports()

- packages/ChangesReporting/Output/ConsoleOutputFormatter.php
- packages/ChangesReporting/Output/JsonOutputFormatter.php
- src/Configuration/Configuration.php
- src/Configuration/Option.php
- src/Console/Command/ProcessCommand.php
I'm refactoring `Configuration` to value object as prequel to parallel run and came across this unused option.
The demo uses direct output since version 0.11, so this option is not needed anymore
See https://github.com/rectorphp/getrector.org/blob/20859c8d114c76fa947cfad4e0da2e30abbb7b2e/packages/Demo/DemoRunner.php#L46
> Remove unused --output-file option, now direct on demo page

- phpstan.neon
- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/on_ob_get_clean.php.inc
- rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php
- rules/DeadCode/SideEffect/PureFunctionDetector.php
Remove variable of assign, but keep assign expr when assign expr is an impure function.
> [DeadCode] Keep Assign expr on RemoveUnusedVariableAssignRector for impure function

- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php
- rules-tests/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector/Fixture/skip_phpstan_var_annotated.php.inc
- rules/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector.php
`PropertyTypeDeclarationRector` should not add another `@var` annotation when a `@phpstan-var` is already declared
Based on https://getrector.org/demo/1ebd59d8-8604-6094-9c71-1f6d7ff1a1c6
> PropertyTypeDeclarationRector: support `phpstan` and `psalm` prefixed `@var`

- .github/workflows/packages_tests.yaml
- rector.php
- rules-tests/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector/Source/vendor/SomeOutsideClass.php
- rules/DeadCode/Rector/ClassMethod/RemoveDelegatingParentCallRector.php
- rules/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector.php
- src/PhpParser/AstResolver.php
- src/Reflection/ReflectionResolver.php
@samsonasik @sabbelasichon FYI, The reflection migration is finished now :+1: 
2 important changes:
* to get method reflection from a method call, static call, class name + method name etc., use `Rector\Core\Reflection\ReflectionResolver`
* see https://github.com/rectorphp/rector-src/blob/main/src/Reflection/ReflectionResolver.php
* to get `ClassMethod`, `Class_` node (AST) from a class name + method name, use `Rector\Core\PhpParser\AstResolver` - its for read-only analysis of specific nodes
* see https://github.com/rectorphp/rector-src/blob/main/src/PhpParser/AstResolver.php
> Final reflection update touches

- packages/PHPStanStaticTypeMapper/Contract/TypeMapperInterface.php
- packages/PHPStanStaticTypeMapper/PHPStanStaticTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ArrayTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/BooleanTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/CallableTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ClassStringTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ClosureTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/FloatTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/HasOffsetTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/IntegerTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/IntersectionTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/IterableTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/MixedTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/NeverTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/NonEmptyArrayTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/NullTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ObjectTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ObjectWithoutClassTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ParentStaticTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ResourceTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/SelfObjectTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/StaticTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/StrictMixedTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/StringTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/ThisTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/TypeWithClassNameTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php
- packages/PHPStanStaticTypeMapper/TypeMapper/VoidTypeMapper.php
- packages/StaticTypeMapper/StaticTypeMapper.php
which allows to differentiate the returned type based on the used location.
this is required to add a proper `@return never` handling as we are building it in https://github.com/rectorphp/rector-src/pull/296
> added `$kind` param to `TypeMapperInterface->mapToPHPStanPhpDocTypeNode()`

- .github/workflows/weekly_pull_requests.yaml
To make auto-merge like in getrector.org repo. It needs to use `secrets.ACCESS_TOKEN` in create pull request to make CI run and `id` to make auto-merge merge the pr from create pull request steps.
> Enable auto-merge on weekly pull request

- rules-tests/CodingStyle/Rector/FuncCall/VersionCompareFuncCallToConstantRector/Fixture/skip_indirect_string_number.php.inc
- rules/CodingStyle/Rector/FuncCall/VersionCompareFuncCallToConstantRector.php
This for compare with eg: class contant.
> [CodingStyle] Skip indirect version number on VersionCompareFuncCallToConstantRector

- rules-tests/CodingStyle/Rector/ClassMethod/UnSpreadOperatorRector/Fixture/handle_multiple_items_to_array.php.inc
- rules-tests/CodingStyle/Rector/ClassMethod/UnSpreadOperatorRector/Fixture/not_pass_arg.php.inc
- rules-tests/CodingStyle/Rector/ClassMethod/UnSpreadOperatorRector/Fixture/typed_param_variadic.php.inc
- rules/CodingStyle/Rector/ClassMethod/UnSpreadOperatorRector.php
On variadic, no argument means empty array, which is optional, while on `array` type hint without default value, it need to be passed. I think default empty array is needed to keep the method call working as previously used, if used by external source.
ref https://3v4l.org/S3sBS
> [CodingStyle] Default empty array [] on UnSpreadOperatorRector

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/skip_unwrap_symfony_nested_validators.php.inc
- rules/Php80/Rector/Class_/AnnotationToAttributeRector.php
After release 0.11.32  AnnotationToAttributeRector tries to unwrap nested annotations, but it has no sense for some symfony validators. This pr provides test and possible solution. @TomasVotruba @samsonasik what do you think?
> [AnnotationToAttributeRector] Skip unwrap symfony nested validators

- rules-tests/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_iterable_pseudotype_array.php.inc
- rules-tests/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_iterable_pseudotype_function_item.php.inc
- rules/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector.php
Closes #371 Fixes https://github.com/rectorphp/rector/issues/6544 
The solution I found for now is mark typed "iterable" as non Iterable type, as it can be array as well.
> [DowngradePhp74] Handle iterable on DowngradeArraySpreadRector

- composer.json
symfony/console classes have sometimes different param types than its parent interface
This causes fatal errors on donwgrade rule, because after moving from dynamic parsing to static reflection, Rector is trying to narrow node modification to current node only.
See failing CI on `rector/rector` (https://github.com/rectorphp/rector/runs/2985182881):
<br>
Coincidentaly, this was fixed in Symfony 5.4 just 2 days ago https://github.com/symfony/symfony/pull/41946
https://github.com/symfony/console/commit/d4c4ac30d2dc666fc72fc3c57fdc9df113e6b184#diff-565a2bb8afda62ae570ddc3b8b24efd584aaafc6c7b65e0071c5deddfd03a766, now backported to 5.3. Just in `dev-master` for time being.
This PR gives a new Symfony try
> use symfony/console with fixed covariant types

- rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/static_call.php.inc
- rules/Php72/NodeFactory/AnonymousFunctionFactory.php
Closes #381 Fixes https://github.com/rectorphp/rector/issues/6551
> [CodeQuality] Handle CallableThisArrayToAnonymousFunctionRector on static call

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
- rules-tests/CodeQuality/Rector/Array_/ArrayThisCallToThisMethodCallRector/Fixture/skip_non_callable.php.inc
- rules-tests/CodeQuality/Rector/Array_/ArrayThisCallToThisMethodCallRector/Source/SomeConstantInteger.php
Closes https://github.com/rectorphp/rector/issues/6540
> Fix ArrayCallableMethodMatcher to accept only strings

- rules/DeadCode/NodeCollector/NodeByTypeAndPositionCollector.php
- tests/Issues/Issue6557/Fixture/fixture.php.inc
- tests/Issues/Issue6557/NullStartTokenTest.php
- tests/Issues/Issue6557/RemoveOverriddenValuesRectorTest.php
- tests/Issues/Issue6557/config/configured_rule.php
Closes #396 Fixes https://github.com/rectorphp/rector/issues/6557
> [DeadCode][Naming] Handle null start token on use RemoveOverriddenValuesRector & RenameVariableToMatchNewTypeRector

- config/set/downgrade-php80.php
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/get_nullable.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/get_nullable_in_trait.php.inc
- rules/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector.php
- rules/Naming/Naming/VariableNaming.php
- add test case for missed downgrade nullsafe
- fix for trait
> [Downgrade PHP 8.0] Fix DowngradeNullsafeToTernaryOperatorRector for trait

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/promoted_property.php.inc
- rules/Php80/Rector/Class_/AnnotationToAttributeRector.php
https://github.com/rectorphp/rector/issues/6566
> added promoted property test for annotation to attribute rule

- rules/DeadCode/UselessIfCondBeforeForeachDetector.php
Previously, the : 
```php
$this->nodeTypeResolver->resolve($param->var)
```
will returns `MixedType` on the following code:
```php
function run(?array $values) {
```
so the code is always negated, which is always not a NullableType, even invalid check as `NodeTypeResolver` must be checked against `PHPStan` type, while we compare against Node's NullableType.
There is no need to update the tests as it previously always negated.
> [DeadCode] Fix non-null type check on RemoveUnusedNonEmptyArrayBeforeForeachRector

- rules/DeadCode/NodeAnalyzer/ExprUsedInNodeAnalyzer.php
Fix PHPStan notice:
```bash
rules/DeadCode/NodeAnalyzer/ExprUsedInNodeAnalyzer.php:32
- '#Parameter \#2 \$variable of method Rector\\Core\\NodeAnalyzer\\CompactFuncCallAnalyzer\:\:isInCompact\(\) expects PhpParser\\Node\\Expr\\Variable, PhpParser\\Node\\Expr given#'
```
> Fix PHPStan notice

- rules-tests/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/FileWithoutNamespaceTest.php
It previously got error:
```bash
1) Rector\Tests\PSR4\Rector\Namespace_\MultipleClassFileToPsr4ClassesRector\FileWithoutNamespaceTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...), array(Rector\FileSystemRector\ValueObject\AddedFileWithContent Object (...), Rector\FileSystemRector\ValueObject\AddedFileWithContent Object (...)))
ArgumentCountError: Too few arguments to function Rector\Tests\PSR4\Rector\Namespace_\MultipleClassFileToPsr4ClassesRector\FileWithoutNamespaceTest::test(), 2 passed in /Users/samsonasik/www/rector-src/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1527 and exactly 3 expected
/Users/samsonasik/www/rector-src/rules-tests/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/FileWithoutNamespaceTest.php …
```
> [PSR4] Fix PHPUnit run test error on FileWithoutNamespaceTest

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_in_compact.php.inc
- rules-tests/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_in_compact_array.php.inc
- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_compact_array.php.inc
- src/NodeAnalyzer/CompactFuncCallAnalyzer.php
Continuing from #238, I have found that both `RemoveUnusedAssignVariableRector` and `RemoveUnusedVariableAssignRector` mistakenly remove variables that are referenced in `compact()` when using PHP's alternative array syntax.
In other words, currently Rector only supports `compact(string $var_name, string ...$var_names)` where as [PHP supports](https://www.php.net/manual/en/function.compact.php) `compact(array|string $var_name, array|string ...$var_names)` and will also recursively handle arrays within arrays. 
This PR addresses this issue and also fixes an incorrect test namespace from my previous PR.
> Support compact() array syntax

- .github/workflows/build_scoped_rector.yaml
- .github/workflows/build_scoped_rector_php70.yaml
- .github/workflows/code_analysis.yaml
- .github/workflows/code_analysis_no_dev.yaml
- .github/workflows/packages_tests.yaml
- .github/workflows/php_linter.yaml
- .github/workflows/rector.yaml
- .github/workflows/tests.yaml
- .github/workflows/weekly_pull_requests.yaml
the default of 6h is way to long and produced a overlong queue in case of endless loop bugs.
as discussed in https://github.com/rectorphp/rector/issues/6574#issuecomment-881273800
closes https://github.com/rectorphp/rector/issues/6574
> github-actions: declare timeout for job execution

- rules-tests/Php71/Rector/Assign/AssignArrayToStringRector/Fixture/empty_string_array_dim_fetch_value.php.inc
- rules-tests/Php71/Rector/Assign/AssignArrayToStringRector/Fixture/skip_empty_string_array_dim_fetch_value.php.inc
- src/PhpParser/Node/BetterNodeFinder.php
It currently got error:
```bash
1) Rector\Tests\Php71\Rector\Assign\AssignArrayToStringRector\AssignArrayToStringRectorTest::test with data set #9 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\NotImplementedYetException: 
/Users/samsonasik/www/rector-src/src/PhpParser/Node/BetterNodeFinder.php:385
/Users/samsonasik/www/rector-src/rules/Php71/Rector/Assign/AssignArrayToStringRector.php:81
```
It Fixes rectorphp/rector#6573
> [Php71] Skip AssignArrayToStringRector on empty string array dim fetch value

- rules/Arguments/Rector/FuncCall/SwapFuncCallArgumentsRector.php
- rules/CodeQuality/Rector/Foreach_/UnusedForeachValueToArrayKeysRector.php
- rules/CodingStyle/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector.php
- rules/DeadCode/NodeAnalyzer/ExprUsedInNextNodeAnalyzer.php
- rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php
- rules/DeadCode/Rector/ClassMethod/RemoveLastReturnRector.php
- rules/Naming/Matcher/ForeachMatcher.php
- rules/Naming/Matcher/VariableAndCallAssignMatcher.php
- rules/Php70/EregToPcreTransformer.php
- rules/Php71/Rector/Assign/AssignArrayToStringRector.php
- rules/Php80/Rector/Catch_/RemoveUnusedVariableInCatchRector.php
- rules/TypeDeclaration/NodeAnalyzer/ReturnStrictTypeAnalyzer.php
- rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector.php
- rules/TypeDeclaration/TypeInferer/ParamTypeInferer/FunctionLikeDocParamTypeInferer.php
- src/NodeAnalyzer/CompactFuncCallAnalyzer.php
@TomasVotruba I don't know why, but it fix https://github.com/rectorphp/rector/issues/6573 . 
The error "RectorError::$fileInfo must not be accessed before initialization" no longer appear after run twice.
> [Rectify] Manual twice run rector against rules directory

- packages/ChangesReporting/ValueObjectFactory/ErrorFactory.php
- src/Application/FileProcessor/PhpFileProcessor.php
- src/ValueObject/Application/RectorError.php
To avoid error : "Typed property Rector\Core\ValueObject\Application\RectorError::$fileInfo must not be accessed before initialization" like in https://github.com/rectorphp/rector/issues/6573
> [Core] Refactor RectorError ValueObject with inject with SmartFileInfo

- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_return_static.php.inc
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80/static_.php.inc
- rules/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- rules/TypeDeclaration/TypeInferer/ReturnTypeInferer.php
Fixes https://github.com/rectorphp/rector/issues/6541
- skip return static on use feature before static type ( php <= 7.4 )
- allow return static on php 8+
> [TypeDeclaration] Fixes Return Type static in ReturnTypeDeclarationRector

- packages/NodeCollector/StaticAnalyzer.php
- rules-tests/Php70/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/skip_string_not_method_name_in_annotation.php.inc
- rules-tests/Php70/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/static_method_in_annotation.php.inc
Based on https://getrector.org/demo/1ebe6192-f226-655c-8137-c979d4975a08
Fixes: rectorphp/rector#6578
`skip_string_not_method_name_in_annotation.php.inc` is the failing test fixture and `static_method_in_annotation.php.inc` is added to ensure that the previous code can run correctly.
> Fix match static method name in annotation

- rules/TypeDeclaration/TypeAnalyzer/GenericClassStringTypeNormalizer.php
- rules/TypeDeclaration/TypeInferer/ReturnTypeInferer.php
- tests/Issues/IssueImportedReturn/Fixture/fixture.php.inc
- tests/Issues/IssueImportedReturn/Fixture/namespaced.php.inc
- tests/Issues/IssueImportedReturn/Fixture/namespaced_union.php.inc
- tests/Issues/IssueImportedReturn/Fixture/union_type.php.inc
- tests/Issues/IssueImportedReturn/ImportedReturnTest.php
- tests/Issues/IssueImportedReturn/Source/Logging.php
- tests/Issues/IssueImportedReturn/Source/Logging2.php
- tests/Issues/IssueImportedReturn/config/configured_rule.php
With used of `RepeatedLiteralToClassConstantRector` and `ReturnTypeDeclarationRector`, it cause an invalid return type for the following use case:
```php
use A\B\C;
class X
{
public function run(): C
{
}
}
```
Make : 
```diff
-     public function run(): C
+     public function run(): \C
```
which invalid.
> [Privatization][TypeDeclaration] Invalid return type on use RepeatedLiteralToClassConstantRector + ReturnTypeDeclarationRector

- rules/CodeQuality/Rector/If_/ExplicitBoolCompareRector.php
- tests/Issues/Issue6561/CountArrayOnTruthyEmptyArrayCompareTest.php
- tests/Issues/Issue6561/Fixture/fixture.php.inc
- tests/Issues/Issue6561/config/configured_rule.php
Fixes https://github.com/rectorphp/rector/issues/6561
> [CodeQuality] Handle both ExplicitBoolCompareRector + CountArrayToEmptyArrayComparisonRector usage

- src/PhpParser/Printer/BetterStandardPrinter.php
The regex error can happen on very large Doctrine migration insert:
```bash
public function up(Schema $schema): void
{
$this->addSql("# ************************************************************
INSERT INTO `tableName` (`id`, `name`)
VALUES
(1, 'test 1'),
// ....
");
}    	
```
> [Core] Avoid "Backtrack limit was exhausted" error on BetterStandardPrinter

- src/Stubs/PHPStanStubLoader.php
@TomasVotruba the error : 
```
Class 'ReflectionUnionType' not found
```
is introduced by https://github.com/rectorphp/rector-src/pull/475/files#diff-e554b0d428c1e970b85f6dedf089d2a50f66c1c28b81fbc094cdec4aa9e53ad9R47-R48 which it is looking at `phpstan-extracted` which not exists yet as it currently still looking at `phpstan` phar.
ref https://github.com/codeigniter4/CodeIgniter4/runs/3125228717#step:10:180 for example error.
> [Stubs] Fix Regression Scoped autoload introduced in 0.11.38

- phpstan.neon
- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
- rules/TypeDeclaration/AlreadyAssignDetector/ConstructorAssignDetector.php
- rules/TypeDeclaration/TypeInferer/PropertyTypeInferer/AllAssignNodePropertyTypeInferer.php
- src/Bootstrap/ExtensionConfigResolver.php
- src/NodeManipulator/ClassDependencyManipulator.php
Handle error like in https://github.com/rectorphp/rector-src/pull/503#issuecomment-886168371
> [TypeDeclaration] Return null when $classLike is null on AllAssignNodePropertyTypeInferer::inferProperty()

- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/AutoImportTest.php
- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/FixtureAutoImport/keep_simple_class.php.inc
- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/config/auto_import.php
- rules/TypeDeclaration/TypeAnalyzer/GenericClassStringTypeNormalizer.php
When auto import enabled, given the following code:
```php
use stdClass;
final class KeepSimpleClass
{
/**
* @var stdClass|null
*/
public $obj;
{
$this->obj = new stdClass();
}
}
```
It currently changed to:
```diff
/**
-     * @var stdClass|null
+     * @var class-string<stdClass>|null
*/
public $obj;
```
which invalid.
> [TypeDeclaration] Keep simple class on auto import for CompleteVarDocTypePropertyRector

- packages/Caching/ValueObject/Storage/FileCacheStorage.php
- phpstan.neon
as can be seen in https://github.com/rectorphp/rector-src/pull/461#issuecomment-885617373 the FileCacheStorage is a major bottleneck while running tests on windows - I guess the same is true on other OSes.
This PR removes unnecessary temp-file handling, because `smartFileSystem->dumpFile` is already a atomic operation which does magic temp-path file handling behind the scenes. therefore we don't need to do the same things on the rector side.
> Sync FileCacheStorage with changes from phpstan-src

- config/parameters.php
- packages-tests/Caching/Detector/config.php
- packages/Caching/Cache.php
- packages/Caching/CacheFactory.php
- packages/Caching/ValueObject/Storage/CacheStorage.php
- packages/Caching/ValueObject/Storage/CacheStorageInterface.php
- packages/Caching/ValueObject/Storage/FileCacheStorage.php
- packages/Caching/ValueObject/Storage/MemoryCacheStorage.php
- phpstan.neon
- src/Configuration/Option.php
after this change running packages-tests/Caching/Detector/ChangedFilesDetectorTest.php locally succeeds in ~1 seconds instead of 3 seconds.
based on an investigation in https://github.com/rectorphp/rector-src/pull/461#issuecomment-885617373
> Added MemoryCacheStorage and use it in `ChangedFilesDetectorTest`

- rules/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php
- rules/DeadCode/SideEffect/PureFunctionDetector.php
- function not found: impure
- function found but non-native: impure
This reduce `MoveVariableDeclarationNearReferenceRector` rector rule logic and possibly used by other rules.
> [DeadCode] Refactor PureFunctionDetector: ensure NativeFunctionReflection for pure function check

- packages/Caching/ValueObject/Storage/MemoryCacheStorage.php
- rules-tests/DeadCode/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_not_name.php.inc
- rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php
Instanceof `class` need to be a `Name` node instance to be able to checked to avoid dynamic check. Ref https://3v4l.org/vGZAt .
Non-`Name` node `class` (eg: Variable) for `InstanceOf_`'s class need to be skipped.
> [DeadCode] Skip InstanceOf class not a Name on RemoveDeadInstanceOfRector

- scoper.php
This change proposes to add the bootstrap files for php:^8.0 into the file list to remove namespaces from. This comes in the sequence of the investigation done triggered by an error on the command `vendor/bin/rector init` when executed in my php 8.0 installation.
> Add Symfony's bootstrap80 files to the list for namespace removal

- rules/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php
- rules/DeadCode/SideEffect/SideEffectNodeDetector.php
- rules/DowngradePhp70/Rector/Coalesce/DowngradeNullCoalesceRector.php
It can reduce code at `MoveVariableDeclarationNearReferenceRector`, and possibly can be used in other rules for check dead code removal.
> [DeadCode][CodeQualityStrict] Add SideEffectNodeDetector::detectCallExpr()

- packages/Testing/PHPUnit/Behavior/MovingFilesTrait.php
- return early when `addedFilesWithNodes` is empty array
- early assign service before loop
> [Testing] Avoid repetitive getService(NodesWithFileDestinationPrinter::class) in loop at MovingFilesTrait

- .github/workflows/rector.yaml
- rector.php
- scoper.php
To make `scoper.php` checked by rector as well. The downgrading is executable in php 8, so I think it is safe.
> [Config] Add scoper.php to rector config path

- rules/Autodiscovery/Analyzer/ValueObjectClassAnalyzer.php
Replace the `NodeRepository-> findClass()` with `AstResolver->resolveClassFromName()`
> [Autodiscovery] Using AstResolver->resolveClassFromName() on ValueObjectClassAnalyzer

- packages/FamilyTree/NodeAnalyzer/PropertyUsageAnalyzer.php
Replace the `NodeRepository-> findClass()` with `AstResolver->resolveClassFromName()`
> [FamilyTree] Using AstResolver->resolveClassFromName() on PropertyUsageAnalyzer

- packages/VersionBonding/Application/MissedRectorDueVersionChecker.php
Previously shows invalid value on PR https://github.com/rectorphp/rector-src/pull/572
**Before**
**After**
> [VersionBonding] Correctly shows missed rectors  that will not run

- rules-tests/Defluent/Rector/Return_/DefluentReturnMethodCallRector/Fixture/skip_interface.php.inc
- rules-tests/Defluent/Rector/Return_/DefluentReturnMethodCallRector/Source/MessageInterface.php
- rules/Defluent/NodeAnalyzer/FluentChainMethodCallNodeAnalyzer.php
When the type is interface, it is depends on the implementation for it is able to be defluent, eg: the implementation apply new self, or clone object first before return.
> [Defluent] Skip interface on DefluentReturnMethodCallRector

- utils/compiler/src/PhpScoper/StaticEasyPrefixer.php
Fixes https://github.com/rectorphp/rector/issues/6607
to avoid error: 
```
[ERROR] Could not process "app/Models/User.php" file, due to:                                                          
"RectorPrefix20210802\Doctrine\Inflector\Inflector::__construct(): Argument #1 ($singularizer) must be of type 
RectorPrefix20210802\Doctrine\Inflector\WordInflector, Doctrine\Inflector\CachedWordInflector given, called in 
vendor/laravel/framework/src/Illuminate/Support/Pluralizer.php:140". On line: 28      
```
> [Scoper] Remove Doctrine\Inflector\Inflector from exclude class

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromReturnNewRector/Fixture/arrow_function_.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Fixture/arrow_function.php.inc
- src/PhpParser/Printer/BetterStandardPrinter.php
- add `Expr_ArrowFunction` insertion map for print return type double colon right after the bracket
> [BetterStandardPrinter] Using Expr_ArrowFunction->returnType with print return type double colon right after the bracket

- rules-tests/DeadCode/Rector/ClassMethod/RemoveDeadConstructorRector/Fixture/skip_extends_with_no_stmt.php.inc
- rules/DeadCode/Rector/ClassMethod/RemoveDeadConstructorRector.php
Empty constuctor that the class has extends another class can be on purpose for stubbing usage, eg: on testing.
> [DeadCode] Skip RemoveDeadConstructorRector on empty constructor with class extends

- rules-tests/DeadCode/Rector/Cast/RecastingRemovalRector/Fixture/skip_non_typed_property.php.inc
- rules-tests/DeadCode/Rector/Cast/RecastingRemovalRector/Fixture/skip_non_typed_property.php2.php.inc
- rules-tests/DeadCode/Rector/Cast/RecastingRemovalRector/Fixture/typed_property.php.inc
- rules/DeadCode/Rector/Cast/RecastingRemovalRector.php
- Allow typed property
- Skip non-typed property
> [DeadCode] Skip non-typed property for RecastingRemovalRector

- rules-tests/DeadCode/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/skip_marked_incomplete_test_file.php.inc
- rules/DeadCode/Rector/Stmt/RemoveUnreachableStatementRector.php
Skip with `markTestIncomplete()` for test usage so the test for can be continued later.
> [DeadCode] Skip RemoveUnreachableStatementRector on use of $this->markTestIncomplete()

- rules-tests/TypeDeclaration/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/skip_indirect_array_value_phpuint_data_provider.php.inc
- rules/TypeDeclaration/TypeInferer/ParamTypeInferer/PHPUnitDataProviderParamTypeInferer.php
```php
class SkipInDirectArrayValuePHPUnitDataProvider extends TestCase
{
protected function getData()
{
return [
['a', 'b', 'c'],
];
}
public function dataProvider()
{
$data = $this->getData();
return $data;
}
/**
* @dataProvider dataProvider
*/
public function test($a, $b, $c)
{
}
}
```
with dataProvider got from another method call, currently got error:
```bash
1) Rector\Tests\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector\ParamTypeDeclarationRectorTest::test with data set #14 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\TypeDeclaration\TypeInferer\ParamTypeInferer\PHPUnitDataProviderParamTypeInferer::resolveReturnStaticArrayTypeByParameterPosition()" on line 115
```
> [TypeDeclaration] Skip indirect get array value on PHPUnit dataProvider get on ParamTypeDeclarationRector

- rules-tests/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/int_type.php.inc
- rules-tests/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/numberz.php.inc
- rules/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector.php
```php
public function run(array $array, string $item)
{
$value = count($array);
return "We have {$value} {$item}";
}
```
Currently produce:
```php
return sprintf('We have %s %s', $value, $item);
```
which should be: 
```php
return sprintf('We have %d %s', $value, $item);
```
> [CodingStyle] Handle Non-string specifier for EncapsedStringsToSprintfRector

- .github/workflows/build_scoped_rector.yaml
Sometime, when 2 or more consecutive PRs merged in very near time, the checkout rectorphp/rector-src is overlapped and reverting other commit change so need to manually trigger build scoped. 
ref https://github.com/rectorphp/rector/commit/0dad1bbb20e92668772df4f6de517f4a7cf00079 for sample use case.
This should not happen on create a tag, so wait first to ensure it checking out latest rector-src.
> [Scoped] Wait 3 minutes before checkout rectorphp/rector-src on create a tag

- rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
- tests/Issues/IssueEarlyReturnAndOr/Fixture/fixture.php.inc
- tests/Issues/IssueEarlyReturnAndOr/IssueEarlyReturnAndOrTest.php
- tests/Issues/IssueEarlyReturnAndOr/config/configured_rule.php
```php
class ComplexAndOr
{
public function run($a, $b, $c, $d)
{
if (($a && false === $b) || ! $c) {
return '';
}
return $d;
}
}
```
with use both: `ChangeAndIfToEarlyReturnRector` and `ChangeOrIfReturnToEarlyReturnRector`, it currently got error:
```bash
1) Rector\Core\Tests\Issues\IssueEarlyReturnAndOr\IssueEarlyReturnAndOrTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Rector\NodeNestingScope\ContextAnalyzer::isHasAssignWithIndirectReturn(): Argument #1 ($node) must be of type PhpParser\Node, null given, called in /Users/samsonasik/www/rector-src/rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php on line 242
```
> [EarlyReturn] Handle both ChangeAndIfToEarlyReturnRector and ChangeOrIfReturnToEarlyReturnRector

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_used_in_if_cond_reassign_in_else.php.inc
- src/PhpParser/Comparing/ConditionSearcher.php
```php
$value = 'a value';
if ($value) {
$value = true;
}  else {
$value = false;
}
```
It currently remove the initialization:
```diff
-        $value = 'a value';
```
which make error : "Undefined variable $value"
> [DeadCode] Skip used in If_ cond, reassign in Else_ on RemoveUnusedVariableAssignRector

- packages/BetterPhpDocParser/PhpDocManipulator/PhpDocClassRenamer.php
- packages/BetterPhpDocParser/ValueObject/PhpDoc/DoctrineAnnotation/AbstractValuesAwareNode.php
- tests/Issues/RenameClassInCallbackFromAssertAnnotation/Fixture/callback_with_curly_braces.php.inc
- tests/Issues/RenameClassInCallbackFromAssertAnnotation/Fixture/callback_with_string_value.php.inc
- tests/Issues/RenameClassInCallbackFromAssertAnnotation/RenameClassInCallbackFromAssertAnnotationTest.php
- tests/Issues/RenameClassInCallbackFromAssertAnnotation/config/configured_rule.php
Hi,
When trying to play around I encountered an issue with how the `callback` option of a `Choice` assert annotation was done.
So this is a proposal for a possible solution, don't hesitate if you have any suggestion!
The assertion `Choice` provided by Symfont accept an option `callback`
which can either be of type `string|array|Closure`.
In this case I think we are only interested by the `array` case since
it's the only one in which a class name can be provided.
The phpdoc parser will provide us with a node of type `CurlyListNode`
but it's currently treated like an array.
In addition the `AbstractValuesAwareNode::changeValue` method will
always check if the new value is quoted or not even when the value is
not actually a `string`.
Following I provide a version of the errors I had:
``` …
```
> Fix handling of curly braces for choice's callback

- scoper.php
- utils/compiler/src/PhpScoper/StaticEasyPrefixer.php
The patch https://github.com/rectorphp/rector-src/pull/646 cause adding : 
```php
RectorPrefix20210811\Helmich\TypoScriptParser\Parser\AST\Statement
```
in : 
- https://github.com/rectorphp/rector/blob/9d7620e51f19d58e2e038dd1da41b9fad2d26859/vendor/helmich/typo3-typoscript-parser/src/Parser/Traverser/Visitor.php#L24
- https://github.com/rectorphp/rector/blob/9d7620e51f19d58e2e038dd1da41b9fad2d26859/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php#L26
as parameter into `Visitor` and `AbstractTypoScriptRector` which it may cause it won't work on extended classes. This patch ensure:
- unprefixed Statement to use `Helmich\TypoScriptParser\Parser\AST\Statement` in the parameter.
- Add `Helmich\TypoScriptParser\Parser\AST\Statement` to scoper autoload …
> [Scoper] Unprefix Helmich\TypoScriptParser\Parser\AST\Statement

- rules-tests/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/move_comment_in_if_stmt.php.inc
- rules-tests/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/move_comment_in_if_stmt2.php.inc
- rules/EarlyReturn/NodeFactory/InvertedIfFactory.php
- rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
```php
public function canDrive(Car $car)
{
if ($car->hasWheels && $car->hasFuel) {
// a comment
return true;
}
return false;
}
```
It currently got : 
```diff
public function canDrive(Car $car)
{
if (!$car->hasWheels) {
+            // a comment
return false;
}
if (!$car->hasFuel) {
+            // a comment
return false;
}
// a comment
return true;
```
which the "// a comment" should be moved out to only have one above return true.
> [EarlyReturn] Move comment in If_ stmt for ChangeAndIfToEarlyReturnRector

- packages/NodeNameResolver/NodeNameResolver.php
- rules-tests/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector/Fixture/case_insensitive.php.inc
- rules/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector.php
- src/Rector/AbstractRector.php
When using `NormalizeNamespaceByPSR4ComposerAutoloadRector`, a namespace is not corrected if it differs only by case.
I wrote a test and made an attempt at a fix. Not sure if you'd prefer this being configured, but I added a strict parameter to AbstractRector::isName() and NodeNameResolver::isName() to allow for strict comparisons.
> Namespaces should use a case sensitive comparison

- rules-tests/DeadCode/Rector/ClassMethod/RemoveUselessParamTagRector/Fixture/skip_typed_closure.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUselessParamTagRector/Fixture/x.php.inc
- rules/DeadCode/PhpDoc/DeadParamTagValueNodeAnalyzer.php
Closes https://github.com/rectorphp/rector-src/pull/658 Fixes https://github.com/rectorphp/rector/issues/6628
> [DeadCode] Skip RemoveUselessParamTagRector on typed closure

- rules-tests/EarlyReturn/Rector/Return_/ReturnBinaryOrToEarlyReturnRector/Fixture/multiple_binary_or_start_with_method_call.php.inc
- rules/EarlyReturn/Rector/Return_/ReturnBinaryOrToEarlyReturnRector.php
- src/NodeAnalyzer/CallAnalyzer.php
```php
public function run($a, $b)
{
return $this->execute() || $a || $b;
}
```
Currently produce:
```diff
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
+        if ($this->execute()) {
+            return true;
+        }
return $this->execute() || $a || $b; …
```
> [EarlyReturn] Handle Repetitive If_ on use ReturnBinaryOrToEarlyReturnRector

- rules-tests/Defluent/Rector/MethodCall/NewFluentChainMethodCallToNonFluentRector/Fixture/skip_inside_if_cond.php.inc
- rules/Defluent/Rector/MethodCall/NewFluentChainMethodCallToNonFluentRector.php
```php
if ($instance = (new FluentInterfaceClass())->someFunction()->otherFunction()) {
return $instance;
}
```
Currently got error:
```bash
1) Rector\Tests\Defluent\Rector\MethodCall\NewFluentChainMethodCallToNonFluentRector\NewFluentChainMethodCallToNonFluentRectorTest::test with data set #7 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\Assign" on line 11 is child of "PhpParser\Node\Stmt\If_", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.
```
This may happen in `do{}` and `while {}`'s cond, so better to skip it.
> [Defluent] Skip NewFluentChainMethodCallToNonFluentRector on inside If_ cond

- rules-tests/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Fixture/skip_fluent_in_if_cond.php.inc
- rules/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector.php
```php
if ($obj->someFunction()->otherFunction()) {
}
```
Produce error:
```bash
1) Rector\Tests\Defluent\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector\FluentChainMethodCallToNormalMethodCallRectorTest::test with data set #3 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\MethodCall" on line 13 is child of "PhpParser\Node\Stmt\If_", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.
```
> [Defluent] Skip Fluent in If_ cond on FluentChainMethodCallToNormalMethodCallRector

- rules-tests/Defluent/Rector/MethodCall/InArgFluentChainMethodCallToStandaloneMethodCallRector/Fixture/new_in_arg_not_name.php.inc
- rules-tests/Defluent/Rector/MethodCall/InArgFluentChainMethodCallToStandaloneMethodCallRector/Fixture/skip_new_in_arg_not_name.php.inc
- rules-tests/Defluent/Rector/MethodCall/InArgFluentChainMethodCallToStandaloneMethodCallRector/Source/ValueObject.php
- rules/Naming/Naming/VariableNaming.php
```php
$this->processFluentClass(
(new $valueObject->class)->someFunction()->otherFunction()
);
```
Currently got error:
```bash
1) Rector\Tests\Defluent\Rector\MethodCall\InArgFluentChainMethodCallToStandaloneMethodCallRector\InArgFluentChainMethodCallToStandaloneMethodCallRectorTest::test with data set #8 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\NotImplementedYetException: 
/Users/samsonasik/www/rector-src/rules/Naming/Naming/VariableNaming.php:213
```
> [Defluent] Skip New_ with not a Name on InArgFluentChainMethodCallToStandaloneMethodCallRector

- rules-tests/DeadCode/Rector/If_/UnwrapFutureCompatibleIfPhpVersionRector/Fixture/skip_higher_current.php.inc
- rules/DeadCode/ConditionEvaluator.php
This can happen when composer have the following requirement:
```php
"require": {
"php": "^7.3 || ^8.0",
```
and we have code:
```php
if (version_compare(PHP_VERSION, '8.0', '<')) {
return 'a';
} else {
return 'b';
}
```
above code can run in php 7.3 or php 8.0, which both 'a' and 'b' can have result. Without this skip, it will result only:
```diff
-        if (version_compare(PHP_VERSION, '8.0', '<')) {
-            return 'a';
-        } else {
-            return 'b';
-        }
+        return 'a';
```
which invalid when we use php > 8.0
> [DeadCode] Skip UnwrapFutureCompatibleIfPhpVersionRector on higher than current php provider

- rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/skip_construct_class_extends.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/skip_invoke.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector/Source/MyPdo.php
- rules/DeadCode/Rector/ClassMethod/RemoveEmptyClassMethodRector.php
- src/ValueObject/MethodName.php
- Empty class method with extends class can be used for stub like in https://github.com/rectorphp/rector-src/pull/611
- Class with empty __invoke can be used for stub in test
> [DeadCode] Skip Empty Class Method for __construct with class extends, and class with __invoke

- packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php
- rules-tests/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Fixture/skip_mixin.php.inc
- rules-tests/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Fixture/skip_mixin2.php.inc
```php
/**
* @mixin SkipMixin
*/
class SkipMixin
{
public function someFunction()
{
$this->obj = $this;
$this->obj->run()->execute();
}
{
return $this;
}
public function execute()
{
return $this;
}
}
```
It currently crash:
```bash
[1]    69072 segmentation fault  vendor/bin/phpunit 
```
Removing `@mixin` got normal output
> [Defluent] Skip mixin on FluentChainMethodCallToNormalMethodCallRector

- packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php
- phpstan.neon
- rules-tests/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Fixture/skip_mixin_as_source.php.inc
- rules-tests/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Fixture/skip_mixin_in_source.php.inc
- rules-tests/Defluent/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Source/MixinClass.php
Continue of https://github.com/rectorphp/rector-src/pull/688 , the `@mixin` can make crash when the class used as source to be called.
```bash
.............[1]    4044 segmentation fault  vendor/bin/phpunit 
```
> [Defluent] Skip mixin in source on FluentChainMethodCallToNormalMethodCallRector

- rules-tests/Php80/Rector/FunctionLike/UnionTypesRector/Fixture/_remove_doc_array_typed2.php.inc
- rules/DeadCode/PhpDoc/DeadParamTagValueNodeAnalyzer.php
Like removal `@return` at https://github.com/rectorphp/rector-src/runs/3338083534#step:5:73
> [Php80] Handle Remove Doc Array Typed Param on UnionTypesRector

- rules/CodingStyle/NodeFactory/JsonEncodeStaticCallFactory.php
- rules/CodingStyle/Rector/Assign/ManualJsonStringToJsonEncodeArrayRector.php
> [CodingStyle] Use json_encode for json encode if the class 'Nette\Utils\Json' not found

- packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php
- rules/CodingStyle/Rector/Assign/ManualJsonStringToJsonEncodeArrayRector.php
Same file name with current file name already checked in previous `Strings::match($contents, self::MIXIN_REGEX)` of current content file.
> [NodeTypeResolver] Check current file name is not equal with source file name for mixin class in source

- rules/Defluent/Rector/MethodCall/NewFluentChainMethodCallToNonFluentRector.php
The `$this->typeChecker->isInstanceOf()` is need the first parameter to be a node, while `$node->getAttribute(AttributeKey::PARENT_NODE)` may not be a node. 
For MethodCall, Parent node can be null if parent node is removed by another rector rule.
> [Defluent] Ensure parent is a node on NewFluentChainMethodCallToNonFluentRector before check $this->typeChecker->isInstanceOf()

- rules-tests/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector/Fixture/skip_with_assign.php.inc
- rules/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector.php
To avoid error : 
```bash
Node "PhpParser\Node\Expr\StaticCall" on line 662 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.  
```
> [DeadCode] Skip RemoveParentCallWithoutParentRector on inside assign

- src/Exclusion/ExclusionManager.php
The parent of node can be removed by other rules for multi rules running. To avoid error:
```bash
"Rector\Core\Exclusion\ExclusionManager::hasNoRectorPhpDocTagMatch(): Argument #1 ($node) must be of type      
PhpParser\Node, null given
```
check parent attribute is null is needed.
> [Exclusion] Check Parent attribute is Node on ExclusionManager::isNodeSkippedByRector()

- rules-tests/Transform/Rector/New_/NewToConstructorInjectionRector/Fixture/multi_assign.php.inc
- rules/Transform/Rector/New_/NewToConstructorInjectionRector.php
```php
$dummyValidator = $temp =  new DummyValidator();
```
It currently got error:
```bash
1) Rector\Tests\Transform\Rector\New_\NewToConstructorInjectionRector\NewToConstructorInjectionRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\Assign" on line 11 is child of "PhpParser\Node\Expr\Assign", so it cannot be removed as it would break PHP code. Change or remove the parent node instead.
```
Using `AssignRemover` service fix it.
> [Transform] Handle Multi Assign on NewToConstructorInjectionRector

- build/target-repository/composer.json
Keep the branch-alias of `rector/rector` the same as `rector/rector-src`
> Bump branch-alias from 0.10 to 0.11

- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector/Fixture/phpdoc_method.php.inc
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector/Fixture/skip_phpdoc_method.php.inc
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector/Source/InterfaceWithPhpdocMethod.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector.php
Close #718 Fixes https://github.com/rectorphp/rector/issues/6651
> [DowngradePhp74] Skip php doc method on DowngradeContravariantArgumentTypeRector

- phpstan.neon
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeStaticTypeDeclarationRector/Fixture/remove_self_child_already_no_return_type.php.inc
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeStaticTypeDeclarationRector.php
ref https://github.com/rectorphp/rector/issues/6652
> [DowngradePhp80] Remove self return type if child already has no return type

- rules-tests/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector/Fixture/use_param_type.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector.php
It would be nice if the `@param` type was simply copied into the docblock for the downgraded property. Otherwise, code that passes phpstan in PHP 8 will not pass in lower versions.
> Param doctype not copied to property in DowngradePropertyPromotionRector

- rules-tests/CodingStyle/Rector/Use_/RemoveUnusedAliasRector/Fixture/skip_same_class_in_use_statement_not_used.php.inc
- rules-tests/CodingStyle/Rector/Use_/RemoveUnusedAliasRector/Fixture/skip_used_by_return_method_call.php.inc
- rules/CodeQuality/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector.php
- rules/CodingStyle/Rector/Use_/RemoveUnusedAliasRector.php
Given the folowing code:
```php
use Rector\Tests\CodingStyle\Rector\Use_\RemoveUnusedAliasRector\Source\StandaloneClass;
use Rector\Tests\CodingStyle\Rector\Use_\RemoveUnusedAliasRector\Source\DifferentNamespace\StandaloneClass as StandaloneClassDifferentNamespace;
class SkipSameClassInUseStatementNotUsed
{
{
return new StandaloneClassDifferentNamespace();
}
}
```
When the same class defined in the use statement, it got result:
```diff
use Rector\Tests\CodingStyle\Rector\Use_\RemoveUnusedAliasRector\Source\StandaloneClass;
-use Rector\Tests\CodingStyle\Rector\Use_\RemoveUnusedAliasRector\Source\DifferentNamespace\StandaloneClass as StandaloneClassDifferentNamespace;
+use Rector\Tests\CodingStyle\Rector\Use_\RemoveUnusedAliasRector\Source\DifferentNamespace\StandaloneC …
```
> [CodingStyle] Skip RemoveUnusedAliasRector when same class in use statement exists, but not used

- rules/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector.php
- rules/Php71/Rector/FuncCall/CountOnNullRector.php
- tests/Issues/CountOnNullExactlyArray/CountOnNullExactlyArrayTest.php
- tests/Issues/CountOnNullExactlyArray/Fixture/fixture.php.inc
- tests/Issues/CountOnNullExactlyArray/config/configured_rule.php
```php
{
$array = [];
if (count($array) > 0) {
}
}
```
Got the following result:
```diff
+    private const ARRAY = [];
{
-        if (count(self::ARRAY) > 0) {
+        if ((is_countable(self::ARRAY) ? count(self::ARRAY) : 0) > 0) {
}
```
which invalid as it is exactly an array for applied rules:
```php
use Rector\Php71\Rector\FuncCall\CountOnNullRector;
use Rector\Privatization\Rector\Class_\ChangeReadOnlyVariableWithDefaultValueToConstantRector;
```
> [Privatization][Php71] Handle CountOnNullRector + ChangeReadOnlyVariableWithDefaultValueToConstantRector usage on exactly array

- scoper.php
The fix is far to be perfect, but it still has the merit to replace:
```php
/**
* @var \Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser
*/
private $foo;
/**
* @var \Symfony\Component\Console\Style\SymfonyStyle
*/
private $bar;
/**
* @param \Symfony\Component\Console\Style\SymfonyStyle $a 
*/
public function myMethod($a) {}
```
to
```php
/**
* @var \RectorPrefix20210823\Symplify\Astral\NodeTraverser\SimpleCallableNodeTraverser
*/
private $foo;
/**
* @var \RectorPrefix20210823\Symfony\Component\Console\Style\SymfonyStyle
*/
private $bar;
/**
* @param \RectorPrefix20210823\Symfony\Component\Console\Style\SymfonyStyle $a 
*/
public function myMethod($a) {}
```
However, it does not work with unions types. 
Fixes https://github.com/rectorphp/rector/issues/6614
> fix(scoper): prefix vendor classes from PHPDoc, close #6614

- scoper.php
Revert https://github.com/rectorphp/rector-src/pull/739 as has false positives, ref https://github.com/rectorphp/rector-src/pull/739#issuecomment-903349730
This reverts commit 877cbb2de8150b672a966d7a8907ed63769e1cdd.
> Revert "fix(scoper): prefix vendor classes from PHPDoc

- rules/Php71/Rector/FuncCall/CountOnNullRector.php
to ensure the count parameter not removed by other rules.
> [Php71] Ensure count() function parameter exists early on CountOnNullRector

- rules-tests/TypeDeclaration/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/skip_null.php.inc
- rules/TypeDeclaration/Rector/FunctionLike/ParamTypeDeclarationRector.php
'null' cannot be used as standalone types
> [TypeDeclaration] Skip ParamTypeDeclarationRector on NullType

- rules/Removing/Rector/ClassMethod/ArgumentRemoverRector.php
The value to remove has to be enclosed as array.
The value also has to match the type. The example has a boolean `true`.
The example rule now matches that to prevent confusion.
Resolves: https://github.com/rectorphp/rector/issues/6657
> Fix wrong docs for ArgumentRemoverRector

- rules/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector.php
- tests/Issues/Issue6655/Fixture/fixture.php.inc
- tests/Issues/Issue6655/SimplifyIfElseAndRemoveUnusedAssignVariableTest.php
- tests/Issues/Issue6655/config/configured_rule.php
Closes #788 Fixes https://github.com/rectorphp/rector/issues/6655
> [DeadCode][CodeQuality] Handle SimplifyIfElseToTernaryRector + RemoveUnusedAssignVariableRector

- rules-tests/DeadCode/Rector/Cast/RecastingRemovalRector/Fixture/skip_with_set_get_magic.php.inc
- rules-tests/DeadCode/Rector/Cast/RecastingRemovalRector/Fixture/skip_with_set_magic.php.inc
- rules/DeadCode/Rector/Cast/RecastingRemovalRector.php
When property is not found on use casted `PropertyFetch`, it may be setted via `__set()` or `__get()`, which should be skipped.
> [DeadCode] Skip RecastingRemovalRector on has __set() and __get()

- rules-tests/CodingStyle/Rector/Assign/ManualJsonStringToJsonEncodeArrayRector/Fixture/null_item.php.inc
- src/PhpParser/Node/NodeFactory.php
```php
$json = '{"a":null}';
```
It got error:
```bash
1) Rector\Tests\CodingStyle\Rector\Assign\ManualJsonStringToJsonEncodeArrayRector\ManualJsonStringToJsonEncodeArrayRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\NotImplementedYetException: Not implemented yet. Go to "Rector\Core\PhpParser\Node\NodeFactory::createArrayItem()" and add check for "" node.
```
This patch fix it .
> [CodingStyle] Handle null item on ManualJsonStringToJsonEncodeArrayRector

- rules-tests/CodingStyle/Rector/Stmt/NewlineAfterStatementRector/Fixture/no_new_line_classlike.php.inc
- rules-tests/CodingStyle/Rector/Stmt/NewlineAfterStatementRector/Fixture/no_new_line_try_catch.php.inc
- rules-tests/CodingStyle/Rector/Stmt/NewlineAfterStatementRector/Fixture/no_new_line_try_switch.php.inc
- rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php
Add more statements for add new line after statement:
```
Namespace_::class,
TryCatch::class,
Class_::class,
Trait_::class,
Interface_::class,
Switch_::class,
```
> [CodingStyle] Add more statements for NewlineAfterStatementRector

- rules-tests/EarlyReturn/Rector/If_/ChangeOrIfReturnToEarlyReturnRector/Fixture/skip_same_return.php.inc
- rules/CodeQuality/Rector/ClassMethod/NarrowUnionTypeDocRector.php
- rules/EarlyReturn/Rector/If_/ChangeOrIfReturnToEarlyReturnRector.php
In rectify, previously, it will got:
> [EarlyReturn] Skip same return expr on ChangeOrIfReturnToEarlyReturnRector

- rules/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
- src/Rector/AbstractRector.php
- tests/Issues/Issue6670/Fixture/do_not_remove_used_class_method.php.inc
- tests/Issues/Issue6670/Fixture/fixture.php.inc
- tests/Issues/Issue6670/RemoveAlwaysElseAndUnusedPrivateMethodsRectorTest.php
- tests/Issues/Issue6670/config/configured_rule.php
Closes https://github.com/rectorphp/rector-src/pull/801 Fixes https://github.com/rectorphp/rector/issues/6670
By check `NodesToAddCollector` isActive() check, it seems fix it.
> [DeadCode][EarlyReturn] Handle RemoveUnusedPrivateMethodRector + RemoveAlwaysElseRector

- build/target-repository/.github/workflows/along_other_packages.yaml
- build/target-repository/composer.json
- composer.json
phpstan 0.12.97 was just released today https://github.com/phpstan/phpstan/releases
So right now, rector cannot be installed :-(
> Allowing future versions of phpstan

- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/class_string_array_item.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/class_string_array_item2.php.inc
- rules/TypeDeclaration/TypeAnalyzer/GenericClassStringTypeNormalizer.php
```php
class ClassStringArrayItem
{
public function getData()
{
return [
'invokables' => [
A::class => A::class,
B::class => B::class,
],
'factories'  => [
C::class => CFactory::class,
D::class => DFactory::class,
],
];
}
}
```
It currently produce long:
```diff
+     * @return array<string, class-string<\Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector\Fixture\A>|class-string<\Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector\Fixture\B>>[]|array<string, class-string<\Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector\Fixture\CFactory>|class-string<\Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector\Fixture\DFactory>>[]
```
which should be `@return array<string, …
> [TypeDeclaration] Handle too detailed array item class-string on AddArrayReturnDocTypeRector

- rules-tests/DeadCode/Rector/Assign/RemoveDoubleAssignRector/Fixture/skip_next_coalesce_assign.php.inc
- rules-tests/DeadCode/Rector/Assign/RemoveDoubleAssignRector/Fixture/skip_next_ternary_assign.php.inc
- rules/DeadCode/Rector/Assign/RemoveDoubleAssignRector.php
```php
class SkipNextTernaryAssign
{
public function run($check)
{
$exists = [];
$check
? []
: $exists = [rand(0,1)];
return $exists;
}
}
```
```diff
-        $exists = [];
-
```
which can make error `Undefined variable $exists`, ref https://3v4l.org/ps5N3
> [DeadCode] Skip next ternary & coalesce assign on RemoveDoubleAssignRector

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
- rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/skip_other_class_construct.php.inc
```php
final class OtherClassConstruct
{
{
return [OtherClass3::class, '__construct'];
}
}
```
```diff
+        return function ($property) : void {
+            (new \Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\Source\OtherClass3())->__construct($property);
+        };
```
which make a double call `__construct`, first on `new`, then call `->__construct()`. It should be skipped.
> [CodeQuality] Skip class __construct method on CallableThisArrayToAnonymousFunctionRector

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
- rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/skip_associative_array.php.inc
- rules/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php
```php
class SkipAssociativeArray
{
{
$data = ['extends' => $this, 'methods' => 'compareSize'];
}
protected function compareSize(int $first, $second): bool
{
return $first <=> $second;
}
}
```
```diff
-        $data = ['extends' => $this, 'methods' => 'compareSize'];
+        $data = function (int $first, $second) : bool {
+            return $this->compareSize($first, $second);
+        };
```
which should be skipped, ref https://3v4l.org/ja8Qo
> [CodeQuality] Skip associative array on CallableThisArrayToAnonymousFunctionRector

- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/Fixture/do_not_change_to_property_exists.php.inc
- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/Fixture/skip_not_configured_class.php.inc
- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/config/configured_rule.php
- rules/Renaming/Rector/PropertyFetch/RenamePropertyRector.php
PR https://github.com/rectorphp/rector-src/pull/825 introduce bug:
- not check classname equal with config
- change property when target new property exists, which will cause Fatal error.
This PR patch it.
> [Renaming] Do not change to property exists on RenamePropertyRector

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
- rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/skip_in_trait.php.inc
On trait, currently produce error:
```diff
1) Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\CallableThisArrayToAnonymousFunctionRectorTest::test with data set #4 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: array_keys(): Argument #1 ($array) must be of type array, null given
```
This PR patch it.
> [CodeQuality] Skip CallableThisArrayToAnonymousFunctionRector in trait

- rules/CodeQuality/Rector/If_/ExplicitBoolCompareRector.php
- tests/Issues/IssueOrIfExplicitBoolCompare/Fixture/fixture.php.inc
- tests/Issues/IssueOrIfExplicitBoolCompare/IssueOrIfExplicitBoolCompareTest.php
- tests/Issues/IssueOrIfExplicitBoolCompare/config/configured_rule.php
```php
class Fixture
{
/**
* @param string $a
*/
public function run($a = '"', $b)
{
if (! $a || ! $b) {
return;
}
}
}
```
It currently produce repetitive if:
```diff
-        if (! $a) {
+        if ($a === '') {
+            return;
+        }
+        if ($a === '0') {
+            return;
+        }
+        if ($a === '') {
+            return;
+        }
+        if ($a === '0') {
+            return;
+        }
+        if ($a === '') {
+            return;
+        }
+        if ($a === '0') {
+            return;
+        }
+        if ($a === '') {
+            return;
+        }
+        if ($a === '0') {
+            return;
+        }
+        if ($a === '') {
+            return;
+        }
+        if ($a === '0') {
+            return;
+        } …
```
> [CodeQuality][EarlyReturn] Handle ExplicitBoolCompareRector + ChangeOrIfReturnToEarlyRector

- packages/PHPStanStaticTypeMapper/PHPStanStaticTypeMapper.php
- rules-tests/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector/Fixture/has_method_type.php.inc
```php
class HasMethodType
{
public $obj;
public function loader($obj)
{
if (! method_exists($obj, 'findFile')) {
return;
}
return $this->obj = $obj;
}
}
```
It currently produce error:
```bash
1) Rector\Tests\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector\PropertyTypeDeclarationRectorTest::test with data set #24 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\NotImplementedYetException: Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper::mapToPHPStanPhpDocTypeNode for PHPStan\Type\Accessory\HasMethodType
```
> [TypeDeclaration] Handle PHPStan\Type\Accessory\HasMethodType on PropertyTypeDeclarationRector

- packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80/skip_static_object.php.inc
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80/static_object.php.inc
```php
class StaticObject
{
/**
* @var object
*/
protected $obj;
public function get($obj = null)
{
if (func_num_args() === 0) {
return $this->obj;
}
$this->obj = $obj;
return $this;
}
}
```
It produce `object|static` return type:
```diff
+    public function get($obj = null): object|static
```
which make Fatal error, ref https://3v4l.org/eeHbf
> [TypeDeclaration] Handle object|static return on ReturnTypeDeclarationRector

- build/target-repository/bootstrap.php
- rules-tests/TypeDeclaration/Rector/ClassMethod/ParamTypeByParentCallTypeRector/Fixture/extends_exception.php.inc
- stubs/Php/UnitEnum.php
Fixes https://github.com/rectorphp/rector/issues/6682
@TomasVotruba this is the possible solution I found right now, by add check in the `bootstrap.php` for scoped rector/rector.
> [TypeDeclaration] Handle UnitEnum not exists check on ParamTypeByParentCallTypeRector

- rules-tests/TypeDeclaration/Rector/Closure/AddClosureReturnTypeRector/Fixture/no_return_to_return_void.php.inc
- rules-tests/TypeDeclaration/Rector/Closure/AddClosureReturnTypeRector/Fixture/skip_has_return_to_return_void.php.inc
- rules-tests/TypeDeclaration/Rector/Closure/AddClosureReturnTypeRector/Fixture/skip_return_void.php.inc
- rules/TypeDeclaration/TypeInferer/ReturnTypeInferer.php
```php
class SkipReturnVoid
{
public function run(array $name = [])
{
call_user_func_array(function () use ($name) {
return $this->execute();
}, []);
}
public function execute(): void
{
}
}
```
```diff
+        call_user_func_array(function () use ($name): void {
```
which make fatal error, ref `A void function must not return a value`, ref https://3v4l.org/cUVjT
> [TypeDeclaration] Skip has return to return void on ReturnTypeDeclarationRector

- rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php
- tests/Issues/IssueAndIfCompleteDeMorgan/Fixture/fixture.php.inc
- tests/Issues/IssueAndIfCompleteDeMorgan/IssueAndIfCompleteDeMorganTest.php
- tests/Issues/IssueAndIfCompleteDeMorgan/config/configured_rule.php
```php
class ParentClass
{
protected $d;
}
class Fixture extends ParentClass
{
public function run($a, $b, $c)
{
if (($a === 'a' || $b === 'b') && $c) {
$this->d = 'd';
}
}
}
```
produce repetitive ifs and returns:
```diff
-        if (($a === 'a' || $b === 'b') && $c) {
-            $this->d = 'd';
+        if ($a === 'a') {
+            return;
}
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if ($b === 'b') {
+            return;
+        }
+ …
```
> [CodeQuality][EarlyReturn] Handle SimplifyDeMorganBinaryRector + CompleteDynamicPropertiesRector + ChangeAndIfToEarlyReturnRector

- rules/CodeQuality/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector.php
- tests/Issues/IssueChangeAndIfAndDateTimeAndDeMorgan/Fixture/fixture.php.inc
- tests/Issues/IssueChangeAndIfAndDateTimeAndDeMorgan/IssueChangeAndIfAndDateTimeAndDeMorganTest.php
- tests/Issues/IssueChangeAndIfAndDateTimeAndDeMorgan/config/configured_rule.php
```php
class Fixture
{
public function run($a, $b, $c)
{
if (($a === 'a' || $b === 'b') && $c) {
$d = 'd';
}
}
}
```
It currently repetitive ifs and returns:
```diff
-        if (($a === 'a' || $b === 'b') && $c) {
-            $d = 'd';
+        if ($a === 'a') {
+            return;
}
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if ($b === 'b') {
+            return;
+        }
+        if ($a === 'a') {
+            return;
+        }
+        if …
```
> [CodeQuality][EarlyReturn] Handle SimplifyDeMorganBinaryRector + DateTimeToDateTimeInterfaceRector + ChangeAndIfToEarlyReturnRector

- packages/VendorLocker/NodeVendorLocker/ClassMethodReturnTypeOverrideGuard.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80/return_parent_class.php.inc
```php
class ParentClass
{
public function get(): ParentClass
{
return $this;
}
}
class ChildClass extends ParentClass
{
public function get(): ParentClass
{
return $this;
}
}
```
It produce parent return static:
```diff
class ParentClass
{
-    public function get(): ParentClass
+    public function get(): static
```
which make it Fatal error: `Declaration of ChildClass::get(): ParentClass must be compatible with ParentClass::get(): static`, ref https://3v4l.org/NWkFi
> [TypeDeclaration] Skip child class method return parent class on ReturnTypeDeclarationRector

- rules-tests/DeadCode/Rector/If_/RemoveDeadInstanceOfRector/Fixture/reassign_on_not_typed.php.inc
- rules-tests/DeadCode/Rector/If_/RemoveDeadInstanceOfRector/Fixture/reassign_on_not_typed_param.php.inc
- rules-tests/DeadCode/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_union_not_typed_param.php.inc
- rules-tests/DeadCode/Rector/If_/RemoveDeadInstanceOfRector/Fixture/union_typed_param.php.inc
- rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php
```php
/**
* @param DateTime|stdClass $value
*/
function run($value)
{
if ($value instanceof stdClass) {
return 'a';
}
if ($value instanceof DateTime) {
return 'b';
}
return 'c';
}
```
it produce:
```diff
-    if ($value instanceof DateTime) {
-        return 'b';
-    }
+    return 'b';
```
which non-typed param can pass non-defined in `@param` type types. This PR patch it.
> [DeadCode] Skip RemoveDeadInstanceOfRector on check variable from not typed param

- rules-tests/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/do_not_move_variable_up_foreach.php.inc
- rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
```php
class DoNotMoveVariableUpForeach
{
public function run(array $data, $a, $b)
{
foreach ($data as $value) {
if ($a && $b) {
unset($value);
}
}
$targets = [];
return $targets;
}
}
```
produce moved up variable next foreach to inside foreach:
```diff
foreach ($data as $value) {
-            if ($a && $b) {
-                unset($value);
+            if (!$a) {
+                continue;
}
+            if (!$b) {
+                continue;
+            }
+            unset($value);
+            return $targets;
}
```
that make Warning error:
```
Warning: Undefined variable $targets
```
ref https://3v4l.org/ManEo
> [EarlyReturn] Do not move up variable up next foreach on ChangeAndIfToEarlyReturnRector

- rules-tests/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/from_param.php.inc
- rules-tests/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/skip_from_param.php.inc
- rules/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector.php
```php
class FromParam
{
public function run($a)
{
if ($a === 0) {
$a = '0';
}
if ($a === 'a') {
return 0;
}
if ($a === 'z') {
return 10000;
}
return 0;
}
}
```
It produce changed param:
```diff
+    public function run(self::A)
{
```
which make it Parse Error: "Parse error: syntax error, unexpected token "::", expecting variable" ref https://3v4l.org/g9dvq
> [Privatization] Skip change variable from Param on ChangeReadOnlyVariableWithDefaultValueToConstantRector

- build/target-repository/docs/static_reflection_and_autoload.md
Add documentation for troubleshooting when sometime, rector doesn't detect all children classes via `PHPStan\Reflection\ReflectionProvider` that called via `FamilyRelationsAnalyzer ` service even both parent and child in same directory, and rector run on that directory.
The solution is to run `composer dump-autoload -o`
> [Doc] Autoload Troubleshooting

- rules-tests/TypeDeclaration/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/has_false_default_value.php.inc
- rules-tests/TypeDeclaration/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/has_null_default_value.php.inc
- rules-tests/TypeDeclaration/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/nullable_has_default_value.php.inc
- rules-tests/TypeDeclaration/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/variadic_constructor_param.php.inc
- rules/TypeDeclaration/Rector/Property/TypedPropertyFromStrictConstructorRector.php
```php
use stdClass;
class HasNullDefaultValue
{
/**
* @var stdClass
*/
private $stdClass = null;
public function __construct(stdClass $stdClass)
{
$this->stdClass = $stdClass;
}
}
```
It produce:
```diff
+    private \stdClass $stdClass = null;
```
which make Fatal error: "Fatal error: Default value for property of type stdClass may not be null. Use the nullable type ?stdClass to allow null" ref https://3v4l.org/aPY95
> [TypeDeclaration] Handle default value on TypedPropertyFromStrictConstructorRector

- packages-tests/BetterPhpDocParser/PhpDocInfo/PhpDocInfo/PhpDocInfoTest.php
- rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php
- tests/Issues/IssueVarConstantNewline/Fixture/fixture.php.inc
- tests/Issues/IssueVarConstantNewline/IssueVarConstantNewlineTest.php
- tests/Issues/IssueVarConstantNewline/config/configured_rule.php
```php
class Fixture
{
public const A = 'a';
public const B = 'b';
}
```
It produce double line:
```diff
public const A = 'a';
+
/**
* @var string
```
applied rules:
```php
Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector;
Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector;
```
which as already new line, the new line should not be added.
> [CodingStyle] Handle VarConstantCommentRector + NewlineAfterStatementRector

- rules-tests/Privatization/Rector/Class_/RepeatedLiteralToClassConstantRector/Fixture/skip_exists_different_value.php.inc
- rules-tests/Privatization/Rector/Class_/RepeatedLiteralToClassConstantRector/Fixture/use_exists_same_value.php.inc
- rules/Privatization/Rector/Class_/RepeatedLiteralToClassConstantRector.php
1. has same constant, with same value, currently apply:
```diff
-    private const REQUIRES = 'requires';
+    private const REQUIRES = self::REQUIRES;
```
which make Fatal error:
```bash
Fatal error: Uncaught Error: Cannot declare self-referencing constant self::REQUIRES
```
2. has same constant  with different value, currently use it:
```diff
-        if ($key === 'requires') {
-            return $items['requires'];
+        if ($key === self::REQUIRES) {
+            return $items[self::REQUIRES];
}
-        return $items['requires'];
+        return $items[self::REQUIRES];
```
which make code invalid as the value to compare is different.
> [Privatization] Skip constant exists on RepeatedLiteralToClassConstantRector

- build/target-repository/bootstrap.php
Fix error on scoped rector/rector:
```bash
un vendor/bin/rector list --ansi
4
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/runner/work/rector/rector/standalone/vendor/rector/rector/bootstrap.php on line 58
5
Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/runner/work/rector/rector/standalone/vendor/rector/rector/bootstrap.php on line 58
6
Error: Process completed with exit code 255.
```
> [Scoper] Fix bootstrap BackedEnum code

- rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
- avoid re-assign `$ifNextReturn` variable
- use `addNodesBeforeNode()` instead of loop of `addNodeBeforeNode()`
> [EarlyReturn] Refactor ChangeAndIfToEarlyReturnRector

- rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
- return array of Nodes instead of using `addNodesBeforeNode()`, `addNodeAfterNode()`
- remove unneeded removeNode() when next return array of nodes
> [EarlyReturn] Refactor ChangeAndIfToEarlyReturnRector: return array of Nodes

- build/target-repository/docs/static_reflection_and_autoload.md
@samsonasik I improved the description inside the original issue in order to leave a cleaner/shorter doc. I hope it is ok to you.
Fixes https://github.com/rectorphp/rector/issues/6688
> Documenting a solution for missing classes

- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/array_union_doc_loaded_class.php.inc
- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/array_union_doc_loaded_class2.php.inc
- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/do_not_remove_array_union_doc_not_loaded_class.php.inc
- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/do_not_remove_array_union_doc_not_loaded_class2.php.inc
- rules/DeadCode/PhpDoc/TagRemover/VarTagRemover.php
```php
final class DoNotRemoveArrayUnionDocNotLoadedClass
{
/** @var string[]|\NotLoadedClass[] */
private $unionValue;
}
```
It produce:
```diff
-    /** @var string[]|\NotLoadedClass[] */
+    private array $unionValue;
```
which the `@var` removed, which should not. 
For loaded class, it is working ok, it only happen when union type on not loaded class.
> [Php74] Do not remove Array union doc not loaded class on TypedPropertyRector

- packages/PHPStanStaticTypeMapper/TypeMapper/ArrayTypeMapper.php
- rules-tests/CodingStyle/Rector/ClassConst/VarConstantCommentRector/Fixture/pair_class_string_array.php.inc
- rules-tests/CodingStyle/Rector/ClassConst/VarConstantCommentRector/Fixture/pair_class_string_array2.php.inc
- rules-tests/CodingStyle/Rector/ClassConst/VarConstantCommentRector/Fixture/pair_class_string_array_too_many.php.inc
- rules/TypeDeclaration/TypeAnalyzer/GenericClassStringTypeNormalizer.php
Given the following code with more than 3 classes in list, it got too detailed items, for example:
```php
class A { }
class Aa { }
class B { }
class Bb { }
class C { }
class Cc { }
class D { }
class Dd { }
class PairClassStringArray2
{
private const CLASSES = [
A::class => Aa::class,
B::class => Bb::class,
C::class => Cc::class,
D::class => Dd::class,
];
}
```
It produce very long `@var`:
```diff
+ * @var array<string, class-string<\Rector\Tests\CodingStyle\Rector\ClassConst\VarConstantCommentRector\Fixture\Aa>|class-string<\Rector\Tests\CodingStyle\Rector\ClassConst\VarConstantCommentRector\Fixture\Bb>|class-string<\Rector\Tests\CodingStyle\Rector\ClassConst\VarConstantCommentRector\Fixture\Cc>|class-string<\Rector\Tests\CodingStyle\Rector\ClassConst\VarConstantCommentRector\Fixture\Dd>> …
```
> [CodingStyle] Handle too detailed pair class string array on VarConstantCommentRector

- build/target-repository/README.md
There is an official guideline that specifies the spelling of the proper name: https://typo3.org/project/brand/spelling-typo3
> TYPO3 is always written in uppercase, with no spaces. This rule covers all products under the TYPO3 project. URLs are the only exception to this rule.
> Use correct spelling for TYPO3

- rules-tests/Renaming/Rector/Name/RenameClassRector/FixtureAutoImportNames/rename_class_with_same_name_but_different_namespace_in_var_doc4.php.inc
- rules/Renaming/Rector/Name/RenameClassRector.php
The test somehow error right now tested in local:
```bash
1) Rector\Tests\Renaming\Rector\Name\RenameClassRector\AutoImportNamesTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/Renaming/Rector/Name/RenameClassRector/FixtureAutoImportNames/rename_class_with_same_name_but_different_namespace_in_var_doc4.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
namespace Rector\Tests\Renaming\Rector\Name\RenameClassRector\FixtureAutoImportNames;
use Rector\Tests\Renaming\Rector\Name\RenameClassRector\Source\SecondNamespace\SomeServiceClass;
+use Rector\Tests\Renaming\Rector\Name\RenameClassRector\Source\FirstNamespace\SomeServiceClass;
class RenameClassWithSameNameButDifferentNamespaceInVarDoc4
```
On the …
> [Renaming] Fully Qualified import doc same name renaming class error

- phpstan.neon
- rules/Arguments/ArgumentDefaultValueReplacer.php
- rules/DowngradePhp72/Rector/FuncCall/DowngradePregUnmatchedAsNullConstantRector.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeTrailingCommasInParamUseRector.php
- rules/DowngradePhp80/Rector/FuncCall/DowngradeStrEndsWithRector.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
- rules/MysqlToMysqli/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector.php
- rules/Php70/Rector/FuncCall/CallUserMethodRector.php
- rules/Php70/Rector/FuncCall/MultiDirnameRector.php
- rules/Php73/Rector/FuncCall/SetCookieRector.php
- rules/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector.php
- rules/PhpSpecToPHPUnit/Rector/MethodCall/PhpSpecMocksToPHPUnitMocksRector.php
- rules/PhpSpecToPHPUnit/Rector/MethodCall/PhpSpecPromisesToPHPUnitAssertRector.php
Fixes case when phpstan uses old parser (4.13.x-dev before tagging), while we use never one (4.13), where `getArgs()` is. This happens only on missing `preload.php` when we use `rector-src` to test joined dev packages. This would not affect the `rector/rector` users.
See https://github.com/rectorphp/phpstan-rules/runs/3756325213
> fix getArgs() missing in phpstan scoped version in rector-src packages

- rules-tests/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/do_not_escape_end_anchor.php.inc
- rules-tests/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/do_not_escape_expression_and_anchor.php.inc
- rules-tests/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/escaped_dollar_char.php.inc
- rules/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector.php
If `$` is an end anchor, it should not be escaped. Given the following code:
```php
preg_match("/^value$/", $value);
```
it currently produce:
```diff
+ preg_match("#^value\$#", $value);
```
which should be fine to be:
```diff
+ preg_match("#^value$#", $value);
```
> [CodingStyle] Do not escape expression on ConsistentPregDelimiterRector with double quote

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
Fixes https://github.com/rectorphp/rector/issues/6718
> [NodeCollector] Ensure pass Scope instance to 2nd arg on ClassReflection->getMethod() in ArrayCallableMethodMatcher

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
- packages/NodeCollector/ValueObject/ArrayCallableDynamicMethod.php
- rules/DeadCode/NodeAnalyzer/IsClassMethodUsedAnalyzer.php
Add `ArrayCallableDynamicMethod` value object to be used for array callable like `[$this, $other]` which method is dynamic, like in PRs:
- https://github.com/rectorphp/rector-src/pull/908
- https://github.com/rectorphp/rector-src/pull/909
Previusly, it handled by return back `Array_` object, this PR add the special value object to differentiate that it is a callable as well, but with dynamic method value.
> [NodeCollector] Add ArrayCallableDynamicMethod value object

- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/recursive_multiple_class_string_array.php.inc
- rules/TypeDeclaration/TypeAnalyzer/GenericClassStringTypeNormalizer.php
This was set to `mixed[]` at https://github.com/rectorphp/rector-src/pull/520
The regression happen at https://github.com/rectorphp/rector-src/pull/1112/files#r739660546
This patch set it back to `mixed[]`
> [TypeDeclaration] Add mixed[] array back on complex class-string structure on CompleteVarDocTypePropertyRector

- packages/BetterPhpDocParser/PhpDocNodeVisitor/UnionTypeNodePhpDocNodeVisitor.php
- rules/Php70/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php
- rules/Visibility/Rector/ClassMethod/ChangeMethodVisibilityRector.php
- src/Bootstrap/RectorConfigsResolver.php
- stubs/Symfony/Component/HttpKernel/Bundle/BundleInterface.php
I tried to apply latest `"rector/rector": "dev-main"` for use PHPStan 1.0, and got error into CodeIgniter project to test compatibilty early https://github.com/codeigniter4/CodeIgniter4/pull/5269 and got error:
```bash
Error: ] Could not process "system/CodeIgniter.php" file, due to:               
"Rector\NodeCollector\ScopeResolver\ParentClassScopeResolver::resolvePa
rentClassName(): Argument #1 ($scope) must be of type                  
PHPStan\Analyser\Scope, null given, called in                          
vendor/rector/rector/rules/Php70/Rector/StaticCall/StaticCallOnNonStati
cToInstanceCallRector.php:152". On line: 10    
```
this patch fix it.
> [Php70][Visibility] Avoid error  Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given

- packages/StaticTypeMapper/PhpParser/FullyQualifiedNodeMapper.php
- rules-tests/Naming/Rector/Class_/RenamePropertyToMatchTypeRector/FixturePhp80/use_nullable_aliased_on_promoted_property.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/ParamTypeByMethodCallTypeRector.php
```php
use Rector\Tests\Naming\Rector\Class_\RenamePropertyToMatchTypeRector\Source\EliteManager as AwesomeManager;
class UseNullableAliased
{
public function __construct(private ?AwesomeManager $eventManager)
{
}
}
```
It produce:
```diff
+    public function __construct(private ?AwesomeManager $eliteManager)
```
which should be : 
```diff
+    public function __construct(private ?AwesomeManager $awesomeManager)
```
follow the aliased name.
> [Naming] Use nullable alias on RenamePropertyToMatchTypeRector

- packages/StaticTypeMapper/PhpParser/FullyQualifiedNodeMapper.php
The scoped build somehow stopped after https://github.com/rectorphp/rector-src/commit/4b2877af19320a9b67b124bed02b107ff5c545a4 of PR https://github.com/rectorphp/rector-src/pull/1140.
I refactor `FullyQualifiedNodeMapper` to use direct parent node attribute to get nullable type.
> [StaticTypeMapper] Refactor FullyQualifiedNodeMapper

- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
- rules/TypeDeclaration/NodeAnalyzer/AutowiredClassMethodOrPropertyAnalyzer.php
- move `$classReflection->getName()` outside loop when posisible
- use `PhpAttributeAnalyzer` service to check attributes names 
- check for no params, private, or magic early
- clean up unneded $param->type === null check as already checked in hasParamAlreadyNonTyped()
> [DowngradePhp72] Improve DowngradeParameterTypeWideningRector

- packages/PostRector/Collector/UseNodesToAddCollector.php
- rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/ClassLikeNameClassNameImportSkipVoter.php
- use existing `$shortName` instead of re-call `$fullyQualifiedObjectType->getShortName()` in the loop.
- move $fullyQualifiedObjectType->getShortNameLowered() to outside loop on ClassLikeNameClassNameImportSkipVoter
- early compare to [] before check ->getShortNameLowered()
> [PostRector] Improve UseNodesToAddCollector

- rules/CodingStyle/ClassNameImport/ShortNameResolver.php
- src/NodeManipulator/ClassMethodAssignManipulator.php
- src/PhpParser/AstResolver.php
- src/PhpParser/NodeTraverser/RectorNodeTraverser.php
- remove `NodeFinder` dependency as already injected with `BetterNodeFinder` in `AstResolver`
- remove `NodeFinder` dependency as already injected with `BetterNodeFinder` in `ShortNameResolver`
- remove `NodeFinder` dependency as already injected with `BetterNodeFinder` in `ClassMethodAssignManipulator`
> [Core][CodingStyle][NodeManipulator] Improve Classes to use BetterNodeFinder instead of NodeFinder when BetterNodeFinder already injected

- rules-tests/PhpSpecToPHPUnit/Rector/Variable/PhpSpecToPHPUnitRector/Fixture/custom_matcher.php.inc
- rules-tests/PhpSpecToPHPUnit/Rector/Variable/PhpSpecToPHPUnitRector/Fixture/issue_3931.php.inc
- rules-tests/PhpSpecToPHPUnit/Rector/Variable/PhpSpecToPHPUnitRector/Fixture/let_create_edge.php.inc
- rules-tests/PhpSpecToPHPUnit/Rector/Variable/PhpSpecToPHPUnitRector/Fixture/mock_properties.php.inc
- rules/PhpSpecToPHPUnit/PhpSpecMockCollector.php
The regression from PR https://github.com/rectorphp/rector-src/pull/1144/files#r744037285
This PR try to resolve it.
> [PhpSpecToPHPUnit] Restore PhpSpecToPHPUnitRector behaviour on namespaced name usage

- rules/DowngradePhp80/Rector/ClassMethod/DowngradeStaticTypeDeclarationRector.php
Current scoped build got error:
```bash
In DowngradeStaticTypeDeclarationRector.php line 77:
[Rector\Core\Exception\ShouldNotHappenException]                                                                
Look at "Rector\DowngradePhp80\Rector\ClassMethod\DowngradeStaticTypeDeclarationRector::refactor()" on line 77  
```
On downgrading `bin rector.php` ref https://github.com/rectorphp/rector-src/runs/4128268737?check_suite_focus=true#step:9:72005
This PR try to resolve it.
> [Scoped] Fixing Scoped build bin rector.php

- build/target-repository/.github/workflows/along_other_packages.yaml
- build/target-repository/composer.json
- update phpstan req to ^1.1.1 like in root composer.json
- remove phpstan <=0.12.99 from conflict config as it already covered by requirement of phpstan ^1+ tagged stable.
> [PHPStan][Scoped] Remove phpstan <=0.12.99 from conflict config

- build/target-repository/composer.json
Current root composer.json now require `"phpstan/phpdoc-parser": "^1.2"`, 
https://github.com/rectorphp/rector-src/blob/fed8756bacf4220a777936c2456e326379ccfa77/composer.json#L22
so in the scoped, it needs to be updated to `"phpstan/phpdoc-parser": "<1.2",`
> [Scoped] Update phpstan/phpdoc-parser conflict conflict to < 1.2

- packages/NodeTypeResolver/NodeTypeResolver.php
- packages/NodeTypeResolver/PHPStan/TypeHasher.php
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/skip_nullable_self_referencing_property_setter.php.inc
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_nullable_self_referencing_property_getter.php.inc
- rules/DowngradePhp56/Rector/Pow/DowngradeExponentialAssignmentOperatorRector.php
- rules/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- rules/TypeDeclaration/TypeAnalyzer/ObjectTypeComparator.php
Closes https://github.com/rectorphp/rector-src/pull/1182 Fixes https://github.com/rectorphp/rector/issues/6789
> [TypeDeclaration] Skip nullable self referencing param and return on AddArrayParamDocTypeRector and ReturnTypeDeclarationRector

- packages-tests/NodeTypeResolver/PerNodeTypeResolver/PropertyTypeResolver/PropertyTypeResolverTest.php
- packages-tests/NodeTypeResolver/PerNodeTypeResolver/PropertyTypeResolver/Source/Enum.php
A property typed with a wildcard like `self::*` is turned into a `string` type, instead of a union of each supported constant-type, which would be more precise.
~~current: `self::*` phpdoc is mapped to `string`~~
expected
`self::*` phpdoc should be mapped to the concrete values like `'add'|'edit'|'clone'`
> PropertyTypeResolver enum test coverage

- build/target-repository/docs/rector_rules_overview.md
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/Fixture/different_check.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector/Fixture/use_or_is_resource_different_expr.php.inc
- rules/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector.php
- rules/DowngradePhp81/NodeManipulator/ObjectToResourceReturn.php
- rules/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector.php
Ensure to have the following behaviour :
```diff
-$obj instanceof \CurlHandle;
+is_resource($obj) || $obj instanceof \CurlHandle;
```
to keep code before and after downgraded  working when used in upper php version.
> [DowngradePhp80/81] Refactor Downgrade Resource Return to Object to use BooleanOr check

- rules/DowngradePhp55/Rector/ClassConstFetch/DowngradeClassConstantToStringRector.php
- scoper.php
@TomasVotruba this should resolve https://github.com/rectorphp/rector/issues/6797
The path of Deprecation function is now moved to `vendor/symfony/contracts/Deprecation` instead of old `vendor/symfony/deprecation-contracts`
> [Scoped] Fix scoping symfony Deprecation contract function

- rules/TypeDeclaration/Rector/Property/TypedPropertyFromStrictGetterMethodReturnTypeRector.php
Typed properties requires PHP 7.4.
> Add min PHP version for TypedPropertyFromStrictGetterMethodReturnTypeRector

- build/build-preload.php
- composer.json
- preload.php
- scoper.php
Attempt to fix missing trigger_deprecation() from Symfony package, that was just renamed.
See https://github.com/rectorphp/rector-src/pull/1199
> [Scoped] Fix missing trigger_deprecatoin() in explicit preload

- packages/Testing/PHPUnit/AbstractRectorTestCase.php
- rules-tests/Php71/Rector/FuncCall/CountOnNullRector/Fixture/skip_param_array.php.inc
- rules-tests/Php71/Rector/FuncCall/CountOnNullRector/Fixture/skip_property_array_filled_by_construct.php.inc
- rules/Php71/NodeAnalyzer/CountableAnalyzer.php
- src/NodeAnalyzer/PropertyFetchAnalyzer.php
```php
final class SkipPropertyArrayFilledByConstruct
{
/** @var array */
private $property;
public function __construct(array $property)
{
$this->property = $property;
}
public function run(): int
{
return count($this->property);
}
}
```
```diff
-        return count($this->property);
+        return count((array) $this->property);
```
which should be skipped.
> [Php71] Skip property with array doc filled by __construct on CountOnNullRector

- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/regression_property_removal.php.inc
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_propertyfetch_used_in_assign_expr.php.inc
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_propertyfetch_used_in_assign_expr2.php.inc
- rules/Removing/NodeManipulator/ComplexNodeRemover.php
Closes #1196 Fixes rectorphp/rector#6794
> [DeadCode] Skip RemoveUnusedPrivatePropertyRector on used in Assign expr

- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/sip_new_same_classname_usage.php.inc
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_clone_self.php.inc
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_clone_usage.php.inc
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_new_self_usage.php.inc
- rules/Removing/NodeAnalyzer/ForbiddenPropertyRemovalAnalyzer.php
- rules/Removing/NodeManipulator/ComplexNodeRemover.php
```php
class SkipCloneSelf
{
private $var;
public function __construct($var)
{
$this->var = $var;
}
{
$obj = clone $this;
echo $obj->var;
}
public function run2($var)
{
$obj = new self($var);
echo $obj->var;
}
}
```
It produce:
```diff
-    private $var;
-
-    public function __construct($var)
+    public function __construct()
{
-        $this->var = $var;
}
```
which should be skipped, ref https://3v4l.org/jjNe3
> [DeadCode] Skip clone and new self on RemoveUnusedPrivatePropertyRector

- rules/Naming/ExpectedNameResolver/InflectorSingularResolver.php
- tests/Naming/ExpectedNameResolver/InflectorSingularResolverTest.php
Ref. https://github.com/rectorphp/rector/issues/6796
I don't know if it's the right way, but we should skip some specific keywords like `is`, `has`, etc. while inflecting it as a singular.
> fix: ignore specified words while making it singularized

- rules-tests/Php71/Rector/FuncCall/CountOnNullRector/Fixture/skip_with_if_always_array.php.inc
- rules-tests/Php71/Rector/FuncCall/CountOnNullRector/Fixture/type_changed_on_if.php.inc
- rules/Php71/Rector/FuncCall/CountOnNullRector.php
```php
final class SkipWithIfAlwaysArray
{
public function run($a, $b)
{
$data = [];
if (! $a) {
$data[] = $b;
}
$data[] = count($data) !== 0 ? 'a' : 'b';
}
}
```
Currently produce:
```diff
+        $data[] = (is_array($data) || $data instanceof \Countable ? count($data) : 0) !== 0 ? 'a' : 'b';
```
which should be askipped as always array.
> [Php71] Skip with If always array on CountOnNullRector

- packages/PostRector/Collector/UseNodesToAddCollector.php
- packages/PostRector/Rector/NameImportingPostRector.php
- packages/StaticTypeMapper/ValueObject/Type/FullyQualifiedObjectType.php
- rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/AliasClassNameImportSkipVoter.php
- rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php
- rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php
- rules/CodingStyle/Node/NameImporter.php
- move method call to before loop when possible.
- reduce repetitive call getClassName
- move early check File and shouldApply
- class has backslash, no need to search in aliases, mark aliasedUses as empty
- get real path can be from File object
Close https://github.com/rectorphp/rector/issues/6768
> [PostRector][CodingStyle] Improve Auto import performance

- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php
- packages/NodeTypeResolver/PhpDoc/NodeAnalyzer/DocBlockClassRenamer.php
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/return_static_doc_clone_this.php.inc
@TomasVotruba given the following class:
```php
class ReturnStaticDocCloneThis extends \DateTime
{
/**
* @return static
*/
public function run(\DateTime $dateTime)
{
$obj = clone $this;
return $obj;
}
}
```
It cause error:
```bash
1) Rector\Tests\Renaming\Rector\Name\RenameClassRector\RenameClassRectorTest::test with data set #20 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper::mapStatic(): Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given, called in /Users/samsonasik/www/rector-src/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php on line 81
/Users/samsonasik/www/rector-src/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php:121 …
```
> [Renaming] Handle error on RenameClassRector when method return static

- packages/NodeTypeResolver/PhpDoc/NodeAnalyzer/DocBlockClassRenamer.php
- packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/array_static.php.inc
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/array_static2.php.inc
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/array_static3.php.inc
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/var_static_in_nullable.php.inc
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/var_static_in_nullable2.php.inc
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/var_static_in_union.php.inc
```php
class VarStaticInUnion extends \DateTime
{
/**
* @var DateTime|static|null
*/
private $dateTime;
}
```
It currently produce error:
```bash
1) Rector\Tests\Renaming\Rector\Name\RenameClassRector\RenameClassRectorTest::test with data set #17 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper::mapStatic(): Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given, called in /Users/samsonasik/www/rector-src/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php on line 81
```
> [Renaming] Handle var static docblock in union on RenameClassRector

- rules/Php81/Rector/ClassMethod/NewInInitializerRector.php
@TomasVotruba based on the test fixture : 
https://github.com/rectorphp/rector-src/blob/b201787edc0cc033d0108505c600c7b2ecc889a3/rules-tests/Php81/Rector/ClassMethod/NewInInitializerRector/Fixture/some_class.php.inc#L26
it doesn't add property promotion with `private` modifier. Or it should be added but not applied ?
> [Php81] Fix NewInInitializerRector code sample

- bin/rector.php
- src/Stubs/PHPStanStubLoader.php
- utils/compiler/src/Command/DowngradePathsCommand.php
- utils/compiler/src/PhpScoper/StaticEasyPrefixer.php
We don't have phpstan's extracted yet, I think we can remove code check for it for now, and we can back to check it if the scoper will use extracted phpstan.
> [Scoped] Remove phpstan-extracted code check reference

- .github/workflows/tests.yaml
- config/phpstan/parser.neon
- config/set/downgrade-php81.php
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/DowngradeReadonlyPropertyRectorTest.php
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/Fixture/class_property.php.inc
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/Fixture/class_property_docblock.php.inc
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/Fixture/class_property_docblock_tag.php.inc
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/Fixture/promoted_property.php.inc
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/config/configured_rule.php
- rules/DowngradePhp55/Rector/Foreach_/DowngradeForeachListRector.php
- rules/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector.php
- rules/Php81/Rector/Property/ReadOnlyPropertyRector.php
- rules/Privatization/NodeManipulator/VisibilityManipulator.php
- src/ValueObject/Visibility.php
I had to run the tests with PHP 8.1 to avoid a syntax error: https://phpstan.org/r/2a115211-9002-4800-9999-261b2f7d36a7
> [Downgrade PHP 8.1] Add DowngradeReadonlyPropertyRector

- phpstan.neon
- rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
- tests/Issues/JsonThrowWithChangeAndIf/Fixture/fixture.php.inc
- tests/Issues/JsonThrowWithChangeAndIf/JsonThrowWithChangeAndIfTest.php
- tests/Issues/JsonThrowWithChangeAndIf/config/configured_rule.php
```php
function f()
{
if (true && true) {
json_decode($a);
}
}
```
It produce error:
```bash
There was 1 failure:
1) Rector\Core\Tests\Issues\JsonThrowWithChangeAndIf\JsonThrowWithChangeAndIfTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
assert($itemStartPos >= 0 && $itemEndPos >= 0) in /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:865
```
applied rules:
```php
Rector\EarlyReturn\Rector\If_\ChangeAndIfToEarlyReturnRector;
Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector;
```
Fixes https://github.com/rectorphp/rector/issues/6812
> [EarlyReturn][Php73] Handle JsonThrowOnErrorRector + ChangeAndIfToEarlyReturnRector

- composer.json
- patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch
- phpstan.neon
- rector.php
- src/DependencyInjection/Loader/Configurator/RectorServiceConfigurator.php
We're using [Symfony PHP fluent configuration](https://github.com/symfony/symfony/issues/37186) to add autocomplete and ECS, PHPStan and Rector luxury to configs.
Yet it comes for a price, of complex configuration, mainly in case of value objects. Symfony container cannot work with value objects natively, [so extra inlining complexity has to be added](https://getrector.org/blog/2020/09/07/how-to-inline-value-object-in-symfony-php-config):
Also it's prone to errors:
```php
->call('configure', [[
->call('configure', [[[
->call('configure', [
->call('configure',
```
:red_circle: 
```php
PreferThisOrSelfMethodCallRector::TYPE_TO_PREFERENCE => [
TestCase::class => ValueObjectInliner::inline(PreferenceSelfThis::PREFER_THIS()),
],
PreferThisOrSelfMethodCallRector::TYPE_TO_PREFERENCE => …
```
> [DX] Add configure() method to service configuration to make configuration easy again

- rules/CodingStyle/Rector/ClassMethod/FuncGetArgsToVariadicParamRector.php
- src/Rector/AbstractRector.php
Automated node wrapping can cause unwanted bugs and hides implementation behind magic.
This shoud make using nodes easier and more explicit.
> [DX] Remove extra check for Stmt/Node

- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/in_between_parameter.php.inc
- rules/Autodiscovery/Rector/Class_/MoveServicesBySuffixToDirectoryRector.php
- rules/DeadCode/NodeCollector/UnusedParameterResolver.php
- rules/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector.php
- rules/Php71/Rector/TryCatch/MultiExceptionCatchRector.php
- tests/Issues/NullableParamNamespaced/Fixture/do_not_add_short_fqcn_class_name_docblock_nullable.php.inc
remove both of:
1. param in method 
2. arg in caller as well
Fixes https://github.com/rectorphp/rector/issues/6834
> [DeadCode] Add support remove unused in between private method parameter for RemoveUnusedPrivateMethodParameterRector

- src/ValueObject/PhpVersion.php
The value on constant in Phpversion class should be `80100` and `80200` for php 8.1 and 8.2 for consistency with previous version values, eg: php 7.4 with `70400`
> [Core] Fix PhpVersion value on php 8.1 and php 8.2

- src/Console/Command/InitCommand.php
- templates/rector.php.dist
Fixes https://github.com/rectorphp/rector/issues/6839
It requires PR https://github.com/rectorphp/rector-src/pull/1327 to be merged first as value for php 81 and php 82 currently 81000 and 82000 instead of `80100` and `80200`
> [Core] Refactor init command to use LevelSetList::UP_TO_PHP_XY set list

- build/target-repository/docs/rector_rules_overview.md
- phpstan.neon
- rules-tests/Renaming/Rector/ClassMethod/RenameAnnotationRector/FixtureRenameEverywhere/rename_everywhere.php.inc
- rules-tests/Renaming/Rector/ClassMethod/RenameAnnotationRector/RenameAnnotationEverywhereRectorTest.php
- rules-tests/Renaming/Rector/ClassMethod/RenameAnnotationRector/config/rename_everywhere.php
- rules/Renaming/Contract/RenameAnnotationInterface.php
- rules/Renaming/Rector/ClassMethod/RenameAnnotationRector.php
- rules/Renaming/ValueObject/RenameAnnotationByType.php
Closes https://github.com/rectorphp/rector/issues/6824
Now it's possible to rename simple annotations without type:
```php
// rector.php
use Rector\Renaming\Rector\ClassMethod\RenameAnnotationRector;
use Rector\Renaming\ValueObject\RenameAnnotation;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
return static function (ContainerConfigurator $containerConfigurator): void {
$services = $containerConfigurator->services();
$services->set(RenameAnnotationRector::class)
->configure([new RenameAnnotation('psalm-ignore', 'phpstan-ignore')]);
};
```
> [Renaming] Add generic rename annotation to RenameAnnotationRector

- src/Console/Command/ProcessCommand.php
Using console and json output together leads to crash on invalid json format:
https://github.com/rectorphp/getrector.org/pull/445#issuecomment-981681315
This PR fixes it :+1:
> Do not show --debug output on json error formatter

- build/config/config-downgrade.php
- rules/DowngradePhp80/Rector/New_/DowngradeArbitraryExpressionsSupportRector.php
Current scoped got error:
```bash
23| {
24|     private const LOCALE_TO_TRANSLITERATOR_ID = ['am' => 'Amharic-Latin', 'ar' => 'Arabic-Latin', 'az' => 'Azerbaijani-Latin', 'be' => 'Belarusian-Latin', 'bg' => 'Bulgarian-Latin', 'bn' => 'Bengali-Latin', 'de' => 'de-ASCII', 'el' => 'Greek-Latin', 'fa' => 'Persian-Latin', 'he' => 'Hebrew-Latin', 'hy' => 'Armenian-Latin', 'ka' => 'Georgian-Latin', 'kk' => 'Kazakh-Latin', 'ky' => 'Kirghiz-Latin', 'ko' => 'Korean-Latin', 'mk' => 'Macedonian-Latin', 'mn' => 'Mongolian-Latin', 'or' => 'Oriya-Latin', 'ps' => 'Pashto-Latin', 'ru' => 'Russian-Latin', 'sr' => 'Serbian-Latin', 'sr_Cyrl' => 'Serbian-Latin', 'th' => 'Thai-Latin', 'tk' => 'Turkmen-Latin', 'uk' => 'Ukrainian-Latin', 'uz' => 'Uzbek-Latin', 'zh' => 'Han-Latin'];
> 25|     private ?string …
```
> [Scoped] Fix downgrade AsciiSlugger

- rules/CodingStyle/Rector/Stmt/NewlineAfterStatementRector.php
- tests/Issues/Issue6840/ClassPropertyPromotionAndNewLineAfterStatementRectorTest.php
- tests/Issues/Issue6840/Fixture/fixture.php.inc
- tests/Issues/Issue6840/config/configured_rule.php
Handle stuck on used of 2 rules:
```php
Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector;
```
Closes https://github.com/rectorphp/rector-src/pull/1346 Fixes https://github.com/rectorphp/rector/issues/6840
> [Php80][CodingStyle] Handle ClassPropertyAssignToConstructorPromotionRector+NewlineAfterStatementRector

- rules-tests/Php74/Rector/Property/TypedPropertyRector/FixtureClassLikeTypeOnly/skip_union_object_prophecy.php.inc
- rules-tests/Php74/Rector/Property/TypedPropertyRector/FixtureClassLikeTypeOnly/skip_union_object_prophecy2.php.inc
- rules/Php74/Rector/Property/TypedPropertyRector.php
- rules/Php74/TypeAnalyzer/ObjectTypeAnalyzer.php
> [Php74] Skip ObjectProphecy type on TypedPropertyRector

- rules-tests/Privatization/NodeManipulator/VisibilityManipulatorTest.php
- rules/Privatization/NodeManipulator/VisibilityManipulator.php
Previously the VisibilityManipulator would strip public, protected and/or private visibility. This caused the ChangeMethodVisibilityRector to cause problems described in https://github.com/rectorphp/rector/issues/6829
refs: https://github.com/rectorphp/rector/issues/6829
closes: https://github.com/rectorphp/rector/issues/6829
> VisibilityManipulator adjustment

- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_non_private_property.php.inc
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_non_private_property2.php.inc
- rules-tests/Privatization/NodeManipulator/VisibilityManipulatorTest.php
- rules/Php81/Rector/Property/ReadOnlyPropertyRector.php
- rules/Privatization/NodeManipulator/VisibilityManipulator.php
Avoid error on public modifier like : 
```bash
1) Rector\Tests\BetterPhpDocParser\PhpDocInlineHtml\TestInlineHtmlTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Error: Cannot modify readonly property Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace::$stmts
``` 
on https://github.com/rectorphp/rector-src/pull/1364#issuecomment-984394205
> [Php81] Skip non private modifier on ReadOnlyPropertyRector

- composer.json
- patches/danielstjules-stringy-src-stringy-php.patch
Split part of https://github.com/rectorphp/rector-src/pull/1364#issuecomment-984577128 which stringy needs update methods to use `#[\ReturnTypeWillChange]` when used in php 8.1
while wait for PR https://github.com/danielstjules/Stringy/pull/208 to be merged.
> [Php 8.1 Dep] Update stringy vendor patches to update with #[\ReturnTypeWillChange]

- rules-tests/DowngradePhp81/Rector/Array_/DowngradeArraySpreadStringKeyRector/Fixture/array_spread_string_key.php.inc
- rules-tests/DowngradePhp81/Rector/Array_/DowngradeArraySpreadStringKeyRector/Fixture/array_spread_string_key_by_doc.php.inc
- rules/DowngradePhp81/Rector/Array_/DowngradeArraySpreadStringKeyRector.php
Previous PR https://github.com/rectorphp/rector-src/pull/1369 has equal before and after in fixtures, which incorrect.
> [DowngradePhp81] Fix DowngradeArraySpreadStringKeyRector

- packages/PHPStanStaticTypeMapper/TypeMapper/UnionTypeMapper.php
- tests/Issues/ComplexReadOnly/ComplexReadOnlyTest.php
- tests/Issues/ComplexReadOnly/Fixture/fixture.php.inc
- tests/Issues/ComplexReadOnly/config/configured_rule.php
```php
final class Fixture
{
public function __construct(
private array|null $condExprs
) {
}
public function getCondExprs(): array|null
{
if ($this->condExprs === []) {
return null;
}
return $this->condExprs;
}
}
```
```bash
1) Rector\Core\Tests\Issues\ComplexReadOnly\ComplexReadOnlyTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Look at "Rector\PHPStanStaticTypeMapper\TypeMapper\UnionTypeMapper::mapToPhpParserNode()" on line 137
```
Applied rules:
```php
Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector;
```
split of …
> [Php81][TypeDeclaration] Handle ReadOnlyPropertyRector + ReturnTypeDeclarationRector

- rules/DeadCode/Rector/MethodCall/RemoveEmptyMethodCallRector.php
- src/PhpParser/AstResolver.php
- src/PhpParser/ClassLikeAstResolver.php
- src/PhpParser/Printer/BetterStandardPrinter.php
Split of handle on php 8.1 on PR https://github.com/rectorphp/rector-src/pull/1364#issuecomment-984262906
> [Php81] Add Enum_ support when running on PHP 8.1 on AstResolver+ClassLikeAstResolver+RemoveEmptyMethodCallRector

- .github/workflows/build_scoped_rector.yaml
- .github/workflows/code_analysis.yaml
- .github/workflows/code_analysis_no_dev.yaml
- .github/workflows/e2e.yaml
- .github/workflows/packages_tests.yaml
- .github/workflows/php_linter.yaml
- .github/workflows/rector.yaml
- .github/workflows/tests.yaml
- .github/workflows/weekly_pull_requests.yaml
- build/target-repository/.github/workflows/along_other_packages.yaml
- build/target-repository/.github/workflows/bare_run.yaml
- build/target-repository/.github/workflows/e2e.yaml
- composer.json
- config/set/php81.php
- e2e/plain-views/composer.json
- e2e/template-extends/composer.json
- rector.php
@TomasVotruba this is split of https://github.com/rectorphp/rector-src/pull/1364 with manual change only with teskipped:
- rectify CI
- commented `MyCLabsClassToEnumRector` and `SpatieEnumClassToEnumRector` as it make `Enum` syntax upgrade needs to be skipped as it change `PhpVersion` class that extends : 
```diff
use MyCLabs\Enum\Enum;
- final class PhpVersion extends Enum
+ enum PhpVersion : int
```
which will need update currently manually of its usage:
```diff
-PhpVersion::PHP_52;
+PhpVersion::PHP_52->value;
```
and it seems cause change 
also other Enums, eg `ObjectReference` and `ApplicationPhase` manually:
```diff
-        if ($node->toString() === ObjectReference::PARENT()->getValue()) {
+        if ($node->toString() === ObjectReference::PARENT()->value) {
```
```diff
-        }, …
```
> [Dep] Update to php 8.1 requirement (manual)

- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_entity.php.inc
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_entity2.php.inc
- src/NodeManipulator/PropertyManipulator.php
Doctrine Entity id usually has only public getter, no setter. Given the following code:
```php
use Ramsey\Uuid\UuidInterface;
use Doctrine\ORM\Mapping as ORM;
/**
* News
*
* @ORM\Table(name="news")
* @ORM\Entity(repositoryClass="DoctrineFixtureDemo\Repository\NewsRepository")
*/
class News
{
/**
* @var UuidInterface
*
* @ORM\Id()
* @ORM\Column(type="uuid", unique=true)
* @ORM\GeneratedValue(strategy="CUSTOM")
* @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
*/
private UuidInterface $id;
/**
* @var string
*
* @ORM\Column(name="title", type="string", length=50, nullable=false)
*/
private $title;
/**
* Get id.
*
* @return string
*/
public function getId()
{
return (string) $this->id;
}
/**
* Set title.
*
* @param string $title
*
* @return self
*/
public function …
```
> [Php81] Skip ReadOnlyPropertyRector on Entity id

- rector.php
- rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php
- rules/CodingStyle/ClassNameImport/ShortNameResolver.php
- rules/MockeryToProphecy/Rector/ClassMethod/MockeryCreateMockToProphizeRector.php
- src/Configuration/RenamedClassesDataCollector.php
- src/NonPhpFile/Rector/RenameClassNonPhpRector.php
`ArraySpreadInsteadOfArrayMergeRector` when running on php 8.1, it make array string unpack applied.
>  [Rectify] [Php81] Enable Rectify on ArraySpreadInsteadOfArrayMergeRector on php 8.1 

- rules-tests/Php71/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/from_typed_param.php.inc
- rules-tests/Php71/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/skip_type_by_param_doc.php.inc
- rules-tests/Php71/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/skip_type_by_param_doc2.php.inc
- rules/DeadCode/Rector/Cast/RecastingRemovalRector.php
- rules/Php71/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php
- src/NodeAnalyzer/ExprAnalyzer.php
```php
class SkipTypeByParamDoc
{
/**
* @param int|null  $id
*/
public function run($id)
{
return $id !== null && $id !== 'null';
}
}
```
```diff
-        return $id !== null && $id !== 'null';
+        return $id !== null && $id !== 0;
```
which invalid as param is not typed and docblock can be the invalid one. It should be skipped. This PR skipped it.
> [Php71] Skip Type from @param doc on BinaryOpBetweenNumberAndStringRector

- ecs.php
- rules/Php70/EregToPcreTransformer.php
- src/DependencyInjection/Loader/Configurator/RectorServiceConfigurator.php
- src/PhpParser/Printer/BetterStandardPrinter.php
Based on https://github.com/rectorphp/rector-src/pull/1385#discussion_r762423186, the `FunctionTypehintSpaceFixer` needs to be skipped on various places to avoid apply space on `&$variable` on php 8.1
> [ECS] Skip FunctionTypehintSpaceFixer for add space on &$variable

- utils/compiler/src/Command/DowngradePathsCommand.php
Fixing downgrade scoped error https://github.com/rectorphp/rector-src/runs/4417920630?check_suite_focus=true#step:11:14 as not included in downgrade paths.
> [Scoped] Add missing utils to downgrade paths

- packages/PHPStanStaticTypeMapper/TypeMapper/HasOffsetTypeMapper.php
- packages/VendorLocker/ParentClassMethodTypeOverrideGuard.php
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/skip_implements_interface_method.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Source/RunnableInterface.php
ref https://github.com/rectorphp/rector-src/pull/1381/files#r762443102
> [TypeDeclaration] Skip implements method return type on ReturnNeverTypeRector

- packages/BetterPhpDocParser/PhpDocParser/PhpDocFromTypeDeclarationDecorator.php
- packages/VendorLocker/ParentClassMethodTypeOverrideGuard.php
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradeNeverTypeDeclarationRector/Fixture/equal_with_parent_return_type.php.inc
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradeNeverTypeDeclarationRector/Fixture/follow_parent_return_type.php.inc
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradeNeverTypeDeclarationRector/Source/RunnableInterface.php
Continue of https://github.com/rectorphp/rector-src/pull/1390, when the class method implements interface method already has never type, eg:
```php
interface Runnable
{
public function run(): ?stdClass;
}
class ImplementorRunnable implements Runnable
{
public function run(): never 
{
throw new \Exception('test');
}
}
```
above code in php 8.1 is valid ref https://3v4l.org/npms1#v8.1rc3.
But when it downgraded, it currently produce to:
```diff
-    public function run(): \stdClass
+    /**
+     * @return never
+     */
+    public function run()
```
which will make Fatal error:
```bash
Fatal error: Declaration of ImplementorRunnable::run() must be compatible with Runnable::run(): ?stdClass
```
ref https://3v4l.org/aZ2cq#v8.1rc3
This PR try to fix it.
> [DowngradePhp81] Follow parent return type on DowngradeNeverTypeDeclarationRector

- packages/VendorLocker/ParentClassMethodTypeOverrideGuard.php
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/from_anonymous.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Source/MixedReturn.php
Split of PR https://github.com/rectorphp/rector-src/pull/1395 that was cause error in php 7.2 and php 7.3 scoped.
This part is working when I test build scoped locally on php 7.2.
> [VendorLocker] Allow both in vendor for child and parent on ParentClassMethodTypeOverrideGuard

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/do_not_change_parent_anonymous_class_method.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/do_not_change_parent_anonymous_method_call.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector.php
```php
final class DoNotChangeParentAnonymousClassMethod
{
{
new class implements MixedReturn {
{
throw new Exception('test');
}
};
}
}
```
which anonymous class to have method that return never, it currently change to:
```diff
-    public function run()
+    public function run(): never
{
new class implements MixedReturn {
-            public function run()
+            public function run(): never
```
which the `never` type should only applied to inner anonymous function, not ClassMethod that has it, apply the change will make Fatal error:
```bash
Fatal error: Uncaught TypeError: FromAnonymous::run(): never-returning function must not implicitly return
```
ref https://3v4l.org/OcljB#v8.1rc3
This PR try to fix it
> [TypeDeclaration][Php 8.1] Do not change parent anonymous class method return type to never on ReturnNeverTypeRector

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/do_not_skip_yield_parent_anonymous_class_method.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector.php
continue of https://github.com/rectorphp/rector-src/pull/1400, when yield is in inner anonymous class under ClassMethod, it should not be skipped to have return never.
the skipped one is inside anonymous function only, when outide, it will check for never type.
> [ReturnTypeDeclaration][Php 8.1] Do not skip yield parent anonymous class method

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/do_not_skip_return_parent_anonymous_class_method.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector.php
Continue of https://github.com/rectorphp/rector-src/pull/1402, when return only in inner anonymous class, the skipped one is only in anonymous class.
> [TypeDeclaration][Php 8.1] Do not skip return on parent anonymous class method

- packages/NodeTypeResolver/NodeTypeResolver.php
`NodeTypeResolver::resolve()` class method is deprecated and it seems no longer used. I think it can be removed.
> [NodeTypeResolver] Remove deprecated NodeTypeResolver resolve method

- config/set/downgrade-php80.php
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/DowngradeReflectionGetAttributesRectorTest.php
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/Fixture/skip_non_reflection.php.inc
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/Fixture/with_arguments.php.inc
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/Source/NonReflectionGetAttributes.php
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector.php
Ref https://github.com/symplify/symplify/issues/3801
> [DowngradePhp80] Add getAttributes() reflection downgrade

- config/set/downgrade-php74.php
- rules-tests/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector/DowngradeReflectionGetTypeRectorTest.php
- rules-tests/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector/config/configured_rule.php
- rules/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector.php
Ref https://github.com/symplify/symplify/issues/3801
> [DowngradePhp74] Add DowngradeReflectionGetTypeRector

- rules/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector.php
- src/PhpParser/Node/BetterNodeFinder.php
To reduce repetitive check on verify found node has same FunctionLike (ClassMethod and Function_), the use case is found in the `ReturnNeverTypeRector` at previous PRs  https://github.com/rectorphp/rector-src/pull/1400 https://github.com/rectorphp/rector-src/pull/1402 https://github.com/rectorphp/rector-src/pull/1403
> [Core] Add BetterNodeFinder::hasInstancesOfInFunctionLikeScoped() to handle only true when has same parent FunctionLike

- patches/danielstjules-stringy-src-stringy-php.patch
Because new release of `rector-symfony` while it doesn't has vendor patch to URL based yet https://github.com/rectorphp/rector-symfony/commit/1c76befd5a64d57bd0732aad989b06fd3ed3cb33
ref https://github.com/rectorphp/rector-src/pull/1377#issuecomment-987520400
> [vendor-patches] Add back patches/danielstjules-stringy-src-stringy-php.patch to patches directory

- src/Application/ApplicationFileProcessor.php
- src/Application/FileProcessor/PhpFileProcessor.php
Fixes https://github.com/rectorphp/rector/issues/6849
Correction of previous PR https://github.com/rectorphp/rector-src/pull/1412/files
<br>
@samsonasik The file processors will have to be stateless for parallel to work correctly. That means there cannot be any "cache" properties in any file processors.
* The parallel will run e.g. 16 file processors in paralell with 16 files. Each has to return result (objects serialized to json) just for that file, then die.
* The json will be then merged in main proccess and json string deserialized back to objects.
<br>
The bug here was rather incorrect mering. I forgot the `array_merge()` skips nested mergin and overrides the `file_diff` only with last one.
<br>
I tried your original script (just narrowed to single directory):
```bash
bin/rector …
```
> [Core] Fix mergin of result in PhpFileProcessor

- rules/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector.php
- rules/Php74/Rector/LNumber/AddLiteralSeparatorToNumberRector.php
- rules/Php74/Rector/Property/TypedPropertyRector.php
- rules/TypeDeclaration/Rector/ClassMethod/AddVoidReturnTypeWhereNoReturnRector.php
- src/Contract/Rector/AllowEmptyConfigurableRectorInterface.php
- src/Validation/Collector/EmptyConfigurableRectorCollector.php
- Add AllowEmptyConfigurableRectorInterface interface for alternative to not show warning on allowed rector rule to have default fallback config
Alternative for https://github.com/rectorphp/rector-src/pull/1414
**Before**
**After**
I will create separate PR for moving `Rector\Php74\Rector\Function_\ReservedFnFunctionRector` to `Transform` namespace.
Fixes https://github.com/rectorphp/rector/issues/6850
Closes https://github.com/rectorphp/rector-src/pull/1414
> [Alternative][Validation] Add AllowEmptyConfigurableRectorInterface

- composer.json
- phpstan.neon
- rules/CodingStyle/Naming/ClassNaming.php
- rules/Naming/Naming/VariableNaming.php
- rules/Privatization/Naming/ConstantNaming.php
- rules/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector.php
- replacing with Symfony\String
- try removing dim fetch rename
> [DX] Replace deprecated danielstjules/stringy with Symfony\String

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/throw_property_fetch.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
On Coalesce usage, ref https://github.com/rectorphp/rector-src/pull/1415/files#r764486020
> [DowngradePhp80] Fix DowngradeThrowExprRector on property fetch to use not isset

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/do_not_change_parent_function.php.inc
- src/PhpParser/Node/BetterNodeFinder.php
```php
final class DoNotChangeParentFunction
{
{
function run()
{
throw new Exception('test');
}
}
}
```
currently produce:
```diff
-    public function run()
+    public function run(): never
{
-        function run()
+        function run(): never
```
which the classmethod run should not be changed, only inner function.
> [TypeDeclaration][Php 8.1] Do not change parent function to never on ReturnNeverTypeRector

- config/set/php74.php
- rules-tests/Transform/Rector/Function_/ReservedFnFunctionRector/Fixture/fixture.php.inc
- rules-tests/Transform/Rector/Function_/ReservedFnFunctionRector/ReservedFnFunctionRectorTest.php
- rules-tests/Transform/Rector/Function_/ReservedFnFunctionRector/config/configured_rule.php
- rules/Transform/Rector/Function_/ReservedFnFunctionRector.php
ReservedFnFunctionRector need to be configured to run, while registered in Php74 config set is not configured.
I think it should be moved to Transform namespace.
> [Transform] Move ReservedFnFunctionRector from Php74 to Transform namespace

- build/target-repository/docs/rector_rules_overview.md
- rules-tests/Transform/Rector/Class_/AddAllowDynamicPropertiesAttributeRector/config/configured_rule.php
- rules-tests/Transform/Rector/Class_/RemoveAllowDynamicPropertiesAttributeRector/config/configured_rule.php
- rules/Php55/Rector/String_/StringClassNameToClassConstantRector.php
- rules/Transform/Rector/Class_/AddAllowDynamicPropertiesAttributeRector.php
- rules/Transform/Rector/Class_/RemoveAllowDynamicPropertiesAttributeRector.php
The `classesToSkip` config is an exclude config, the rule will still run even if it is not configured.
> [Php55] Use AllowEmptyConfigurableRectorInterface on StringClassNameToClassConstantRector

- build/config/config-downgrade.php
- phpstan.neon
- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
Seeing the list of safe types in `downgrade-config.php`, it looks like we only have to maintain all the interfaces and parent types.
On the other hand, there are just 2 methods that are currently unsafe:
* in Symfony Loader interface
* in PSR Container interface
Instead of a "removing all types bug X", we should use "remove types on these known cases", to safe work and make list of weak methods easy to see.
> [Downgrade Php 7.2] Add opt-out parameter for unsafe types to avoid piling list of safe types

- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/upper_void.php.inc
- rules/TypeDeclaration/TypeInferer/ReturnTypeInferer.php
```php
class UpperVoid
{
public function upperVoid()
{
function toString()
{
return 'test';
};
}
}
```
it currently produce inner return type hint only:
```diff
public function upperVoid()
{
-        function toString()
+        function toString(): string
```
which upper class method doesn't return anything, that can return `void`.
This PR try to solve it.
> [TypeDeclaration] Add void upper inner function has return on ReturnTypeDeclarationRector
