rectorphp/rector-src

- src/Application/ApplicationFileProcessor.php
- src/Application/FileProcessor/PhpFileProcessor.php
> [TASK] Move RemovedAndAddedFilesCollector

- src/FileSystem/FilesFinder.php
- src/FileSystem/FilesystemTweaker.php
- tests/FileSystem/FilesFinder/FilesFinderTest.php
- Closes rectorphp/rector#6376
> [TASK] Take glob pattern for files into account

- composer.json
Ref https://github.com/rectorphp/rector-phpunit/issues/13
> Bump rector-phpunit without robot loader

- packages/Testing/PHPUnit/AbstractRectorTestCase.php
- tests/DependencyInjection/ConfigurableRectorImportConfigCallsMergeTest.php
Relates: rectorphp/rector#6415
> [TASK] Remove default method provideConfigFilePath

- docs/how_to_use_prefixed_service_in_custom_rule.md
ref https://github.com/rectorphp/rector/issues/6414#issuecomment-841138704
> [Doc] Add documentation for How to use prefixed service in custom rule

- bin/rector.php
- composer.json
- packages/ChangesReporting/Output/JsonOutputFormatter.php
- phpstan.neon
- scoper-php70.php
- scoper.php
- src/Application/VersionResolver.php
- src/Configuration/Configuration.php
- src/Console/ConsoleApplication.php
Inspired by https://github.com/symplify/symplify/pull/3179/files
> Use local version resolver

- src/Application/FileProcessor/PhpFileProcessor.php
Resolves: rectorphp/rector#6418
> [TASK] Output error message for file

- packages/Caching/Application/CachedFileInfoFilterAndReporter.php
- src/Console/Command/ProcessCommand.php
- src/FileSystem/FilesFinder.php
Fixes https://github.com/rectorphp/rector/issues/6389
Closes https://github.com/rectorphp/rector/pull/6398
> [Core] Fixes Cache in FilesFinder

- composer.json
- dev-docs/packages_ci_status.md
- packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php
- phpunit.xml
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/config/before_union_types.php
- src/Application/FileProcessor/PhpFileProcessor.php
@samsonasik @sabbelasichon This fixes the CI fails with `rules-tests`
> Fix ci of missing PHPStan extension types

- packages/Testing/PHPUnit/AbstractRectorTestCase.php
- rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php
- rules/DeadCode/Rector/If_/UnwrapFutureCompatibleIfFunctionExistsRector.php
- rules/DeadCode/Rector/If_/UnwrapFutureCompatibleIfPhpVersionRector.php
- src/Rector/AbstractRector.php
Remove `unwrapStmts()` where possible
> Remove unwrapStmts(), use native return array nodes in refactor() method

- config/services.php
- phpstan.neon
- src/PhpParser/NodeVisitor/CreatedByRuleNodeVisitor.php
- src/Rector/AbstractRector.php
- src/Validation/InfiniteLoopValidator.php
Follow up to https://github.com/rectorphp/rector-src/pull/51
> Infinity loop check #2

- build/target-repository/README.md
Attempt No.2 after https://github.com/rectorphp/rector/pull/6425 was closed
> remove proposal of rector-prefixed installation

- config/set/php80.php
- rules-tests/Arguments/Rector/FuncCall/FunctionArgumentDefaultValueReplacerRector/Fixture/some_function.php.inc
- rules-tests/Arguments/Rector/FuncCall/FunctionArgumentDefaultValueReplacerRector/Fixture/version_compare.php.inc
- rules-tests/Arguments/Rector/FuncCall/FunctionArgumentDefaultValueReplacerRector/FunctionArgumentDefaultValueReplacerRectorTest.php
- rules-tests/Arguments/Rector/FuncCall/FunctionArgumentDefaultValueReplacerRector/config/configured_rule.php
- rules/Arguments/ArgumentDefaultValueReplacer.php
- rules/Arguments/Contract/ArgumentDefaultValueReplacerInterface.php
- rules/Arguments/Rector/ClassMethod/ArgumentDefaultValueReplacerRector.php
- rules/Arguments/Rector/FuncCall/FunctionArgumentDefaultValueReplacerRector.php
- rules/Arguments/ValueObject/FuncCallArgumentDefaultValueReplacer.php
- rules/CodeQuality/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector.php
Resolves: rectorphp/rector#6271
> [TASK] Add FunctionArgumentDefaultValueReplacerRector

- composer.json
Resolves: rectorphp/rector#6428
> [TASK] allow latest phpstan

- rules-tests/Transform/Rector/Assign/PropertyFetchToMethodCallRector/Fixture/factory.php.inc
- rules-tests/Transform/Rector/Assign/PropertyFetchToMethodCallRector/Source/Generator.php
- rules-tests/Transform/Rector/Assign/PropertyFetchToMethodCallRector/config/configured_rule.php
- rules/Transform/Rector/Assign/PropertyFetchToMethodCallRector.php
Resolves: https://github.com/rectorphp/rector/issues/6440
> [TASK] Refactor getter without assignment node

- packages/BetterPhpDocParser/Printer/PhpDocInfoPrinter.php
closes https://github.com/rectorphp/rector/issues/6446
> [PhpDocInfoPrinter] fix running tests on windows

- rules-tests/CodeQuality/Rector/Foreach_/UnusedForeachValueToArrayKeysRector/Fixture/skip_used_in_compact.php.inc
- rules/CodeQuality/Rector/Foreach_/UnusedForeachValueToArrayKeysRector.php
Fixes https://github.com/rectorphp/rector/issues/6449
> [CodeQuality] Skip UnusedForeachValueToArrayKeysRector when value used in compact

- build/target-repository/composer.json
- composer.json
- Resolves: https://github.com/rectorphp/rector/issues/6450
> [TASK] Allow higher phpstan version

- rules-tests/Renaming/Rector/Name/RenameClassRector/FixtureAutoImportNames/rename_class_with_same_name_but_different_namespace_in_class.php.inc
- rules/Renaming/NodeManipulator/ClassRenamer.php
Relates: https://github.com/rectorphp/rector/issues/6441
> [TASK] Use method findFirstPreviousOfNode instead of findFirstPrevious

- rules-tests/CodeQuality/Rector/If_/SimplifyIfElseToTernaryRector/Fixture/mirror_comment.php.inc
- rules/CodeQuality/Rector/If_/SimplifyIfElseToTernaryRector.php
Fixes https://github.com/rectorphp/rector/issues/6452
> [CodeQuality] Mirror comment on SimplifyIfElseToTernaryRector

- packages-tests/BetterPhpDocParser/PhpDocInlineHtml/config/configured_rule.php
- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeMixedTypeDeclarationRector/Fixture/on_closure.php.inc
- rules/DowngradePhp80/Rector/FunctionLike/DowngradeMixedTypeDeclarationRector.php
ref https://github.com/rectorphp/rector-src/pull/105#issuecomment-848380283
> [DowngradePhp80] Handle DowngradeMixedTypeDeclarationRector on Closure

- packages-tests/NodeTypeResolver/PerNodeTypeResolver/ClassAndInterfaceTypeResolver/ClassTypeResolverTest.php
closes https://github.com/rectorphp/rector/issues/6468
> fix ClassTypeResolverTest on windows

- packages/Testing/PHPUnit/Behavior/MovingFilesTrait.php
- src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php
Based on https://github.com/rectorphp/rector-src/pull/127#issuecomment-851388360
Closes https://github.com/rectorphp/rector-src/pull/127 
Closes https://github.com/symplify/symplify/pull/3245
> [Testing] Fixes relative path against _temp_fixture_easy_testing for multi OSs support

- build/target-repository/docs/how_it_works.md
Adding document for order of rectors, about node traversal order.
related
https://github.com/rectorphp/rector/issues/6472
https://github.com/rectorphp/rector/issues/5962
> add details about node traversal order 

- rules-tests/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector/Fixture/nullable_string.php.inc
- rules-tests/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector/Fixture/skip_nullable_string_from_external.php.inc
- rules-tests/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector/Source/ParentNullableString.php
- rules/DowngradePhp72/Rector/Class_/DowngradeParameterTypeWideningRector.php
https://github.com/rectorphp/rector-src/pull/134#issuecomment-852158317
> [DowngradePhp72] Skip nullable string on DowngradeParameterTypeWideningRector from external

- scoper.php
Fixes https://github.com/rectorphp/rector/issues/6477
> [Scoper] Fix Could not resolve argument "Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator"

- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/param_converter.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Source/Post.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
> [BUGFIX] Fix if key is not a string

- rules-tests/PHPOffice/Rector/StaticCall/ChangePdfWriterRector/Fixture/fixture.php.inc
- rules-tests/PHPOffice/Rector/StaticCall/ChangePdfWriterRector/Fixture/fixture_variable_format.php.inc
- rules-tests/PHPOffice/Rector/StaticCall/ChangePdfWriterRector/config/configured_rule.php
- rules/PHPOffice/Rector/StaticCall/ChangePdfWriterRector.php
Resolves: https://github.com/rectorphp/rector/issues/6482
> [BUGFIX] Check if argument is string

- packages/BetterPhpDocParser/ValueObject/PhpDoc/DoctrineAnnotation/AbstractValuesAwareNode.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/api_platform_resource.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/param_converter.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
- rules/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector.php
Based on https://getrector.org/demo/df58f840-a218-4f37-bd1a-f48771bed3bc
Refs: rectorphp/rector#6484
> Add test fixture and fix for AnnotationToAttributeRector

- packages/ChangesReporting/Output/ConsoleOutputFormatter.php
- packages/ListReporting/Contract/Output/ShowOutputFormatterInterface.php
- packages/ListReporting/Output/ConsoleOutputFormatter.php
- phpstan.neon
- src/Console/Command/ShowCommand.php
- src/Console/Output/ShowOutputFormatterCollector.php
In order to better customize the output for the show command it should be extendable with custom OutputFormatter
> [FEATURE] Use OutputFormatter for show command

- rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/skip_embeddable_with_attribute.php.inc
- rules-tests/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/skip_entity_with_attribute.php.inc
- rules/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector.php
- src/Console/Output/ShowOutputFormatterCollector.php
Closes https://github.com/rectorphp/rector-src/pull/154
Fixes https://github.com/rectorphp/rector/issues/6488
> [Privatization] Skip Entity and Embeddable Attribute Doctrine\ORM\Mapping on FinalizeClassesWithoutChildrenRector

- rules-tests/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/Expected/ClassMatchesFilenameException.php
- rules-tests/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/Fixture/ClassMatchesFilename.php.inc
- rules-tests/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
- rules/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector.php
> [PSR4] Fix deleting file that matches class name

- rector.php
- rules-tests/PSR4/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
- rules/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector.php
one by one apply rules on php 8 check, this for property promotion `ClassPropertyAssignToConstructorPromotionRector`
> [PHP 8] Enable Property promotion

- .github/workflows/build_scoped_rector.yaml
ref https://github.com/rectorphp/rector-src/pull/178#discussion_r647852723
> [Scoped] Early downgrade src/functions

- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/api_platform_resource.php.inc
> Normalize array values in PhpAttributeGroupFactory

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/Fixture/return.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
Fixes https://github.com/rectorphp/rector/issues/5961
> [Downgrade 8.0] Match to switch, also for returns

- packages/NodeCollector/NodeCollector/NodeRepository.php
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/keep_case_mismatch.php.inc
- Closes https://github.com/rectorphp/rector-src/pull/194
- Closes https://github.com/rectorphp/rector/issues/6499
> Fix private method removal with different casing

- packages/BetterPhpDocParser/DataProvider/CurrentTokenIteratorProvider.php
- packages/NodeTypeResolver/NodeVisitor/FunctionMethodAndClassNodeVisitor.php
- packages/NodeTypeResolver/PhpDocNodeVisitor/NameImportingPhpDocNodeVisitor.php
- packages/NodeTypeResolver/PhpDocNodeVisitor/UnderscoreRenamePhpDocNodeVisitor.php
- packages/Testing/PHPUnit/AbstractRectorTestCase.php
- packages/Testing/PHPUnit/AbstractTestCase.php
- rector.php
- rules-tests/Php74/Rector/LNumber/AddLiteralSeparatorToNumberRector/config/configured_rule.php
- rules/CodingStyle/Rector/ClassConst/SplitGroupedConstantsAndPropertiesRector.php
- rules/Php74/Rector/LNumber/AddLiteralSeparatorToNumberRector.php
- rules/PhpSpecToPHPUnit/PHPUnitTypeDeclarationDecorator.php
- rules/Restoration/Rector/New_/CompleteMissingDependencyInNewRector.php
- src/Configuration/CurrentNodeProvider.php
- src/NodeAnalyzer/PropertyPresenceChecker.php
- src/NodeManipulator/ClassMethodManipulator.php
with temporary skip `ChangeReflectionTypeToStringToGetNameRector` as buggy on `ReflectionNamedType` getName check.
> [SetList] Add import SetList::PHP_74 in rector.php

- rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php
- tests/Issues/Issue6480/Fixture/fixture.php.inc
- tests/Issues/Issue6480/NegatedTernaryInsideDeadInstanceTest.php
- tests/Issues/Issue6480/config/configured_rule.php
Closes #174  Fixes https://github.com/rectorphp/rector/issues/6480
> [DeadCode][CodeQuality] Handle use RemoveDeadInstanceOfRector + SwitchNegatedTernaryRector with if instanceof check

- rules-tests/CodingStyle/Rector/Switch_/BinarySwitchToIfElseRector/Fixture/deep_nested_break.php.inc
- rules-tests/CodingStyle/Rector/Switch_/BinarySwitchToIfElseRector/Fixture/nested_break.php.inc
- rules/Renaming/NodeManipulator/SwitchManipulator.php
fixes https://github.com/rectorphp/rector/issues/6458
> [CodingStyle] Handle nested breaks in BinarySwitchToIfElseRector and SingularSwitchToIfRector

- rules-tests/CodingStyle/Rector/FuncCall/VersionCompareFuncCallToConstantRector/Fixture/short_version_compare.php.inc
- rules/CodingStyle/Rector/FuncCall/VersionCompareFuncCallToConstantRector.php
- rules/Renaming/NodeManipulator/SwitchManipulator.php
- src/PhpParser/Comparing/ConditionSearcher.php
Fixes https://github.com/rectorphp/rector/issues/6459 by use existing `PhpVersionFactory` service.
> [CodingStyle] Fix change short php version on VersionCompareFuncCallToConstantRector

- build/target-repository/README.md
- build/target-repository/docs/beyond_php_file_processors.md
- build/target-repository/docs/how_to_create_custom_fileprocessor.md
Resolves: https://github.com/rectorphp/rector/issues/6374
> [TASK] Add documentation about FileProcessors

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_used_after_if_else.php.inc
- rules/DeadCode/Rector/Assign/RemoveUnusedAssignVariableRector.php
Fixes https://github.com/rectorphp/rector/issues/6460
> [DeadCode] Skip RemoveUnusedAssignVariableRector on used after if else

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/foo.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/multiline.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
Closes https://github.com/rectorphp/rector-src/pull/165
> [Php80] Test for misplaced } on multiline in AnnotationToAttributeRector

- rules-tests/DeadCode/Rector/For_/RemoveDeadIfForeachForRector/Fixture/if_no_stmt_with_else.php.inc
- rules/DeadCode/Rector/For_/RemoveDeadIfForeachForRector.php
Closes https://github.com/rectorphp/rector/issues/6462
> [DeadCode] Handle RemoveDeadIfForeachForRector on if has no stmts with else 

- packages/PostRector/Rector/NameImportingPostRector.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/FixtureAutoImported/do_not_import_collision.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Source/Annotation/Apple.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Source/Attribute/Apple.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/auto_import.php
- rules/CodingStyle/ClassNameImport/ClassNameImportSkipper.php
- rules/CodingStyle/Node/NameImporter.php
- rules/Php80/Rector/Class_/AnnotationToAttributeRector.php
- less changelog links
- avoid duplicated attribute import
- fixup! avoid duplicated attribute import
> [PHP 8.0] Fix conflicting attribute import

- rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/cases_mix_up_default.php.inc
- rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/mutiple_cases.php.inc
- rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/mutiple_cases2.php.inc
- rules/Php80/NodeResolver/SwitchExprsResolver.php
- fix add one more case on 2 cases with no stmt switch case.
- Also Closes https://github.com/rectorphp/rector-src/pull/230 Fixes https://github.com/rectorphp/rector/issues/6508
> [Php80] Fix multiple cases and case mix up default for ChangeSwitchToMatchRector

- rules-tests/EarlyReturn/Rector/If_/RemoveAlwaysElseRector/Fixture/elseif.php.inc
- rules-tests/EarlyReturn/Rector/If_/RemoveAlwaysElseRector/Fixture/keep_the_else_if_elseif_has_no_stmt.php.inc
- rules-tests/EarlyReturn/Rector/If_/RemoveAlwaysElseRector/Fixture/lost_comment_before_elseif2.php.inc
- rules-tests/EarlyReturn/Rector/If_/RemoveAlwaysElseRector/Fixture/lost_comment_before_elseif3.php.inc
- rules-tests/EarlyReturn/Rector/If_/RemoveAlwaysElseRector/Fixture/process_empty_return_last.php.inc
- rules/EarlyReturn/Rector/If_/RemoveAlwaysElseRector.php
Closes https://github.com/rectorphp/rector-src/pull/224 Fixes https://github.com/rectorphp/rector/issues/6505
> [EarlyReturn] Handle mirror comments before elseif on RemoveAlwaysElseRector

- rules-tests/Php71/Rector/FuncCall/RemoveExtraParametersRector/Fixture/skip_func_get_all_on_func_call.php.inc
- rules/Php71/Rector/FuncCall/RemoveExtraParametersRector.php
- src/PHPStan/Reflection/VariadicAnalyzer.php
Closes #243 Fixes https://github.com/rectorphp/rector/issues/6516
> [Php71] Handle variadic check inside function with function_exists() check

- rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture/if_condition_method_call_with_namespaced_function_call.php.inc
- rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture/if_condition_method_call_with_namespaced_function_call2.php.inc
- rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Source/s.php
- rules/CodeQuality/Naming/MethodCallToVariableNameResolver.php
close #241 Fixes https://github.com/rectorphp/rector/issues/6502
> Alternative for 241 (Remove backslash from fallback var name)

- build/target-repository/.github/workflows/publish_docker_images.yaml
This reverts commit c2dbe67cb67e0e08e69029ba1516173723021d40.
> Revert "add DockerHub overview update workflow (#249)"

- src/Application/FileSystem/RemovedAndAddedFilesCollector.php
- src/NonPhpFile/NonPhpFileProcessor.php
ref https://github.com/rectorphp/rector-src/pull/257#issuecomment-864570415
> [Doc] Add comment @see for move method call to assign outside loop

- config/set/downgrade-php80.php
- packages/FileSystemRector/Parser/FileInfoParser.php
- packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php
- packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php
- packages/Testing/TestingParser/TestingParser.php
- rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture/if_condition_method_call_with_arg_on_no_assignment.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
- rules/DowngradePhp80/ValueObject/DowngradeAttributeToAnnotation.php
- src/Application/FileProcessor.php
- src/Autoloading/AdditionalAutoloader.php
- src/Configuration/Configuration.php
- src/Configuration/Option.php
- src/Console/Command/ProcessCommand.php
- src/Console/Command/ShowCommand.php
- src/Console/ConsoleApplication.php
- src/Reflection/FunctionLikeReflectionParser.php
- src/StaticReflection/DynamicSourceLocatorDecorator.php
- remove passing extra fileInfo with file, already included
- remove OPTION_ prefix
- remove extra parma in value object
- remove is cache debug
- add shot options constant
> Various cleanup

- packages/BetterPhpDocParser/ValueObject/PhpDoc/DoctrineAnnotation/CurlyListNode.php
**Source**
```php
/**
* @ApiResource(
*      mercure=true,
*      graphql={
*         "item_query",
*         "update",
*         "transition"={
*             "denormalization_context"={"groups"={"transition"}},
*             "security"="is_granted('transition',object)",
*             "mutation"=VmTransitionResolver::class,
*             "deserialize"=false,
*             "args"={"id"={"type"="ID!"}, "state"={"type"="String!"}}
*         }
*     }
* )
*/
```
**Result**
- Incorrect  _(before this change)_
```php
/**
* @ApiResource(mercure=true, graphql={"item_query", "update", "transition"=Array, "is_granted('transition',object)", VmTransitionResolver::class, false, Array})
*/
```
- Correct  _(after this change)_
```php
/**
* @ApiResource(mercure=true, graphql={"item_query", "update", …
```
> Handle nested arrays in CurlyListNode

- phpstan.neon
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector/Fixture/on_new.php.inc
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector/Fixture/on_new2.php.inc
- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector/Fixture/on_new3.php.inc
- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
- rules/TypeDeclaration/NodeTypeAnalyzer/CallTypeAnalyzer.php
Fix https://github.com/rectorphp/rector-src/runs/2894971370#step:14:103
> [DowngradePhp80] Enable New_ on DowngradeNamedArgumentRector

- packages/NodeCollector/NodeCollector/NodeRepository.php
- phpstan.neon
- rules-tests/RemovingStatic/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector/Fixture/double_static_method.php.inc
- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
- rules/Php70/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector.php
- rules/RemovingStatic/Rector/ClassMethod/LocallyCalledStaticMethodToNonStaticRector.php
- rules/Renaming/Rector/MethodCall/RenameMethodRector.php
- src/NodeManipulator/ClassMethodAssignManipulator.php
- src/PHPStan/Reflection/CallReflectionResolver.php
Ref https://github.com/rectorphp/rector/issues/6438,
follow up to https://github.com/rectorphp/rector-src/pull/276
Preparation for parallel runner
> [Parallel] Make DowngradeNamedArgumentRector use reflection over nodes

- build/downgrade-rector.sh
- rules/CodingStyle/NodeAnalyzer/SpreadVariablesCollector.php
- rules/CodingStyle/Rector/ClassMethod/UnSpreadOperatorRector.php
- src/PHPStan/Reflection/ClassMethodReflectionResolver.php
- [CodingStyle] Remove node repository dependency in UnSpreadOperatorRector
- [scoping] wait a bit to downgrade all the code
> [Prallel] Remove node repository dependency in UnSpreadOperatorRector

- packages/StaticTypeMapper/StaticTypeMapper.php
- phpstan.neon
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/skip_template.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/add_from_child.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayReturnDocTypeRector/Source/NestedGetData.php
- rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/private_property_reflection.php.inc
- rules/Php80/NodeResolver/ArgumentSorter.php
- rules/Php80/NodeResolver/RequireOptionalParamResolver.php
- rules/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector.php
- rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector.php
- rules/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- rules/TypeDeclaration/Reflection/ReflectionTypeResolver.php
- rules/TypeDeclaration/TypeInferer/ReturnTypeInferer/ReturnedNodesReturnTypeInferer.php
- src/Reflection/FunctionLikeReflectionParser.php
Follow up to https://github.com/rectorphp/rector-src/pull/278
- remove NodeRepository from OptionalParametersAfterRequiredRector
- remove NodeRepository dependency from ReturnTypeFromStrictTypedCallRector
- remove NodeRepository from ReturnedNodesReturnTypeInferer
- fixup! remove NodeRepository from ReturnedNodesReturnTypeInferer
> Cleaning up NodeRepository dependency

- rules-tests/CodingStyle/Rector/FuncCall/PreslashSimpleFunctionRector/Fixture/skip_defined_previous_call.php.inc
- rules/CodingStyle/Rector/FuncCall/PreslashSimpleFunctionRector.php
Fixes https://github.com/rectorphp/rector/issues/6497
> [CodingStyle] Skip PreslashSimpleFunctionRector on function defined previous call

- packages/BetterPhpDocParser/PhpDocParser/StaticDoctrineAnnotationParser.php
- packages/BetterPhpDocParser/PhpDocParser/StaticDoctrineAnnotationParser/PlainValueParser.php
- packages/NodeCollector/StaticAnalyzer.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/traing_comma_after_array.php.inc
- rules/CodeQuality/Rector/Array_/ArrayThisCallToThisMethodCallRector.php
- src/PhpParser/Node/NodeFactory.php
Fixes https://github.com/api-platform/core/pull/4334#discussion_r657761015
> Various NodeRepository removal + fix of Annotation parsing trailing comma

- rules-tests/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/if_in_closure.php.inc
- rules/EarlyReturn/NodeFactory/InvertedIfFactory.php
Fixes https://github.com/rectorphp/rector/issues/6503
> [EarlyReturn] Handle If inside closure for ChangeAndIfToEarlyReturnRector

- .phpstorm.meta.php
- packages/BetterPhpDocParser/PhpDoc/DoctrineAnnotationTagValueNode.php
- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php
- packages/BetterPhpDocParser/PhpDocParser/DoctrineAnnotationDecorator.php
- packages/BetterPhpDocParser/ValueObject/PhpDocAttributeKey.php
- packages/NodeTypeResolver/PhpDocNodeVisitor/ClassRenamePhpDocNodeVisitor.php
- packages/NodeTypeResolver/PhpDocNodeVisitor/NameImportingPhpDocNodeVisitor.php
- tests/Issues/IssueDoubleNestedAnnotatoinDocBlock/Fixture/some_fixture.php.inc
- tests/Issues/IssueDoubleNestedAnnotatoinDocBlock/IssueDoubleNestedAnnotatoinDocBlockTest.php
- tests/Issues/IssueDoubleNestedAnnotatoinDocBlock/Source/SomeAnnotation.php
- tests/Issues/IssueDoubleNestedAnnotatoinDocBlock/config/configure_rule.php
- add failing docblock pirnt test
- fix fqn vs short doctrine class name issue
> Fix accidental class rename on docblock imports

- rules-tests/TypeDeclaration/Rector/ClassMethod/AddVoidReturnTypeWhereNoReturnRector/Fixture/some_function.php.inc
- rules/TypeDeclaration/TypeInferer/SilentVoidResolver.php
> [TypeDeclaration] Prevent checking class like has external fully qualifieds when class like is null

- packages/NodeTypeResolver/MethodParameterTypeResolver.php
- packages/NodeTypeResolver/NodeTypeResolver/StaticCallMethodCallTypeResolver.php
- rules/CodeQuality/Rector/Catch_/ThrowWithPreviousExceptionRector.php
- rules/CodingStyle/NodeAnalyzer/SpreadVariablesCollector.php
- rules/DeadCode/Comparator/CurrentAndParentClassMethodComparator.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
- rules/Generics/TagValueNodeFactory/MethodTagValueNodeFactory.php
- rules/Php70/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector.php
- rules/Php72/NodeFactory/AnonymousFunctionFactory.php
- rules/Php80/NodeResolver/RequireOptionalParamResolver.php
- rules/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector.php
- src/NodeManipulator/ClassMethodAssignManipulator.php
- src/NodeManipulator/PropertyManipulator.php
Ref https://github.com/rectorphp/rector/issues/6530
> Cleanup stuff

- packages/NodeNestingScope/ContextAnalyzer.php
- rules/Php70/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector.php
Use separate method for in switch check.
> [NodeNestingScope] Remove Switch_ from LOOP_NODES constant value in ContextAnalyzer

- packages/BetterPhpDocParser/PhpDocParser/StaticDoctrineAnnotationParser.php
- packages/BetterPhpDocParser/PhpDocParser/StaticDoctrineAnnotationParser/PlainValueParser.php
- packages/NodeTypeResolver/MethodParameterTypeResolver.php
- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/multiline_content.php.inc
- rules/CodingStyle/Rector/ClassMethod/FuncGetArgsToVariadicParamRector.php
- consume multiline values in Attributes
- fixup! consume multiline values in Attributes
> [PHP 8.0] Fix attribute multi-line

- rules-tests/Php80/Rector/Identical/StrEndsWithRector/Fixture/substr_not_prefix.php.inc
- rules/Php80/Rector/Identical/StrEndsWithRector.php
Fixes https://github.com/rectorphp/rector/issues/6537
> Support negative equality on StrEndsWith rule

- packages/BetterPhpDocParser/PhpDocParser/ClassAnnotationMatcher.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/nested_unwrap.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Source/Response.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Source/Responses.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
- add more nested example
- fix annotation on ending route
> Improve suffix match

- packages/BetterPhpDocParser/PhpDoc/DoctrineAnnotationTagValueNode.php
- packages/BetterPhpDocParser/PhpDocNodeFinder/DoctrineAnnotationMatcher.php
- packages/BetterPhpDocParser/ValueObject/PhpDoc/DoctrineAnnotation/AbstractValuesAwareNode.php
Cherry pick of https://github.com/rectorphp/rector-src/pull/345/files
> Allow DoctrineTagValueNode values to be processed by traverser

- .github/workflows/build_scoped_rector.yaml
- .github/workflows/packages_tests.yaml
- config/set/downgrade-php80.php
- full_build.sh
@TomasVotruba It seems make downgrade `vendor/symfony/dependency-injection/Attribute` can be by directory.
> [DowngradePhp80] Early Register DowngradeNamedArgumentRector then DowngradeAttributeToAnnotationRector

- packages/NodeCollector/NodeCollector/NodeRepository.php
- packages/NodeCollector/NodeCollector/ParsedNodeCollector.php
- packages/NodeTypeResolver/NodeTypeCorrector/GenericClassStringTypeCorrector.php
- packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php
- rules-tests/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector/Fixture/doctrine_inflector_factory.php.inc
- rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php
- rules/Arguments/Rector/ClassMethod/ReplaceArgumentDefaultValueRector.php
- rules/DowngradePhp72/NodeAnalyzer/ParentChildClassMethodTypeResolver.php
- rules/PHPOffice/Rector/StaticCall/AddRemovedDefaultValuesRector.php
- rules/Removing/Rector/ClassMethod/ArgumentRemoverRector.php
- utils/compiler/src/Command/DowngradePathsCommand.php
Ref https://github.com/rectorphp/rector/issues/6543
Ref https://github.com/rectorphp/rector/issues/6543#issuecomment-874073386
> Fix doctrine inflector bug downgrade

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/skip_unwrap_symfony_nested_validators.php.inc
Closes https://github.com/rectorphp/rector/issues/6555
> Added failing test for symfony validator

- build/target-repository/composer.json
- composer.json
This update adds support for the recently released phpstan v0.12.91
> Add support for phpstan/phpstan 0.12.91

- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/skip_mixed_union_never_array_type.php.inc
Test for previous PR https://github.com/rectorphp/rector-src/pull/394
>  Add test for Fix key 1 TypeNormalizer::isUnionMixedArrayNeverType()

- rules-tests/Php80/Rector/Identical/StrEndsWithRector/Fixture/hardcoded.php.inc
- rules-tests/Php80/Rector/Identical/StrEndsWithRector/Fixture/hardcoded_not_identical.php.inc
- rules-tests/Php80/Rector/Identical/StrEndsWithRector/Fixture/substr_compare_hardcoded.php.inc
- rules-tests/Php80/Rector/Identical/StrEndsWithRector/Fixture/substr_compare_not_hardcoded.php.inc
- rules/Php80/Rector/Identical/StrEndsWithRector.php
closes https://github.com/rectorphp/rector/issues/6549
> [Php80] feat: str_ends_with with hardcoded string

- rules/TypeDeclaration/TypeNormalizer.php
- src/Reporting/MissingRectorRulesReporter.php
- note complementary rector in missing rector reportre
- fix cs
> tv add complementary marker

- composer.json
- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php
- packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfoFactory.php
- packages/BetterPhpDocParser/PhpDocManipulator/PhpDocTagRemover.php
- phpstan.neon
- rules/CodingStyle/ClassNameImport/ShortNameResolver.php
- rules/Php80/PhpDocCleaner/ConvertedAnnotationToAttributeParentRemover.php
- rules/Php80/Rector/Class_/AnnotationToAttributeRector.php
- src/functions/node_helper.php
- tests/debug_functions.php
- misc
- remove patches, already part of symfony/console native code
> Refactor node removing to phpdoc node traverser

- rules/DeadCode/PhpDoc/TagRemover/ParamTagRemover.php
- rules/DeadCode/Rector/ClassMethod/RemoveUselessParamTagRector.php
> Use PhpDocNodeTraverser to remove useless param tag value nodes

- rules-tests/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector/Fixture/with_attributes.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector.php
Fixes #376 Closes https://github.com/rectorphp/rector/issues/6546
> [DowngradePhp80] Handle Attribute in DowngradePropertyPromotionRector

- rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/some_static_call.php.inc
- rules-tests/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector/DowngradePhpTokenRectorTest.php
- rules-tests/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector.php
Ref https://wiki.php.net/rfc/token_as_object
> [DowngradePhp80] Add DowngradePhpTokenRector

- config/set/downgrade-php80.php
> [Downgrade PHP 8] Register DowngradePhpTokenRector to downgrade-php80 config set

- rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/default_outside_switch.php.inc
- rules/Php80/Rector/Switch_/ChangeSwitchToMatchRector.php
> [Php80] Handle Default value from previous switch for ChangeSwitchToMatchRector

- rules-tests/Php80/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/code_sniffer_case.php.inc
- rules-tests/Php80/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/fixture.php.inc
- rules-tests/Php80/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/not_array_first.php.inc
- rules-tests/Php80/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/process_token_get_all_but_keep_non_token_array.php.inc
- rules/Php80/Rector/FuncCall/TokenGetAllToObjectRector.php
Fixes https://github.com/rectorphp/rector/issues/6569
> Update TokenGetAllToObjectRector to use the correct method name

- src/NodeFactory/ClassWithPublicPropertiesFactory.php
- tests/NodeFactory/ClassWithPublicPropertiesFactory/ClassWithPublicPropertiesFactoryTest.php
- tests/NodeFactory/ClassWithPublicPropertiesFactory/Fixture/empty_class_no_namespace.php.inc
- tests/NodeFactory/ClassWithPublicPropertiesFactory/Fixture/full_usage.php.inc
- tests/NodeFactory/ClassWithPublicPropertiesFactory/Fixture/full_usage_no_leading_slashes.php.inc
Moved from https://github.com/rectorphp/rector-nette/pull/23
> Added factory to create class with public properties

- src/Application/ApplicationFileProcessor.php
Fixes https://github.com/rectorphp/rector/issues/6575
**Before**
**After**
> [Core] Fix --no-progress-bar option not applied

- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/inferred-type-vs-annotated-type.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/skip_nullable_typed.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector.php
Closes #451 Fixes https://github.com/rectorphp/rector/issues/6567
> [TypeDeclaration] Skip nullable typed on AddArrayParamDocTypeRector

- packages/Testing/PHPUnit/AbstractRectorTestCase.php
- rules-tests/CodingStyle/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/NewlineBeforeNewAssignSetRectorTest.php
- rules-tests/Defluent/Rector/ClassMethod/ReturnThisRemoveRector/ReturnThisRemoveRectorTest.php
- rules-tests/DowngradePhp70/Rector/String_/DowngradeGeneratedScalarTypesRector/DowngradeGeneratedScalarTypesRectorTest.php
- rules-tests/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector/DowngradeFlexibleHeredocSyntaxRectorTest.php
- rules-tests/Php73/Rector/String_/SensitiveHereNowDocRector/SensitiveHereNowDocRectorTest.php
Cherry picked from https://github.com/rectorphp/rector-src/pull/461/files
> skip Windows-broken rules

- packages/NodeTypeResolver/PhpDocNodeVisitor/NameImportingPhpDocNodeVisitor.php
- packages/PostRector/Collector/UseNodesToAddCollector.php
- packages/StaticTypeMapper/ValueObject/Type/AliasedObjectType.php
- phpstan.neon
- rules/CodingStyle/Application/UseImportsAdder.php
- rules/CodingStyle/ClassNameImport/UsedImportsResolver.php
- rules/Privatization/NodeAnalyzer/PropertyFetchByMethodAnalyzer.php
- tests/Issues/AliasedImportDouble/AliasedImportDoubleTest.php
- tests/Issues/AliasedImportDouble/Fixture/fixture.php.inc
- tests/Issues/AliasedImportDouble/IssueAnnotationTest.php
- tests/Issues/AliasedImportDouble/Rector/ClassMethod/AddAliasImportRector.php
- tests/Issues/AliasedImportDouble/config/configured_rule.php
Follow up to https://github.com/rectorphp/rector-src/pull/478
Fixes https://github.com/rectorphp/rector-src/pull/478#issuecomment-884196334
> Fix alias object imports

- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/nullable_setter.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/nullable_setter2.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/AddArrayParamDocTypeRector.php
Closes https://github.com/rectorphp/rector-src/pull/482
Closes https://github.com/rectorphp/rector-src/pull/483
Fixes https://github.com/rectorphp/rector/issues/6585
Fixes https://github.com/rectorphp/rector/issues/6586
> [TypeDeclaration] Handle nullable array param type on AddArrayParamDocTypeRector

- packages/Caching/FileSystem/DependencyResolver.php
- src/ValueObjectFactory/ProcessResultFactory.php
Ref https://github.com/rectorphp/rector/issues/6418#issuecomment-884498090
> Add errors even if no diff

- build/target-repository/composer.json
- config/set/downgrade-php81.php
- config/set/php81.php
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/normal_property.php.inc
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_non_read_only_promoted.php.inc
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_write_also_normal_property.php.inc
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/some_class.php.inc
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/ReadOnlyPropertyRectorTest.php
- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/config/configured_rule.php
- rules/Php81/Rector/Property/ReadOnlyPropertyRector.php
- rules/Privatization/NodeManipulator/VisibilityManipulator.php
- src/NodeManipulator/PropertyManipulator.php
See https://wiki.php.net/rfc/readonly_properties_v2#proposal
> [PHP 8.1] Add ReadOnlyPropertyRector

- build/target-repository/.github/workflows/along_other_packages.yaml
ref https://github.com/rectorphp/rector/runs/3139170727#step:6:32
> Fix along other packages gha

- rules/Renaming/Rector/ClassConstFetch/RenameClassConstFetchRector.php
- src/NodeManipulator/ClassManipulator.php
- tests/Issues/IssueImportedReturn/Fixture/repeated_trait_use.php.inc
- tests/Issues/IssueImportedReturn/Source/SomeTrait.php
- add trait use case
- fix trait check in ClassManipulator
> Fix trait check in ClassManipulator

- packages/NodeNameResolver/NodeNameResolver.php
- packages/StaticTypeMapper/ValueObject/Type/FullyQualifiedObjectType.php
- phpstan.neon
- src/Application/FileProcessor/PhpFileProcessor.php
- stubs/Prophecy/PhpUnit/ProphecyTrait.php
- tests/Issues/DoubleImportedTraitUse/DoubleImportedTraitUseTest.php
- tests/Issues/DoubleImportedTraitUse/Fixture/add_array_trait.php.inc
- tests/Issues/DoubleImportedTraitUse/config/double_imported_trait_use.php
> [Naming] Fix imported trait names

- packages/PostRector/Collector/PropertyToAddCollector.php
- packages/PostRector/DependencyInjection/PropertyAdder.php
- rules/DependencyInjection/NodeManipulator/PropertyConstructorInjectionManipulator.php
- rules/DependencyInjection/Rector/Class_/ActionInjectionToConstructorInjectionRector.php
- rules/Php80/Rector/Class_/DoctrineAnnotationClassToAttributeRector.php
- rules/RemovingStatic/Rector/Class_/DesiredClassTypeToDynamicRector.php
- rules/RemovingStatic/Rector/Class_/NewUniqueObjectToEntityFactoryRector.php
- rules/RemovingStatic/Rector/Class_/PHPUnitStaticToKernelTestCaseGetRector.php
- rules/RemovingStatic/Rector/Class_/PassFactoryToUniqueObjectRector.php
- rules/RemovingStatic/Rector/StaticPropertyFetch/DesiredStaticPropertyFetchTypeToDynamicRector.php
- rules/Transform/NodeAnalyzer/FuncCallStaticCallToMethodCallAnalyzer.php
- rules/Transform/Rector/FuncCall/ArgumentFuncCallToMethodCallRector.php
- rules/Transform/Rector/MethodCall/MethodCallToMethodCallRector.php
- rules/Transform/Rector/MethodCall/ServiceGetterToConstructorInjectionRector.php
- rules/Transform/Rector/MethodCall/VariableMethodCallToServiceCallRector.php
- rules/Transform/Rector/New_/NewToConstructorInjectionRector.php
- rules/Transform/Rector/New_/NewToMethodCallRector.php
- src/NodeAnalyzer/PropertyPresenceChecker.php
- src/Rector/AbstractRector.php
> Remove deprecated addConstructorDependencyToClass() from AbstractRector class, use PropertyToAddCollector directly instaed

- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- rector.php
- rules-tests/PSR4/Composer/PSR4NamespaceMatcherTest.php
- rules/PSR4/Composer/PSR4NamespaceMatcher.php
- src/NonPhpFile/NonPhpFileProcessor.php
Enabled skipped `AddSeeTestAnnotationRector`
> [Config] Clean up rector.php config

- rules-tests/DeadCode/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector/Fixture/skip_assign_to_property_fetch.php.inc
- rules/DeadCode/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector.php
> [DeadCode] Skip Assign to PropertyFetch on RemoveAssignOfVoidReturnFunctionRector

- rules-tests/DeadCode/Rector/MethodCall/RemoveEmptyMethodCallRector/Fixture/skip_fluent_return_this2.php.inc
- rules/DeadCode/Rector/MethodCall/RemoveEmptyMethodCallRector.php
> [DeadCode] Skip Static Call fluent on RemoveEmptyMethodCallRector

- config/parameters.php
- packages/Caching/CacheFactory.php
- packages/Caching/ValueObject/Storage/MemoryCacheStorage.php
- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_null_safe_test.php.inc
- rules/Php80/Rector/If_/NullsafeOperatorRector.php
- src/NodeAnalyzer/CallAnalyzer.php
- src/NodeManipulator/NullsafeManipulator.php
Closes https://github.com/rectorphp/rector/issues/6592
> Fix NullsafeOperatorRector 

- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_null_safe_test.php.inc
https://getrector.org/demo/1ebef980-e98f-6c14-988b-4bfe6a0e7eae
> Simplify skip_null_safe_test.php.inc

- rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector/Fixture/skip_string_variable.php.inc
- rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector/Fixture/some_class.php.inc
- rules/CodingStyle/NodeFactory/ArrayCallableToMethodCallFactory.php
- Closes https://github.com/rectorphp/rector-src/pull/546
- Fixes https://github.com/rectorphp/rector/issues/6602
> [CodingStyle] Fix ArrayCallableToMethodCallFactory for non-object types

- composer.json
to dogfood https://github.com/symplify/symplify/pull/3440#issuecomment-889390020
> [EasyTesting] dogfood next iteration

- rules-tests/DeadCode/Rector/FunctionLike/RemoveOverriddenValuesRector/Fixture/skip_assign_method_call.php.inc
- rules/DeadCode/Rector/FunctionLike/RemoveOverriddenValuesRector.php
Check call that may has side effect.
> [DeadCode] Using SideEffectNodeDetector::detectCallExpr() on RemoveOverriddenValuesRector

- rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/some_static_call.php.inc
- rules-tests/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector/Fixture/fqn_class_reference.php.inc
- rules/Php72/NodeFactory/AnonymousFunctionFactory.php
Closes https://github.com/rectorphp/rector/issues/6603
> Fix AnonymousFunctionFactory for class constant reference

- rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php
- rules/TypeDeclaration/Matcher/PropertyAssignMatcher.php
- src/NodeAnalyzer/PropertyFetchAnalyzer.php
Move `PropertyAssignMatcher->isPropertyFetch()` to `PropertyFetchAnalyzer->PropertyFetchAnalyzer()`
> [Core] Move isPropertyFetch() to PropertyFetchAnalyzer

- packages/VersionBonding/Application/MissedRectorDueVersionChecker.php
> [VersionBonding] Update rector warning message for min PHP version project

- build/target-repository/composer.json
- composer.json
Upgrading supported phpstan/phpstan to 0.12.94. All tests seem to pass.
> Upgrade phpstan/phpstan to 0.12.94

- packages/StaticTypeMapper/Mapper/PhpParserNodeMapper.php
- tests/Issues/IssueDowngradeMixedType/DowngradeMixedTypeTest.php
- tests/Issues/IssueDowngradeMixedType/Fixture/fixture.php.inc
- tests/Issues/IssueDowngradeMixedType/Source/SomeClass.php
- tests/Issues/IssueDowngradeMixedType/config/configured_rule.php
Closes #590 Fixes https://github.com/rectorphp/rector/issues/6611
> [DowngradePhp80] Handle both DowngradeTypedPropertyRector and DowngradeMixedTypeDeclarationRector Name parameter

- .github/workflows/build_scoped_rector.yaml
- build/build-rector-scoped.sh
Fixes https://github.com/rectorphp/rector/issues/6612
> [Scoper] No need to re-generate preload.php on scoping

- .github/workflows/code_analysis.yaml
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPromotedPropertyRector/Fixture/user_variable.php.inc
- rules/DeadCode/Rector/ClassMethod/RemoveUnusedPromotedPropertyRector.php
- rules/Naming/Naming/VariableNaming.php
- rules/Php72/Rector/Assign/ListEachRector.php
- src/PhpParser/Node/BetterNodeFinder.php
- add used variable test
- fix only ctor used promoted property removal
> [DeadCode] Fix removal of variable-used promoted property

- packages/Testing/PHPUnit/Behavior/MultipleFilesChangedTrait.php
- rules/DeadCode/NodeAnalyzer/IsClassMethodUsedAnalyzer.php
- tests/PhpUnit/MultipleFilesChangedTrait/Rector/Class_/CreateJsonWithNamesForClassRector.php
ref https://github.com/rectorphp/rector-src/pull/545#issuecomment-894380464
> [Testing] Fixing MultipleFilesChangedTrait under macOs

- config/set/downgrade-php80.php
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector/DowngradeAbstractPrivateMethodInTraitRectorTest.php
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector/Fixture/skip_abstract_non_private.php.inc
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector/Fixture/skip_non_abstract_private.php.inc
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector/Fixture/skip_non_trait.php.inc
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector/Fixture/with_abstract_private.php.inc
- rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector.php
- rules/Privatization/NodeManipulator/VisibilityManipulator.php
refs https://github.com/rectorphp/rector/issues/6619
> Implement DowngradeAbstractPrivateMethodInTrait

- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_overwritten_private_function_of_trait.php.inc
- rules/DeadCode/NodeAnalyzer/IsClassMethodUsedAnalyzer.php
refs https://github.com/rectorphp/rector/issues/6613
> adjust fixture + fixed removing overwriting private functions

- rules/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector.php
- rules/Privatization/NodeManipulator/VisibilityManipulator.php
- src/PhpParser/Parser/PhpParserLexerFactory.php
Ref https://github.com/rectorphp/rector/issues/6593
> Allow smart lexer regardless PHP version

- rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php
- tests/Issues/IssueCreatePublicPropertyOnRename/CreatePublicPropertyOnRenameTest.php
- tests/Issues/IssueCreatePublicPropertyOnRename/Fixture/fixture.php.inc
- tests/Issues/IssueCreatePublicPropertyOnRename/config/configured_rule.php
Closes #632 Fixes https://github.com/rectorphp/rector/issues/6621
> [CodeQuality][Naming] Handle both RenamePropertyToMatchTypeRector and CompleteDynamicPropertiesRector

- tests/Issues/PhpTagsAddedToBlade/Fixture/php_tags_added_to_blade.input.php
- tests/Issues/PhpTagsAddedToBlade/PhpTagsAddedToBladeTest.php
Ensure to rollback content after run for apply the rector rule.
> Fix blade test input

- build/config/config-downgrade.php
- tests/Issues/RenameClassInCallbackFromAssertAnnotation/RenameClassInCallbackFromAssertAnnotationTest.php
Resolves: https://github.com/rectorphp/rector/issues/6624
> Adjust downgrade config for rector build

- build/config/config-downgrade.php
- phpstan.neon
Fixes https://github.com/rectorphp/rector/issues/6624
> Fix downgrade TYPO3 Visitor interface

- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/default_value.php.inc
- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_default_value_more_stmt.php.inc
- rules/Php80/Rector/If_/NullsafeOperatorRector.php
> [Php80] Handle Default value in Else_ not null on NullsafeOperatorRector

- rules-tests/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_closure_call.php.inc
- rules/CodeQuality/NodeAnalyzer/LocalPropertyAnalyzer.php
Closes #666 Fixes https://github.com/rectorphp/rector/issues/6635
> [CodeQuality] Skip Closure call on CompleteDynamicPropertiesRector

- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/fixture_ternary_is_not_null.php.inc
- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/fixture_ternary_is_null.php.inc
- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_ternary_elvis.php.inc
- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_ternary_returns_non_null_in_if_and_else.php.inc
- rules/Php80/Rector/If_/NullsafeOperatorRector.php
Refs: https://github.com/rectorphp/rector/issues/6634
Closes: https://github.com/rectorphp/rector/issues/6634
> add ternary support for NullsafeOperatorRector

- rules-tests/DeadCode/Rector/ClassMethod/RemoveUselessParamTagRector/Fixture/skip_tag_with_generic_type.php.inc
- rules/DeadCode/PhpDoc/DeadParamTagValueNodeAnalyzer.php
> [DeadCode] Skip RemoveUselessParamTagRector on BracketsAwareUnionTypeNode

- scoper.php
- utils/compiler/src/PhpScoper/StaticEasyPrefixer.php
Resolve https://github.com/rectorphp/rector-src/pull/461/files#r689329490
> [Scoper] Fix PHPUnit scoper IsEqual

- rules-tests/DeadCode/Rector/ClassMethod/RemoveUselessReturnTagRector/Fixture/skip_tag_with_generic_type.php.inc
- rules/DeadCode/PhpDoc/DeadParamTagValueNodeAnalyzer.php
- rules/DeadCode/PhpDoc/DeadReturnTagValueNodeAnalyzer.php
> [DeadCode] Skip RemoveUselessReturnTagRector on BracketsAwareUnionTypeNode

- phpstan.neon
- src/Exclusion/ExclusionManager.php
- tests/Exclusion/Fixture/different_norector.php.inc
- tests/Exclusion/Fixture/skip_other_docblocks.php.inc
Local	 merge of https://github.com/rectorphp/rector-src/pull/696
---
* Closes #696
* Closes https://github.com/rectorphp/rector/issues/6638
> improve exclusion manager

- packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php
- phpstan.neon
> [NodeTypeResolver] Clean up PHPStanNodeScopeResolver 

- src/Application/FileProcessor/PhpFileProcessor.php
Fixes https://github.com/rectorphp/rector/issues/6646
> [Core] Avoid removal of contents when error found

- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeMixedTypeDeclarationRector/Fixture/skip_parent_return_self_child_return_parent.php.inc
- rules/DowngradePhp80/Rector/FunctionLike/DowngradeMixedTypeDeclarationRector.php
ref https://github.com/rectorphp/rector/issues/6652
> [DowngradePhp80] Skip child return parent on DowngradeMixedTypeDeclarationRector

- rules-tests/CodeQuality/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector/Fixture/skip_exactly_return_datetime.php.inc
- rules/CodeQuality/NodeManipulator/ClassMethodParameterTypeManipulator.php
- rules/CodeQuality/NodeManipulator/ClassMethodReturnTypeManipulator.php
- rules/CodeQuality/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector.php
ref rectify on https://github.com/rectorphp/rector-src/pull/724#pullrequestreview-735493895 /cc @Bl00D4NGEL
> [CodeQuality] Skip DateTimeToDateTimeInterfaceRector on exactly return DateTime

- rules-tests/CodeQuality/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector/Fixture/skip_exactly_return_datetime.php.inc
- rules/CodeQuality/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector.php
- rules/Defluent/NodeAnalyzer/FluentChainMethodCallNodeAnalyzer.php
- src/NodeAnalyzer/CallAnalyzer.php
Continue of https://github.com/rectorphp/rector-src/pull/730 which `New_` can be in assign first. Re-used existing detect is new instance check.
> [Core] Refactor CallAnalyzer: Move isNewInstance() from FluentChainMethodCallNodeAnalyzer to CallAnalyzer

- rules-tests/CodeQuality/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Fixture/skip_foreach_this_if_class_implements_iterator_aggregate.php.inc
- rules-tests/CodeQuality/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Fixture/skip_foreach_when_iterated_item_is_iterator_aggregate.php.inc
- rules-tests/CodeQuality/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Source/IteratorAggregateImplementation.php
- rules/CodeQuality/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector.php
Based on https://getrector.org/demo/1ec0351f-7789-6576-bb02-3bbbd8617543
refs https://github.com/rectorphp/rector/issues/6643
closes https://github.com/rectorphp/rector/issues/6643
> [CodeQuality] ForeachItemsAssignToEmptyArrayToAssignRector skip classes that implement IteratorAggregate

- rules/CodeQuality/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector.php
- src/FileSystem/PhpFilesFinder.php
Add check for [Smarty](https://www.smarty.net) for template with `.tpl` file as non-PHP files.
> [Core] Add Smarty Support for PhpFilesFinder check non-PHP files

- rules-tests/Php80/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/generic.php.inc
- rules/Php80/NodeAnalyzer/PromotedPropertyCandidateResolver.php
> [Php80] Handle Generic TemplateType on ClassPropertyAssignToConstructorPromotionRector

- rules-tests/Php56/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/skip_with_embedded_html.php.inc
- rules-tests/Php56/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/with_embedded_html.php.inc
- rules/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector.php
- rules/Php56/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
- src/NodeAnalyzer/InlineHTMLAnalyzer.php
> [Php56] Skip AddDefaultValueForUndefinedVariableRector on has InlineHTML

- scoper.php
- utils/compiler/src/PhpScoper/StaticEasyPrefixer.php
Closes https://github.com/rectorphp/rector/issues/6661
> [Scoper] Fix Cannot autowire service "RectorPrefix20210825\Helmich\TypoScriptParser\Parser\Traverser\Traverser"

- phpstan.neon
- rules-tests/CodingStyle/Rector/Use_/RemoveUnusedAliasRector/Fixture/nullable_alias.php.inc
- rules-tests/CodingStyle/Rector/Use_/RemoveUnusedAliasRector/Fixture/under_intanceof.php.inc
- rules/CodingStyle/Naming/NameRenamer.php
Closes https://github.com/rectorphp/rector-src/pull/782 Fixes https://github.com/rectorphp/rector/issues/6666
> [CodingStyle] Handle Nullable Type and under intanceof for RemoveUnusedAliasRector

- rules/EarlyReturn/Rector/If_/ChangeOrIfReturnToEarlyReturnRector.php
- tests/Issues/IssueEarlyReturnAndOrNarrow/Fixture/and_next_or.php.inc
- tests/Issues/IssueReturnBeforeElseIf/Fixture/complex_if_cond_or_without_elseif.php.inc
Handle duplicate ifs and returns like in https://github.com/rectorphp/rector-src/pull/795#issuecomment-909152044 on collection of rules.
> [EarlyReturn] Skip ChangeOrIfReturnToEarlyReturnRector on next node is null or return void

- rules/EarlyReturn/Rector/If_/ChangeOrIfReturnToEarlyReturnRector.php
After PR https://github.com/rectorphp/rector-src/pull/799 that skip left or right is BooleanAnd on ChangeOrIfReturnToEarlyReturnRector, the skip check can be cleaned up.
> [EarlyReturn] Clean up ChangeOrIfReturnToEarlyReturnRector skip check

- config/set/downgrade-php71.php
- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/DowngradeClosureFromCallableRectorTest.php
- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/Fixture/skip_other_static_call.php.inc
- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/config/configured_rule.php
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
> Implements DowngradeClosureFromCallableRector (PHP 7.1).

- phpstan.neon
- rules-tests/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector/Fixture/anonymous_class_alternative.php.inc
- rules-tests/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector/Fixture/anonymous_return_abstract_interface.php.inc
- rules/CodeQuality/Rector/LogicalAnd/LogicalToBooleanRector.php
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
- rules/DowngradePhp72/NodeAnalyzer/OverrideFromAnonymousClassMethodAnalyzer.php
- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
- src/Rector/AbstractRector.php
> [DowngradePhp72] Handle DowngradeParameterTypeWideningRector on anonymous class implements interface

- rules/Php81/Rector/ClassConst/FinalizePublicClassConstantRector.php
- rules/Php81/Rector/Class_/MyCLabsClassToEnumRector.php
- rules/Php81/Rector/MethodCall/MyCLabsMethodCallToEnumConstRector.php
- rules/Php81/Rector/Property/ReadOnlyPropertyRector.php
- src/ValueObject/PhpVersionFeature.php
Fixes https://github.com/rectorphp/rector/issues/6676.
> Add minimum PHP versions for PHP 8.1 rules

- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
- tests/Issues/Issue6677/DoNotTriggerPhpWarningRectorTest.php
- tests/Issues/Issue6677/Fixture/do_not_trigger_php_warning.php.inc
- tests/Issues/Issue6677/config/configured_rule.php
Closes #817 Fixes rectorphp/rector#6677
> [DowngradePhp71][DowngradePhp80] Handle SymmetricArrayDestructuringToListRector + DowngradeNamedArgumentRector

- phpstan.neon
- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/Fixture/class_with_old_property.php.inc
- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/config/configured_rule.php
- rules/Renaming/Rector/PropertyFetch/RenamePropertyRector.php
Closes #820 Fixes rectorphp/rector#6678
> [Renaming] Rename Property name as well for RenamePropertyRector on Class

- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/Fixture/class_with_old_property2.php.inc
- rules-tests/Renaming/Rector/PropertyFetch/RenamePropertyRector/config/configured_rule.php
- rules/Renaming/Rector/PropertyFetch/RenamePropertyRector.php
> [Renaming] Handle ClassLike property on RenamePropertyRector

- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_no_result_usage.php.inc
- rules/Php80/Rector/If_/NullsafeOperatorRector.php
Closes #827 Fixes rectorphp/rector#6680
> [Php80] Fix NullsafeOperatorRector on no result usage

- rules/EarlyReturn/Rector/If_/ChangeOrIfReturnToEarlyReturnRector.php
return array of ifs statements instead of use `nodesToAddCollector` property.
> [EarlyReturn] Returns array of If_ on ChangeOrIfReturnToEarlyReturnRector

- rules/EarlyReturn/Rector/If_/ChangeOrIfContinueToMultiContinueRector.php
like in https://github.com/rectorphp/rector-src/commit/5b17710c25ddb7cd75a31dfbf7bc2ed05072b6e8
> [EarlyReturn] Returns array of If_ on ChangeOrIfContinueToMultiContinueRector

- packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php
- rules/EarlyReturn/Rector/If_/ChangeIfElseValueAssignToEarlyReturnRector.php
- rules/MysqlToMysqli/Rector/Assign/MysqlAssignToMysqliRector.php
PHPStan fix error message after run composer update for the following phpstan error:
```bash
> vendor/bin/phpstan analyse --ansi --error-format symplify
Note: Using configuration file /Users/samsonasik/www/rector-src/phpstan.neon.
1432/1432 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php:47
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> [PHPStan] PHPStan fixes after update symplify

- rules/DeadCode/NodeAnalyzer/ExprUsedInNextNodeAnalyzer.php
- rules/DeadCode/NodeAnalyzer/ExprUsedInNodeAnalyzer.php
- rules/DeadCode/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector.php
- tests/Issues/Issue6675/Fixture/fixture.php.inc
- tests/Issues/Issue6675/MysqlToMysqliRenameRemoveTest.php
- tests/Issues/Issue6675/config/configured_rule.php
Fixes https://github.com/rectorphp/rector/issues/6675
> [MysqlToMySqli][DeadCode] Handle MYSQL_TO_MYSQLI and DEAD_CODE SetList usage

- build/target-repository/README.md
Fixes https://github.com/rectorphp/rector/issues/6694
> Fix broken link in README.md

- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/demo_file.php.inc
- rules-tests/Php80/Rector/If_/NullsafeOperatorRector/Fixture/skip_ternary_no_direct_usage2.php.inc
- rules/Php80/Rector/If_/NullsafeOperatorRector.php
> [Php80] Skip Ternary indirect usage with null else on NullsafeOperatorRector

- build/target-repository/docs/auto_import_names.md
- packages/PostRector/Rector/NameImportingPostRector.php
- rules-tests/CodingStyle/Rector/Namespace_/ImportFullyQualifiedNamesRector/AutoImportNamesOnlyOnChangedFilesTest.php
- rules-tests/CodingStyle/Rector/Namespace_/ImportFullyQualifiedNamesRector/FixtureNameImportingOnChangedFiles/auto_import_names_on_changed_file.php.inc
- rules-tests/CodingStyle/Rector/Namespace_/ImportFullyQualifiedNamesRector/FixtureNameImportingOnChangedFiles/skip_auto_import_names_no_change.php.inc
- rules-tests/CodingStyle/Rector/Namespace_/ImportFullyQualifiedNamesRector/config/import_only_on_changed_files_config.php
- src/Configuration/Option.php
- src/ValueObject/Application/File.php
- In order to apply the Option::AUTO_IMPORT_NAMES only on those files which are really changed by a rector we introduce this new option
> Add new option for auto importing names

- rules-tests/Arguments/Rector/ClassMethod/ArgumentAdderRector/Fixture/argument_without_type_or_default_value.php.inc
- rules-tests/Arguments/Rector/ClassMethod/ArgumentAdderRector/Source/SomeClass.php
- rules-tests/Arguments/Rector/ClassMethod/ArgumentAdderRector/config/configured_rule.php
- rules-tests/Arguments/Rector/ClassMethod/ReplaceArgumentDefaultValueRector/Fixture/param_with_any_values.php.inc
- rules-tests/Arguments/Rector/ClassMethod/ReplaceArgumentDefaultValueRector/Fixture/param_with_null.php.inc
- rules-tests/Arguments/Rector/ClassMethod/ReplaceArgumentDefaultValueRector/Source/SomeClassWithAnyDefaultValue.php
- rules-tests/Arguments/Rector/ClassMethod/ReplaceArgumentDefaultValueRector/config/configured_rule.php
- rules/Arguments/ArgumentDefaultValueReplacer.php
- rules/Arguments/NodeAnalyzer/ChangedArgumentsDetector.php
- rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php
- rules/Arguments/ValueObject/ReplaceArgumentDefaultValue.php
This PR will add the missing default value and type for the arguments already added.
as discussed in https://github.com/rectorphp/rector-laravel/pull/12#discussion_r702424125
> [Arguments] Add the missing default value and type for the added arguments

- packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/keep_with_call_user_func.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/keep_with_call_user_func2.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/normal_array.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/normal_array2.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/normal_array3.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/normal_array4.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/normal_array5.php.inc
- rules/DeadCode/NodeAnalyzer/IsClassMethodUsedAnalyzer.php
> [DeadCode] Skip Array Callable dynamic method on RemoveUnusedPrivateMethodRector

- packages/NodeTypeResolver/PhpDocNodeVisitor/NameImportingPhpDocNodeVisitor.php
- stubs/AutoImport/Annotation/SomeEnum2.php
- tests/Issues/AutoImportDocInUse/Fixture/skip_auto_import_doc_in_use_namespace2.php.inc
- tests/Issues/AutoImportDocInUse/Fixture/skip_auto_import_doc_in_use_namespace3.php.inc
- tests/Issues/AutoImportDocInUse/Source/Annotation/SomeEnum2.php
Continue of https://github.com/rectorphp/rector-src/pull/912
> [NodeTypeResolver] Skip Auto Import from doc on sub namespace class exists when already in use statement by other namespace

- phpstan.neon
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/remove_only_private_property.php.inc
- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/remove_only_private_property2.php.inc
- src/PhpParser/NodeFinder/PropertyFetchFinder.php
Closes #915 Fixes https://github.com/rectorphp/rector/issues/6701
> [DeadCode] Only remove private property from current class on RemoveUnusedPrivatePropertyRector

- rules/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector.php
- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
- tests/Issues/Issue6708/DowngradeMatchToSwitchAndArraySpreadRectorTest.php
- tests/Issues/Issue6708/Fixture/fixture.php.inc
- tests/Issues/Issue6708/Fixture/fixture2.php.inc
- tests/Issues/Issue6708/Fixture/fixture3.php.inc
- tests/Issues/Issue6708/config/configured_rule.php
Fix #927 Closes rectorphp/rector#6708
> [DowngradePhp80][DowngradePhp74] Handle DowngradeMatchToSwitchRector + DowngradeArraySpreadRector

- rules/CodingStyle/Reflection/VendorLocationDetector.php
- src/NodeAnalyzer/VariadicAnalyzer.php
- src/PhpParser/AstResolver.php
Make use of https://github.com/phpstan/phpstan-src/commit/5ddca4279e348a3e9e8ce1b1dbac70459b7ab20c
> [PHPStan 1.0] resolve FunctionReflection getFileName() from main interface

- rules/CodingStyle/Rector/ClassMethod/UnSpreadOperatorRector.php
- rules/CodingStyle/Reflection/VendorLocationDetector.php
- rules/Php80/Rector/ClassMethod/OptionalParametersAfterRequiredRector.php
See https://github.com/phpstan/phpstan-src/commit/3738fcd98a98f5a8ef61b40a4c0c5384b7704714
> [PHPStan 1.0] Remove ReflectionWithFilename

- packages/BetterPhpDocParser/PhpDocNodeVisitor/UnionTypeNodePhpDocNodeVisitor.php
Ref https://github.com/rectorphp/rector-src/runs/4068728595?check_suite_focus=true
> Fix parent converting of union type based on token position

- phpstan.neon
- src/Bootstrap/RectorConfigsResolver.php
based on https://github.com/rectorphp/rector-src/pull/1122#issuecomment-956432175
> [PHPStan] Skip PHPStan error message on RectorConfigsResolver check realpath

- src/PhpParser/Node/Value/ValueResolver.php
- add getStringValue() to value resolver
- make use of assert phpstan extension
> add getStringValue() to value resolver

- config/set/php81.php
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Fixture/some_finfo_open.php.inc
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Fixture/some_ftp_connect.php.inc
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Fixture/some_imap_open.php.inc
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Fixture/some_ldap_connect.php.inc
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Fixture/some_pg_connect.php.inc
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Fixture/some_pspell.php.inc
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/Php81ResourceReturnToObjectRectorTest.php
- rules-tests/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector/config/configured_rule.php
- rules/Php80/NodeManipulator/ResourceReturnToObject.php
- rules/Php80/Rector/FuncCall/Php8ResourceReturnToObjectRector.php
- rules/Php81/Rector/FuncCall/Php81ResourceReturnToObjectRector.php
- rules/Php81/Rector/FuncCall/Php8ResourceReturnToObjectRector.php
- src/ValueObject/PhpVersionFeature.php
for php 8.1 Resolve https://github.com/rectorphp/rector/issues/6749
> [Php 81] Add Php81ResourceReturnToObjectRector

- packages-tests/NameImporting/NodeAnalyzer/UseAnalyzer/UseAnalyzerTest.php
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Fixture/rename_method_and_method_call.php.inc
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Fixture/rename_method_call_when_class_method_exists.php.inc
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Fixture/skip_when_interface.php.inc
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Source/CustomType.php
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Source/Foo.php
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Source/FooInterface.php
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Source/SomeSubscriber.php
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/Source/SubscriberInterface.php
- rules-tests/Renaming/Rector/MethodCall/RenameMethodRector/config/configured_rule.php
- rules/CodingStyle/Naming/NameRenamer.php
- rules/Renaming/Rector/MethodCall/RenameMethodRector.php
- src/NodeManipulator/ClassManipulator.php
Closes #1073 Fixes rectorphp/rector#6691
> [Renaming] Rename class method implements interface with method exists 

- rules/DeadCode/NodeAnalyzer/ExprUsedInNextNodeAnalyzer.php
- rules/DeadCode/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector.php
- tests/Issues/Issue6675/Fixture/fixture.php.inc
- tests/Issues/Issue6675/Fixture/no_namespace.php.inc
The regression is introduced at https://github.com/rectorphp/rector-src/pull/1144#r744013774
This PR restore it to previous fix.
> [MYSQL_TO_MYSQLI] Restore Mysql to Mysqli Behaviour when used with Dead Code SetList

- rules-tests/DeadCode/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/no_usage_outside_anonymous_class.php.inc
- src/PhpParser/NodeFinder/PropertyFetchFinder.php
The regression happen on PR https://github.com/rectorphp/rector-src/pull/1144/files/063002ece76ce8355cc05d49f20b8a35e01d5854#diff-86b64df361694af16991e1552adf6b48c3f54d50137fea43628476ba23f4132c
> [DeadCode] Restore RemoveUnusedPrivatePropertyRector behaviour on no usage outside anonymous class

- packages-tests/ChangesReporting/Annotation/AppliedRectorsChangelogResolver/RectorsChangelogResolverTest.php
- packages/ChangesReporting/Collector/RectorChangeCollector.php
- packages/ChangesReporting/ValueObject/RectorWithLineChange.php
- packages/ChangesReporting/ValueObjectFactory/ErrorFactory.php
- packages/ChangesReporting/ValueObjectFactory/FileDiffFactory.php
- packages/Parallel/Contract/SerializableInterface.php
- src/Application/FileProcessor/PhpFileProcessor.php
- src/Rector/AbstractRector.php
- src/ValueObject/Application/File.php
- src/ValueObject/Application/RectorError.php
- src/ValueObject/ProcessResult.php
- src/ValueObject/Reporting/FileDiff.php
Ref https://github.com/rectorphp/rector/issues/2971
First steps to parallel run - add jsonable value objects 
See inspiration from ECS implementation https://github.com/symplify/symplify/pull/3325
> [Parallel] Add SerializableInterface to File, RectorError and FileDiff value objects

- phpstan.neon
- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/filled_by_trait.php.inc
- rules/CodingStyle/ClassNameImport/UsedImportsResolver.php
Crashes on Sypmlify downgrade - https://github.com/symplify/symplify/runs/4131260815?check_suite_focus=true
> Check namespaced name on non-anonymous class

- config/set/downgrade-php80.php
- config/set/downgrade-php81.php
- packages-tests/NodeTypeResolver/PerNodeTypeResolver/PropertyTypeResolver/PropertyTypeResolverTest.php
- packages/BetterPhpDocParser/Annotation/ChangeResolvedClassInParticularContextForAnnotation.php
- packages/BetterPhpDocParser/ValueObject/ChangeResolvedClassInParticular.php
- packages/BetterPhpDocParser/ValueObject/ChangeResolvedClassInParticularContext.php
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/DowngradePhp80ResourceReturnToObjectRectorTest.php
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/Fixture/skip_different_instance.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/config/configured_rule.php
- rules-tests/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector/DowngradePhp81ResourceReturnToObjectRectorTest.php
- rules-tests/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector/Fixture/skip_different_instance.php.inc
- rules-tests/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector.php
- rules/DowngradePhp81/NodeManipulator/ObjectToResourceReturn.php
- rules/DowngradePhp81/Rector/Instanceof_/DowngradePhp81ResourceReturnToObjectRector.php
Resolve https://github.com/rectorphp/rector/issues/6793 for downgrade for both php 8.1 and php 8.0 object of resource check.
> [DowngradePhp81][DowngradePhp80] Add DowngradePhp81ResourceReturnToObjectRector and DowngradePhp80ResourceReturnToObjectRector

- build/target-repository/docs/rector_rules_overview.md
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/Fixture/different_check.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradePhp80ResourceReturnToObjectRector/Fixture/skip_combine_check_with_is_resource.php.inc
- rules/DowngradePhp81/NodeManipulator/ObjectToResourceReturn.php
Handle https://github.com/rectorphp/rector/commit/b8ef7203efd26601b4a8d0a3883cd698a451b5d3#r59655762
> [DowngradePhp81/80] Skip combine check with is_resource and instanceof Object

- bin/generate-changelog.php
- build/target-repository/composer.json
- composer.json
- phpstan.neon
- add generate-changelog.php helper command
- open 0.12-dev
* Inspired from PHPStan https://github.com/phpstan/phpstan-src/blob/master/bin/generate-changelog.php
> [CI] Add generate changelog helper command

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/skip_conditional_throw.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/skip_method_throwing.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector.php
Close #1187 Close https://github.com/rectorphp/rector-src/pull/1188
> [TypeDeclaration] Skip Conditional on ReturnNeverTypeRector

- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/skip_conditional_throw2.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector/Fixture/skip_conditional_throw3.php.inc
- rules/TypeDeclaration/Rector/ClassMethod/ReturnNeverTypeRector.php
> [TypeDeclaration] Skip conditional Throw_ on ReturnNeverTypeRector

- rules-tests/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector/DoWhileBreakFalseToIfElseRectorTest.php
- rules-tests/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector/Fixture/double_break.php.inc
- rules-tests/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector/Fixture/if_else.php.inc
- rules-tests/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector/Fixture/single_break.php.inc
- rules-tests/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector/Fixture/some_class.php.inc
- rules-tests/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector/config/configured_rule.php
- rules/CodeQuality/Rector/Do_/DoWhileBreakFalseToIfElseRector.php
Closes https://github.com/rectorphp/rector/issues/6801
> [CodeQuality] Add DoWhileBreakFalseToIfElseRector

- config/set/php81.php
- phpstan.neon
- rules-tests/Php81/Rector/ClassMethod/NewInInitializerRector/Fixture/some_class.php.inc
- rules-tests/Php81/Rector/ClassMethod/NewInInitializerRector/NewInInitializerRectorTest.php
- rules-tests/Php81/Rector/ClassMethod/NewInInitializerRector/config/configured_rule.php
- rules/Php81/Rector/ClassMethod/NewInInitializerRector.php
- src/PhpParser/Node/BetterNodeFinder.php
- src/ValueObject/PhpVersionFeature.php
* RFC: https://wiki.php.net/rfc/new_in_initializers
* Ref https://github.com/rectorphp/rector/issues/6792
> [PHP 8.1] Add NewInInitializerRector

- packages/BetterPhpDocParser/Annotation/ChangeResolvedClassInParticularContextForAnnotation.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/join_table.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
@fezfez this is based on @usu comment at https://github.com/rectorphp/rector-src/pull/1142#issuecomment-966572068
> [Php80] Fix InverseJoinColumn Annotation to Attribute on AnnotationToAttributeRector

- src/Error/ExceptionCorrector.php
> Add BOOTSTRAP_FILES hint to AutoloadExceptionMessage

- rules-tests/Php74/Rector/Closure/ClosureToArrowFunctionRector/Fixture/nested_closures.php.inc
- src/Validation/InfiniteLoopValidator.php
> [Php74] Handle nested closure on ClosureToArrowFunctionRector

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/schema_after_table_name_with_unique_constraint.php.inc
- rules/Php80/Rector/Class_/AnnotationToAttributeRector.php
Closes https://github.com/rectorphp/rector/issues/6809
> [Php80] Handle schema on Table with UniqueConstraint on AnnotationToAttributeRector

- build/config/config-downgrade.php
- full_build.sh
Fixes https://github.com/rectorphp/rector/issues/6813
> [Scoped] Fix AsciiSlugger::slug does not match SluggerInterface slug parameter typing

- config/set/dead-code.php
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedParamInRequiredAutowireRector/Fixture/skip_no_reqiured_attribute_or_annotation.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedParamInRequiredAutowireRector/Fixture/with_required_annotation.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedParamInRequiredAutowireRector/Fixture/with_required_attribute.php.inc
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedParamInRequiredAutowireRector/RemoveUnusedParamInRequiredAutowireRectorTest.php
- rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedParamInRequiredAutowireRector/config/configured_rule.php
- rules/DeadCode/Rector/ClassMethod/RemoveUnusedParamInRequiredAutowireRector.php
- src/Rector/AbstractRector.php
Fixes https://github.com/rectorphp/rector/issues/6830
> [DeadCode] Add RemoveUnusedParamInRequiredAutowireRector

- packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php
- packages/NodeTypeResolver/PHPStan/Scope/TraitScopeFaker.php
- rules/CodeQuality/Rector/If_/ExplicitBoolCompareRector.php
- rules/CodingStyle/Rector/FuncCall/CountArrayToEmptyArrayComparisonRector.php
- rules/TypeDeclaration/TypeAnalyzer/GenericClassStringTypeNormalizer.php
- src/PhpParser/NodeTransformer.php
- tests/Issues/Issue6561/Fixture/on_call_method_return_array.php.inc
> Decouple TraitScopeFaker

- build/target-repository/docs/rector_rules_overview.md
- config/set/privatization.php
- rules-tests/Privatization/Rector/Class_/ChangeGlobalVariablesToPropertiesRector/ChangeGlobalVariablesToPropertiesRectorTest.php
- rules-tests/Privatization/Rector/Class_/ChangeGlobalVariablesToPropertiesRector/Fixture/fixture.php.inc
- rules-tests/Privatization/Rector/Class_/ChangeGlobalVariablesToPropertiesRector/Fixture/global_after.php.inc
- rules-tests/Privatization/Rector/Class_/ChangeGlobalVariablesToPropertiesRector/Fixture/skip_read_only_global.php.inc
- rules-tests/Privatization/Rector/Class_/ChangeGlobalVariablesToPropertiesRector/config/configured_rule.php
- rules/Privatization/Rector/Class_/ChangeGlobalVariablesToPropertiesRector.php
Cherry picked from https://github.com/rectorphp/rector-src/pull/1297
> Move ChangeGlobalVariablesToPropertiesRector from ClassMethod to Class_ node, to keep the minimal changed scope in active nodes

- rules/CodingStyle/Rector/ClassMethod/FuncGetArgsToVariadicParamRector.php
- remove unused private method args/param - @todo make Rector rule for it
- explicit types
> Fix Param to Method call override

- packages/BetterPhpDocParser/ValueObject/NodeTypes.php
- rules-tests/Renaming/Rector/Name/RenameClassRector/Fixture/rename_generic_template_of_fixture.php.inc
- rules/Php80/NodeAnalyzer/PhpAttributeAnalyzer.php
- rules/Transform/Rector/Class_/AddAllowDynamicPropertiesAttributeRector.php
- src/ValueObject/MethodName.php
Closes #1309 Fixes https://github.com/rectorphp/rector/issues/6835
> [Renaming] Handle rename template tag of class on RenameClassRector

- rules-tests/Transform/Rector/StaticCall/StaticCallToNewRector/Fixture/some_class.php.inc
- rules/Transform/Rector/StaticCall/StaticCallToNewRector.php
Closes https://github.com/rectorphp/rector-symfony/pull/74 Fixes https://github.com/rectorphp/rector-symfony/issues/73
> [Transform]Fix keep args on StaticCallToNewRector

- packages/FamilyTree/NodeAnalyzer/ClassChildAnalyzer.php
Closes https://github.com/rectorphp/rector-symfony/issues/61
> Fix child method check - both on native

- rules/CodingStyle/Application/UseImportsAdder.php
- tests/Issues/AutoImportBeforeDocblock/AutoImportBeforeDocblockTest.php
- tests/Issues/AutoImportBeforeDocblock/Fixture/fixture.php.inc
- tests/Issues/AutoImportBeforeDocblock/config/configured_rule.php
Fixes https://github.com/rectorphp/rector/issues/6833
> [PostRector] Fixing auto import to not placed before top docblock

- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/nested_nested_arrays.php.inc
Ref https://github.com/rectorphp/rector/issues/6825#issuecomment-981508586
> add test case for nested attribute arrays

- .github/workflows/e2e.yaml
- e2e/template-extends/composer.json
@staabm this is update path e2e bin location and autoload to make work on PR.
> [e2e] Update e2e autoload and path to current ../../bin

- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/integer_keys.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_get_iterator.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_iterator_to_array.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_parse_url.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_simple_array_merge.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_spread_array_merge.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_string_keys.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp74/skip_string_keys_from_functions.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/integer_keys.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/parse_url.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/skip_get_iterator.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/skip_iterator_to_array.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/skip_simple_array_merge.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/skip_spread_array_merge.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/skip_string_keys_from_functions.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/FixturePhp81/string_keys.php.inc
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Php74ArraySpreadInsteadOfArrayMergeRectorTest.php
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Php81ArraySpreadInsteadOfArrayMergeRectorTest.php
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/config/configured_rule_php74.php
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/config/configured_rule_php81.php
- rules/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector.php
- src/ValueObject/PhpVersionFeature.php
refs https://github.com/rectorphp/rector/issues/6792
> Array merge to unpacking

- rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_no_type.php.inc
- rules/Php81/Rector/Property/ReadOnlyPropertyRector.php
part of https://github.com/rectorphp/rector/issues/6844 /cc @canvural
> [Php81] Skip no type property on ReadOnlyPropertyRector

- rector.php
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/config/configured_rule_php74.php
- rules-tests/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/config/configured_rule_php81.php
- rules/DowngradePhp80/Rector/New_/DowngradeArbitraryExpressionsSupportRector.php
- rules/Php74/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector.php
- rules/Php81/Rector/Property/ReadOnlyPropertyRector.php
- rules/Transform/Rector/FuncCall/ArgumentFuncCallToMethodCallRector.php
The SetList were commented at PR https://github.com/rectorphp/rector-src/pull/1344/files#diff-d933a2ad57daa43419b483d3f1ddedaec7aa44933007fead9f9437390f596f4a . 
This PR re-enable it.
> [Config] Re-enable Config SetList on rector.php

- composer.json
- packages-tests/NodeTypeResolver/PerNodeTypeResolver/ClassAndInterfaceTypeResolver/ClassTypeResolverTest.php
- packages/NodeNameResolver/NodeNameResolver/ClassNameResolver.php
- packages/NodeTypeResolver/NodeTypeResolver/ClassAndInterfaceTypeResolver.php
- phpstan.neon
- rules/CodingStyle/ClassNameImport/UsedImportsResolver.php
- rules/Php74/TypeAnalyzer/ObjectTypeAnalyzer.php
- src/Reflection/ReflectionResolver.php
Closes https://github.com/rectorphp/rector-src/pull/1356
> [Dep] Update to php-parser ^4.13.2

- packages/ChangesReporting/Output/ConsoleOutputFormatter.php
- packages/ChangesReporting/ValueObjectFactory/ErrorFactory.php
- phpstan.neon
- rector.php
- rules/Composer/Application/FileProcessor/ComposerFileProcessor.php
- src/Application/ApplicationFileProcessor.php
- src/Application/FileProcessor/PhpFileProcessor.php
- src/Console/Command/ProcessCommand.php
- src/Contract/Processor/FileProcessorInterface.php
- src/UnusedPrivateConstant.php
- src/ValueObject/Application/File.php
- src/ValueObject/Application/SystemError.php
- src/ValueObject/ProcessResult.php
- src/ValueObjectFactory/ProcessResultFactory.php
- tests/Application/ApplicationFileProcessor/ApplicationFileProcessorTest.php
- tests/Application/ApplicationFileProcessor/Source/TextFileProcessor.php
- tests/Application/ApplicationFileProcessor/config/configured_rule.php
Ref https://github.com/rectorphp/rector/issues/2971
> [Parallel] Refactor file processor to return arrays of data to allow json

- src/Application/FileProcessor/PhpFileProcessor.php
- src/ValueObject/Application/File.php
Ref https://github.com/rectorphp/rector/issues/2971
> [Parallel] Simplify PhpFileProcessor

- packages/ChangesReporting/Output/JsonOutputFormatter.php
- rules-tests/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector/Fixture/skip_instanceof.php.inc
- rules-tests/Transform/Rector/MethodCall/MethodCallToMethodCallRector/config/configured_rule.php
- rules/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector.php
- rules/Transform/NodeTypeAnalyzer/TypeProvidingExprFromClassResolver.php
- rules/Transform/Rector/MethodCall/MethodCallToMethodCallRector.php
- src/NodeAnalyzer/PropertyPresenceChecker.php
- src/PhpParser/AstResolver.php
Fixes https://github.com/rectorphp/rector-src/pull/1407#issuecomment-986961214
> [PHP 7.4] Skip dependency on native ReflectionProperty->getType()

- src/Application/FileProcessor/PhpFileProcessor.php
Fixes https://github.com/rectorphp/rector/issues/6849
> [Core] Fix count files and diff changes on FileProcessor

- build/target-repository/docs/rector_rules_overview.md
- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/return_throw_variable.php.inc
- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/throw_property_fetch.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
- src/NodeManipulator/IfManipulator.php
Fixing for https://github.com/symplify/monorepo-builder/blob/5e1332f534391014483f0a9ef592e5106d08dbc1/vendor/symfony/console/Style/SymfonyStyle.php#L384
> [DowngradePhp80] Add return property downgrade case

- packages/PostRector/Collector/NodesToAddCollector.php
- rules/CodingStyle/Rector/Assign/SplitDoubleAssignRector.php
- re-use CallLike
- return nodes instead of adding
> [DX] Less addNodeAfterNode() methods

- composer.json
cc @samsonasik I've tagged new Symplify version, let's see how stringy goes
> Bump to Symplify 10.0.1 stable

- build/config/config-downgrade.php
Fixes error https://github.com/rectorphp/rector-src/runs/4468953091?check_suite_focus=true#step:14:77
> [Scoped] Fix downgrade error on symfony/Event*

- .github/workflows/build_scoped_rector.yaml
- build/config/config-downgrade.php
Continue of https://github.com/rectorphp/rector-src/pull/1435
> [Scoped] Fix downgrade error on symfony/console/Tester

- .github/workflows/build_scoped_rector.yaml
- full_build.sh
Continue https://github.com/rectorphp/rector-src/pull/1436
> [Scoped] Require symfony-eventdispatcher on build

- .github/workflows/build_scoped_rector.yaml
Continue of https://github.com/rectorphp/rector-src/pull/1437
> [Scoped] Fix exclude symfony/console/Tester

- .github/workflows/build_scoped_rector.yaml
- build/config/config-downgrade.php
- full_build.sh
based on https://github.com/rectorphp/rector-src/pull/1438#issuecomment-989856871
> [Scoped] Skip symfony console Event and EventListener and exclude in parallel-lint

- packages/PHPStanStaticTypeMapper/TypeMapper/StaticTypeMapper.php
- packages/StaticTypeMapper/ValueObject/Type/SimpleStaticType.php
- phpstan.neon
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddReturnTypeDeclarationRector/Fixture/return_of_static.php.inc
- rules-tests/TypeDeclaration/Rector/ClassMethod/AddReturnTypeDeclarationRector/config/configured_rule.php
- rules/TypeDeclaration/Rector/ClassMethod/AddReturnTypeDeclarationRector.php
- rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromReturnNewRector.php
- src/ValueObject/PhpVersionFeature.php
Helps with https://github.com/rectorphp/rector-symfony/commit/041b6a55afbf249daea857459a978dd8308dd72d#diff-ad5389e0b0526eba44cae5f18f56becae724b7d7ccc85cb44019eba5f85806f1R341
> Add SimpleStaticType for return type completion
